= F+D Forth history

.2015-06-02:

Start, based on the disassembled code of Abersoft Forth
(http://programandala.net/en.program.abersoft_forth.html).

First changes:

Some fig-Forth words are renamed with their modern forms: `vlist` as
`words`, `-dup` as `?dup`, `minus` as `negate`, `dminus` as
`dnegate`, `s->d` as `s>d`, `mon` to `bye`, `free` as `unused`.

Old synonyms are removed: `end` and `endif`.

The editor is removed.

`branch` and `back` are modified to do absolute branches.  The
branches are converted with a simple substitution, thanks to the
comments prepared by the disassembling of Abersoft Forth.

New words, from the Afera library: `\`, `.(`, `char` and `[char]`,
`2-`, `1-`, `2*`.

`2+` and `1+` are converted to Z80.

`forth` is not immediate any more.

`'` is converted to non-immediate; new immediate version: `[']`.

.2015-06-03:

`dliteral` is renamed as `2literal`.

Removed: `verify`.

.2015-06-04:

New: `upperc` and `uppers`.

Improvement: `-find` is made case insensitive.

`key` is documented.

Removed: `udg`, `init-disc`, `.cpu`.

New: `<>`.

Improvement: the lower part of the screen can be used.

Removed: `loadt`, `savet`, `(tape)` and tape headers.

Removed: `triad`.

Change: `inp` renamed as `p@`; `outp` renamed as `p!`.

Change: stacks and buffers are moved to the bottom of the memory map,
before the interpreter. They must be below 0xC000 in order to use the
memory banks.

Change: `r` renamed as `r@`; the Z80 Z80 code of `i` is moved to `r@`,
and the cfa of `i` is pointed to the pfa of `r@`. This is logical and
faster (formerly `r` was a colon word that called `i`).

New: `clit` and `cliteral`. Their code ocuppies 46 bytes, but there
are 84 compiled bytes that save one byte when using `clit` instead of
`lit`, and it's faster.

Change: `bleep` is moved to the blocks disk.

Improvement: `quit` is optimized: faster and smaller.

New: `bounds`; used in `type`.

Removed: `not` (synonym of `0=`).

Change: `offset` deactivated.

New: `block>sector` and first tries with the new version of `r/w`,
that uses the sectors of the disk.  The screens can be listed, but
only the first time. They are shown corrupted when trying to access
them more than once. Something is wrong.

.2015-06-05:

New: `nip`, `tuck`.

Change: `2drop` rewritten in Z80.

New: `rdrop`, in Z80 (`exit` is pointed to it); `2rdrop` and `unloop`.

Removed: `plot` (faster version, from Afera, added to the blocks
disk); `draw` (faster version will be create).

Improvement: Error messages are included in screens 4 and 5 of the
blocks disk.  In order to avoid numbers 0 and 16 (that coincide with
the first lines of screens 4 and 5, and are incompatible with the fsb
format), some error messages are reorganized (and updated in the main
source).

New: `-rot` in the blocks disk.
