= Solo Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2016-11-16

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

== Description

Solo Forth is a modern Forth system for the ZX Spectrum 128 computer
and later models.

Solo Forth is focused on cross development of Forth programs for this
platform, using a ZX Spectrum emulator and all modern development
tools provided by a Linux-like OS.

Solo Forth can be used also as a stand-alone Forth System (for
example, using its own block editor), on a ZX Spectrum emulator or
(provided the disk images are converted to actual disks) a real
machine.  But that's not what Solo Forth was developed for.

Home page: http://programandala.net/en.program.solo_forth.html

== History and current status

The
http://programandala.net/en.program.solo_forth.history.html[development
history] started on 2015-05-30.

As of 2016-11-13 Solo Forth is under active development. It's very
usable and stable on G+DOS, and it's already used to develop some
projects in Forth.

== Target platforms

Solo Forth needs a ZX Spectrum with 128 KiB of RAM and disk drives.
Therefore it can not run on a ZX Spectrum 48, but it can be used to
create programs compatible with a ZX Spectrum 48 without disk drives.

=== ZX Spectrum 128 with G+DOS

Solo Forth was first intended for a ZX Spectrum 128 with G+DOS
(provided by the Plus D interface).  The support for G+DOS is almost
complete, both in the kernel and the library.

=== ZX Spectrum 128 with TR-DOS

TR-DOS (provided by the Beta 128 Disk interface) is supported but with
some limitations, which will be solved in a future version of Solo
Forth:

- There are no words to use disk files yet.
- There's no way to change the current drive yet.  This means the
  library can be used only when the library disk is in drive A.

=== ZX Spectrum +3 with +3DOS

Support for +3DOS is still in a very initial stage.  The Forth system
boots, but there's no way to access the library disks yet, so in
practice it's useless.

=== Future target platforms

The DOS support in Solo Forth is modular, so in theory it would not be
difficult to add support for a more advanced DOS, like IDEDOS,
ResiDOS, ESXDOS...

== How to run

=== ZX Spectrum 128 with G+DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Plus D disk interface.
2. "Insert" the file <disks/gplusdos/disk0.mgt> as disk 1 of the Plus D
   disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `run` in BASIC. G+DOS will be loaded from disk and Solo Forth
   will be autoloaded.

=== ZX Spectrum 128 with TR-DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Beta 128 disk interface.
2. "Insert" the file <disks/trdos/disk0.trd> as disk A of the Beta 128
   disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `randomize usr 15616` in BASIC. This will enter the TR-DOS
   command line, which uses tokens, like the ZX Spectrum 48.
5. Type the `R` key to get the `RUN` command and press the `Enter`
   key. This will autoload Solo Forth.

=== ZX Spectrum +3 (or ZX Spectrum +3e)

1. Run a ZX Spectrum emulator and select a ZX Spectrum +3.
2. "Insert" the file <disks/plus3dos/disk0.180.dsk> as disk A of the
   ZX Spectrum +3.
3. Choose "Loader" from the ZX Spectrum +3 start menu. Solo Forth will
   be autoloaded.

There's no way to access the library disks yet, so the system is
almost useless on +3DOS.

== How to use the library

The library disk contains the source code in Forth blocks, written
directly on the disk sectors, without any filesystem.  In order to use
the library, follow these steps:

1. Run Solo Forth.
2. Insert the the library disk:
** In G+DOS: "Insert" the file <disks/gplusdos/disk1_lib.mgt> as disk
   2 of the Plus D disk interface.
** In TR-DOS: "Insert" the file <disks/trdos/disk1_lib.trd> as disk A
   of the Beta 128 disk interface.
3. Type `2 load`. Block 2 will be loaded from the library disk. This
   block contains `need` and related words.
4. Type `need name`, were "name" is the name of the word or tool you
   want to load from the library.

Disk image number 1 contains only the library.  Disk images from
number 2 contain the library plus sample games, benchmarks and test,
as their filenames read.

`need` searches the index line (line 0) of all blocks of the disk for
the first occurence of the required word, within a configurable range
of blocks (using the variables `first-locatable` and
`last-locatable`). This can be slow. But (from version 0.11.0) you can
create an index to access the contents of the library almost
instantaneously:

1. Load the indexer with `need indexer`.
2. Execute it with `indexer`.

The indexer creates an index (actually, a Forth word list) and changes
the default behaviour of `need` and related words. Then `need name`
will automatically start loading the first block where the word "name"
is defined.

NOTE: At the time of writing (2016-11-16) the indexing takes 195
seconds (at 100% the speed of the real machine) and the index uses c.
12 KiB of "far memory" (so called in Solo Forth): a virtual 64 KiB
space formed by 4 configurable memory banks, independent from the main
memory, used to store the definition headers (and also usable by the
programmer).

== How to build

If you modify the kernel or the library, you need to build the system.

First, see the requirements listed in the header of <Makefile> file
and install the required programs. Then enter the project directory
and use one of the following commands to build the disk images for
your DOS of choice:

|===
| DOS          | Command

| G+DOS        | `make gplusdos`
| TR-DOS       | `make trdos`
| +3DOS        | `make plus3dos`
| All of them  | `make all` or simply `make`
|===

The correspondent disk images will be recreated under the <disks>
directory.

== Documentation

So far the only documentation is this file and the sources.  Most
Forth words are fully documented in their comments in the sources.
Special markups are used in order to extract those comments in the
future and convert them into an independent manual.

== Git repository

The Git repository of Solo Forth was created from development backups
on 2016-03-12. Later commits are "real".
