= Solo Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2017-02-18
:toc:
:linkattrs:

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

// Last modified 201702182121

// tag::description[]

== Description

Solo Forth is a modern http://forth-standard.org[standard
Forth,role="external"] system under development for the ZX Spectrum
128 computer and later models.

Solo Forth is focused on cross development of Forth programs for this
platform, using a ZX Spectrum emulator on a GNU/Linux operating system
(in theory, other kind of operating system could be used as well).

Solo Forth can be used also as a stand-alone Forth System on a ZX
Spectrum emulator or the real computer, but that's not what it was
developed for.

.Main features

- Fast Direct Threaded Code (DTC) implementation.
- A kernel as small as possible (c. 9400 bytes at the moment, and
  shrinking).
- Definition headers separated from code, and stored in banked memory.
- Transparent access to 64 KiB of banked memory.
- Big <<_library,library>> of useful source code, well organized for
  easy of use.
- Modular <<_targets,DOS support>>.
- Fully documented source code.
- Full documentation.

// end::description[]

// tag::history[]

== History and current status

The development started on 2015-05-30, from the
http://programandala.net/en.program.abersoft_forth[disassembled code
of Abersoft Forth], a tape-based fig-Forth 1.1 for ZX Spectrum 48.

As of 2017-02-18 Solo Forth is under active development. It's very
stable, and it's being used to develop a couple of projects in Forth.

// end::history[]

// tag::target[]

[id=_target]
== Target platforms

Solo Forth needs a ZX Spectrum with 128 KiB of RAM and disk drives.
Therefore it can not run on a ZX Spectrum 48, but in theory it could
be used to develop Forth programs that run on a ZX Spectrum 48.

.ZX Spectrum 128 with the Plus D interface: G+DOS

The G+DOS support is the most advanced. Only some file-management
words have to be fixed, improved or implemented yet.

This was the first target (in fact, the only planned target at the
beginning), and it's also the platform of choice for development of
projects in Solo Forth, because of its excellent features:

- Very fast disk operations.
- Big disk capacity (800 KiB).
- It uses only the RAM of the Plus D interface.

.ZX Spectrum 128 with the Beta 128 Disk interface: TR-DOS

The TR-DOS support is still basic. The blocks disks can be used, but
most file-management words are still under development.

TR-DOS is much slower than G+DOS, it uses some RAM from the computer
(0x170 bytes), and the maximum capacity of its disks is smaller (636
KiB of useful space), but it can handle 4 disk drives at the same
time, what makes it an interesting choice in some cases. For example,
to compile a program from the third drive, using the library on the
second drive during the process, and also reading or manipulating the
files on the first drive; or just to use a total 2544 blocks (636*4).

.ZX Spectrum +3 and ZX Spectrum +3e: +3DOS

The +3DOS support is still in a very initial stage.  The Forth system
boots, but there's no way to use the blocks disks yet or to manipulate
disk files, so in practice it's useless.

+3DOS is also slower than G+DOS, and somehow its by-design
compatibility with CP/M is an issue.  But its features and API are
excellent and very well documented. And anyway it's the door to
support <<_future,future platforms>> like IDEDOS and ResiDOS.

.Future

The DOS support in Solo Forth is modular, so in theory it would not be
too difficult to support also more powerful DOSs in future versions,
like
http://www.worldofspectrum.org/zxplus3e/technical.html[IDEDOS,role="external"],
http://www.worldofspectrum.org/residos/[ResiDOS,role="external"], and
http://esxdos.org[esxDOS,role="external"]. This will let Solo Forth
use hard drives, flash cards, and much more memory, beside many other
new features.

.Far future

Porting the G+DOS version of Solo Forth to http://worldofsam.org[SAM
Coupé,role="external"] (the powerful cousin of ZX Spectrum) would be
feasible...

// end::target[]

// tag::tree[]

== Directory tree

....
.
├── backgrounds       Version background images
├── bin               Binary files needed to build disk 0
│   ├── fonts         Fonts for the supported screen modes
│   ├── addons        Code that is loaded from disk
│   │                 because it's not assembled in the library yet
│   └── sys           DOS files
├── disks             Disk images ready to use
│   ├── gplusdos      For G+DOS
│   ├── plus3dos      For +3DOS
│   └── trdos         For TR-DOS
├── doc               Documentation
├── make              Files used by `make` to build the system
├── screenshots       Version screenshots
├── src               Sources
│   ├── inc           Z80 symbols files
│   ├── lib           Library
│   ├── loader        BASIC loader for disk 0
│   ├── addons        Code that is loaded from disk
│   └── doc           Files used to build the documentation
├── tmp               Temporary files created by `make`
├── tools             Development and user tools
└── vim               Vim files
    ├── ftdetect      File type detection
    └── syntax        Syntax highlighting

....

// end::tree[]

// tag::disks[]
== Disks

The <disks> directory of the <<_tree,directory_tree>> contains the
disk images:

....
disks/*/disk_0_boot.*
disks/*/disk_1_library.*
disks/*/disk_2_games.*
disks/*/disk_3_workbench.*
....

The subdirectory name and the filename extension depend on the DOS.

- Disk 0 is the boot disk. It contains the BASIC loader, the Solo
  Forth binary, some addons (i.e. compiled code that is not part of
  the library yet) and fonts for the supported screen modes. For
  +3DOS, two boot disk images are included, with different sizes.
- Disk 1 contains the sources of the library.
- Disk 2 contains some little sample games.
- Disk 3 contains tests and benchmarks used during the development.

WARNING: Disks 1, 2 and 3 are Forth blocks disks: They store the Forth
blocks directly on the disk sectors, without any file system.
Therefore their contents can not be accessed with ordinary DOS
commands.

// end::disks[]

// tag::run[]

[id=_run]
== How to run

=== On ZX Spectrum 128 with G+DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Plus D disk interface.
2. "Insert" the file <disks/gplusdos/disk_0_boot.mgt> as disk 1 of the
   Plus D disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `run` in BASIC. G+DOS will be loaded from disk, and Solo Forth
   as well.

=== On ZX Spectrum 128 with TR-DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Beta 128 disk interface.
2. "Insert" the file <disks/trdos/disk_0_boot.trd> as disk A of the
   Beta 128 disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `randomize usr 15616` in BASIC (or just `run usr15360` to save
   seven keystrokes). This will enter the TR-DOS command line, which
   uses keyboard tokens, like the ZX Spectrum 48footnote:[Only while
   the cursor is in 'K' mode; in 'L' mode keywords can be typed in
   full; unfortunately, the only way to get 'L' mode is the following:
   type some token first, e.g. `REM` (with the 'E' key), then type the
   DOS command in full, and finally delete the `REM` token from the
   start of the line.].
5. Type the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== On ZX Spectrum +3 or ZX Spectrum +3e

1. Run a ZX Spectrum emulator and select a ZX Spectrum +3 or
   http://www.worldofspectrum.org/zxplus3e/[ZX Spectrum
   +3e,role="external"].
2. "Insert" the file <disks/plus3dos/disk_0_boot.180.dsk> (or
   <disks/plus3dos/disk_0_boot.720.dsk>, depending on the capacity of
   the drive) as disk A of the ZX Spectrum +3(e).
3. Choose "Loader" from the ZX Spectrum +3(e) start menu. Solo Forth will
   be loaded from disk.

// end::run[]

// tag::library[]

[id=_library]
== The library

NOTE: At the moment, the library can not be used on +3DOS.

The library disk contains the source code in Forth blocks, written
directly on the disk sectors, without any filesystem.  In order to use
the library, follow these steps:

1. <<_run,Run Solo Forth>>.
2. Insert the library disk:
** In G+DOS: "Insert" the file <disks/gplusdos/disk_1_library.mgt> as
   disk 2 of the Plus D disk interface. Type `2 set-drive throw` to
   make drive 2 the current one.
** In TR-DOS: "Insert" the file <disks/trdos/disk_1_library.trd> as
   disk B of the Beta 128 disk interface. Type `1 set-drive throw` to
   make drive 1 (="B") the current one.
3. Type `1 load` to load block 1 from the library disk. By convention,
   block 0 can not be loaded (is is used for comments), and block 1 is
   used as a loader.  In Solo Forth, block 1 contains just `2 load`,
   in order to load the `need` tool and related words from block 2.
4. Type `need name`, were "name" is the name of the word or tool you
   want to load from the library.

// end::library[]

== Documentation

A HTML manual is included in the <doc> directory.  It is automatically
built from the source files, which are fully documented, and from
secondary files as well, like this README file, which in fact is only
an extract from the manual.

The manual is a work in progress. At the moment it contains the basic
information and a complete glossary with cross references.  A section
to describe the contents of the library modules is under development.

