= Solo Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2017-02-18
:toc:
:linkattrs:

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html


// tag::description[]

== Description

Solo Forth is a modern http://forth-standard.org[standard
Forth,role="external"] system under development for the ZX Spectrum
128 computer and later models.

Solo Forth is focused on cross development of Forth programs for this
platform, using a ZX Spectrum emulator on a GNU/Linux operating system
(in theory, the cross development could be done on other kind of
operating system as well, but this has not been tried).

Solo Forth can be used also as a stand-alone Forth System on a ZX
Spectrum emulator or the real computer, but that's not what it was
developed for.

.Main features

- Fast Direct Threaded Code (DTC) implementation.
- A kernel as small as possible (c. 9400 bytes at the moment, and
  shrinking).
- Definition headers separated from code, and stored in banked memory.
- Transparent access to 64 KiB of banked memory.
- Big <<_library,library>> of useful source code, well organized for
  easy of use.
- Modular <<_targets,DOS support>>.
- Fully documented source code.
- Full documentation.

// end::description[]

// tag::history[]

== History and current status

The development started on 2015-05-30, from the
http://programandala.net/en.program.abersoft_forth[disassembly of
Abersoft Forth], a tape-based fig-Forth 1.1 for ZX Spectrum 48.

As of 2017-02-18 Solo Forth is under active development. It's very
stable, and it's already used to develop some projects in Forth.

// end::history[]

// tag::target[]

[id=_target]
== Target platforms

Solo Forth needs a ZX Spectrum with 128 KiB of RAM and disk drives.
Therefore it can not run on a ZX Spectrum 48, but in theory it could
be used to develop Forth programs that run on a ZX Spectrum 48.

.ZX Spectrum 128 with the Plus D interface: G+DOS

The G+DOS support is the most advanced. Only some file-management
words have to be fixed, improved or implemented yet.

This was the first target (in fact, the only planned target at the
beginning), and it's also the platform of choice for development of
projects in Solo Forth, because of its excellent features:

- Very fast disk operations.
- Big disk capacity (800 KiB).
- It uses only the RAM of the Plus D interface.

.ZX Spectrum 128 with the Beta 128 Disk interface: TR-DOS

The TR-DOS support is still basic. The blocks disks can be used, but
most file-management words are still under development.

TR-DOS is much slower than G+DOS, it uses some RAM from the computer
(0x170 bytes), and the maximum capacity of its disks is smaller (636
KiB of useful space), but it can handle 4 disk drives at the same
time, what makes it an interesting choice in some cases. For example,
to compile a program from the third drive, using the library on the
second drive during the process, and also reading or manipulating the
files on the first drive; or just to use a total 2544 blocks (636*4).

.ZX Spectrum +3 and ZX Spectrum +3e: +3DOS

The +3DOS support is still in a very initial stage.  The Forth system
boots, but there's no way to use the blocks disks yet or to manipulate
disk files, so in practice it's useless.

+3DOS is also slower than G+DOS, and somehow its by-design
compatibility with CP/M is an issue.  But its features and API are
excellent and very well documented. And anyway it's the door to
support <<_future,future platforms>> like IDEDOS and ResiDOS.

.Future

The DOS support in Solo Forth is modular, so in theory it would not be
too difficult to support also more powerful DOSs in future versions,
like
http://www.worldofspectrum.org/zxplus3e/technical.html[IDEDOS,role="external"],
http://www.worldofspectrum.org/residos/[ResiDOS,role="external"], and
http://esxdos.org[esxDOS,role="external"]. This will let Solo Forth
use hard drives, flash cards, and much more memory, beside many other
new features.

.Far future

Porting the G+DOS version of Solo Forth to http://worldofsam.org[SAM
Coupé,role="external"] (the powerful cousin of ZX Spectrum) would be
feasible...

// end::target[]

// tag::downloads[]

== Downloads

Solo Forth can be downloaded from two sites:

- http://programandala.net/en.program.solo_forth.html[Solo Forth home
  page]
- http://github.com/programandala-net/solo-forth[Solo Forth repository
  in GitHub,role="external"]

// end::downloads[]

// tag::tree[]

== Directory tree

....
.
├── backgrounds       Version background images
├── bin               Binary files needed to build disk 0
│   ├── fonts         Fonts for the supported screen modes
│   ├── addons        Code that is loaded from disk
│   │                 because it's not assembled in the library yet
│   └── sys           DOS files
├── disks             Disk images ready to use
│   ├── gplusdos      For G+DOS
│   ├── plus3dos      For +3DOS
│   └── trdos         For TR-DOS
├── doc               Documentation
├── make              Files used by `make` to build the system
├── screenshots       Version screenshots
├── src               Sources
│   ├── inc           Z80 symbols files
│   ├── lib           Library
│   ├── loader        BASIC loader for disk 0
│   ├── addons        Code that is loaded from disk
│   └── doc           Files used to build the documentation
├── tmp               Temporary files created by `make`
├── tools             Development and user tools
└── vim               Vim files
    ├── ftdetect      File type detection
    └── syntax        Syntax highlighting

....

// end::tree[]

== Documentation

A HTML manual is included in the <doc> directory.  It is automatically
built from the source files, which are fully documented, and from
secondary files as well, like this README file. The manual is a work
in progress. At the moment it contains the basic information and a
complete glossary with cross references.  A section to describe the
contents of the library modules is under development.

// tag::disks[]
== Disks

The <disks> directory of the <<_tree,directory_tree>> contains the
disk images:

....
disks/*/disk_0_boot.*
disks/*/disk_1_library.*
disks/*/disk_2_games.*
disks/*/disk_3_workbench.*
....

The subdirectory name and the filename extension depend on the DOS.

- Disk 0 is the boot disk. It contains the BASIC loader, the Solo
  Forth binary, some addons (i.e. compiled code that is not part of
  the library yet) and fonts for the supported screen modes. For
  +3DOS, two boot disk images are included, with different sizes.
- Disk 1 contains the sources of the library.
- Disk 2 contains some little sample games.
- Disk 3 contains tests and benchmarks used during the development.

WARNING: Disks 1, 2 and 3 are Forth blocks disks: They store the Forth
blocks directly on the disk sectors, without any file system.
Therefore they can not be used with DOS commands.

=== Notes on the disk images formats

.MGT

The MGT disk image file format (used for G+DOS disks) does not include
format-describing metadata: The MGT file is just a dump of the
original 800-KiB disk. Beside, G+DOS does not need its own metadata
(the directory tracks) be present in order to read or write sectors.

That's why converting Forth sources to MGT disk images is most simple,
and the full capacity of the disks can be used to store the Forth
blocks.

All this means the MGT disk images actually are identical to Forth
blocks files, as used by modern Forth systems.  Therefore, for
example, they can be browsed with a Forth blocks editor.

.TRD

Also the TRD disk images, one of the formats used for TR-DOS disk
images, are dumps of the original disks, without any format-describing
metadata. But, contrary to G+DOS, TR-DOS needs the system track (track
0) to contain certain data in order to recognize the disk, even for
sector-level access. That's why 636 KiB can be used for Forth blocks,
4 KiB (one track) less than then maximum capacity.

Anyway, TRD disk images can be browsed with a Forth blocks editor,
with the following restriction: blocks 0..3 will be shown as garbage
(they are track 0 of the disk), while the actual first Forth block of
the disk (block 0) will be shown as block 4.

.DSK

The DSK disk image format, used by +3DOS and other systems, is quite a
different thing: It contains a lot of metadata to describe the format
of the disk, the format tracks and the format of sectors...

// end::disks[]

// tag::run[]

[id=_run]
== How to run

=== On ZX Spectrum 128 with G+DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Plus D disk interface.
2. "Insert" the file <disks/gplusdos/disk_0_boot.mgt> as disk 1 of the
   Plus D disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `run` in BASIC. G+DOS will be loaded from disk, and Solo Forth
   as well.

=== On ZX Spectrum 128 with TR-DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Beta 128 disk interface.
2. "Insert" the file <disks/trdos/disk_0_boot.trd> as disk A of the
   Beta 128 disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `randomize usr 15616` in BASIC (or just `run usr15360` to save
   seven keystrokes). This will enter the TR-DOS command line, which
   uses keyboard tokens, like the ZX Spectrum 48footnote:[Only while
   the cursor is in 'K' mode; in 'L' mode keywords can be typed in
   full; unfortunately, the only way to get 'L' mode is the following:
   type some token first, e.g. `REM` (with the 'E' key), then type the
   DOS command in full, and finally delete the `REM` token from the
   start of the line.].
5. Type the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== On ZX Spectrum +3 or ZX Spectrum +3e

1. Run a ZX Spectrum emulator and select a ZX Spectrum +3 or
   http://www.worldofspectrum.org/zxplus3e/[ZX Spectrum
   +3e,role="external"].
2. "Insert" the file <disks/plus3dos/disk_0_boot.180.dsk> (or
   <disks/plus3dos/disk_0_boot.720.dsk>, depending on the capacity of
   the drive) as disk A of the ZX Spectrum +3(e).
3. Choose "Loader" from the ZX Spectrum +3(e) start menu. Solo Forth will
   be loaded from disk.

// end::run[]

// tag::library[]

[id=_library]
== The library

NOTE: At the moment, the library can not be used on +3DOS.

The library disk contains the source code in Forth blocks, written
directly on the disk sectors, without any filesystem.  In order to use
the library, follow these steps:

1. <<_run,Run Solo Forth>>.
2. Insert the library disk:
** In G+DOS: "Insert" the file <disks/gplusdos/disk_1_library.mgt> as
   disk 2 of the Plus D disk interface. Type `2 set-drive throw` to
   make drive 2 the current one.
** In TR-DOS: "Insert" the file <disks/trdos/disk_1_library.trd> as
   disk B of the Beta 128 disk interface. Type `1 set-drive throw` to
   make drive 1 (="B") the current one.
3. Type `1 load` to load block 1 from the library disk. By convention,
   block 1 is used as a loader.  In Solo Forth, block 1 contains just
   `2 load`, in order to load the `need` tool and related words from
   block 2.
4. Type `need name`, were "name" is the name of the word or tool you
   want to load from the library.

=== Library index

The `need` word and its related words search the index line (line 0)
of all blocks of the disk for the first occurence of the required
word, within a configurable range of blocks (using the variables
`first-locatable` and `last-locatable`).  Of course, nested `need` are
resolved the same way: searching the library from the beginning.  This
can be slow.  This is not a problem, because the goal of Solo Forth is
cross development, and therefore only the last step of the development
loop, i.e., the compilation of the sources from the disk images
created in the host system, compilation that includes all the slow
searching of library blocks, is done in the real (actually, emulated)
machine. But the system includes a tool to create an index of the
library, which is used to locate their contents instantaneously, what
makes things more comfortable when the Forth system is used
interactively.

How to use the library index:

1. Load the indexer with `need make-thru-index`.
2. Make the index and activate it with `make-thru-index`.
3. The default behaviour (no index) can be restored with
   `use-no-index`.  The index can be reactivated with
   `use-thru-index`.

The indexer creates an index (actually, a Forth word list whose
definitions use no code or data space) and changes the default
behaviour of `need` and related words to use it. Then `need name` will
automatically start loading the first block where the word "name" is
defined.

.Time and memory required to make the library index (in v0.12.0)
|===
| DOS     | First block | Last block | Seconds | Bytes of far memory

| G+DOS   |           5 |        799 |     154 |               13498
| TR-DOS  |           5 |        635 |     135 |               13027
|===

NOTE: The far memory is the virtual 64-KiB space formed by 4
configurable memory banks. No code or data space is used by the
indexer.

An alternative indexer is under development. It's activated with
`use-fly-index` and does not make and index in advance: Instead, it
indexes the blocks on the fly, when they are searched the first time.
This indexer was included in Solo Forth 0.12.0 but it's not finished
yet.

=== How to search the library from the host system

A simple wrapper script is provided to search the Forth sources (not
the Z80 kernel files) for a regular expression. It's used during the
development, but it can be useful for the user too.

Usage examples:

----
tools/search_library.sh make-thru-index
tools/search_library.sh make-thru-index -l
tools/search_library.sh color
tools/search_library.sh ":\scolor\s"
----

The script uses `ack`, but it can be replaced with the more common
`grep`. They are compatible.

// end::library[]

=== How to use the additional source disks

Section pending.

// tag::write[]

[id=_write]
== How to write Forth programs

In order to use Solo Forth to write programs for ZX Spectrum,
programmers already acquainted with Forth and GNU/Linux systems can
extract all the required information from the <Makefile> of Solo
Forth.

The only difference between <<__rebuild,building Solo Forth>> and
building a Forth program is the contents of disk 0 (the boot disk), if
needed, and the library modules included in disk 1 (the library disk),
which usually also contains the source of the program.  If the program
does not need to use the disk at run-time, you can simply copy the
default disk 0, and boot it to load your program from block 1 of your
customized disk 1, with a simple `1 load`. When the loading finishes,
you can save a snapshot with the ZX Spectrum emulator.

Some simple little games are provided as examples, in <<_disks,disk
3>>.  Some of them are not finished yet.

In order to try and fix the Forth system during its development, two
more complex game projects are being developed at the same time.  One
of them has been published:
http://programandala.net/en.program.black_flag.html[Black Flag]
(http://github.com/programandala-net/black-flag[Black Flag in
GitHub]).  It's not finished, but it can be useful as example of
development with Solo Forth.

// end::write[]

// tag::vim[]

[id=_vim]
== Vim support

In order to make Vim recognize and highlight the Solo Forth sources,
with the ".fsb" extension, copy the contents of the <./vim/> directory
to your home <~/.vim/> directory.

// end::vim[]

// tag::rebuild[]

[id=_rebuild]
== How to rebuild

If you modify the sources, you have to build new disk images for your
DOS of choice. Also the manual depends on the documentation included
in the sources.

First, see the requirements listed in the header of the <Makefile>
file and install the required programs. Then enter the project
directory and use one of the following commands to build the disk
images or the manual for your DOS of choice:

.Commands to rebuild Solo Forth
|===
| DOS          | Disk images                 | Documentation

| G+DOS        | `make gplusdos` or `make g` | `make gplusdosdoc` or `make gdoc`
| TR-DOS       | `make trdos` or `make t`    | `make trdosdoc` or `make tdoc`
| +3DOS        | `make plus3dos` or `make p` | `make plus3dosdoc` or `make pdoc`
| All of them  | `make all` or `make`        | `make doc`
|===

The disk images will be created in the <disks> directory. The HTML
manual will be created in the <doc> directory.

// end::rebuild[]

