= Solo Forth README
:author: Marcos Cruz (programandala.net)
:revdate: 2016-10-22

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

== Description

Solo Forth is a modern Forth system for ZX Spectrum 128 and later
models.

Solo Forth is focused on cross development of Forth programs for the
platform, using a ZX Spectrum emulator and all modern development
tools provided by the host OS.

Solo Forth could be used also to write Forth programs using its own
block editor, on a ZX Spectrum emulator or the real machine (provided
the disk images are converted to actual disks).  But it's not what
Solo Forth was developed for.

Home page: http://programandala.net/en.program.solo_forth.html

== History and current status

The
http://programandala.net/en.program.solo_forth.history.html[development
history] started on 2015-05-30.

As of 2016-10-22 Solo Forth is under active development. It's very
usable and stable on G+DOS, and it's already used to develop some
projects in Forth.

== Target platforms

=== ZX Spectrum 128 with G+DOS

Solo Forth was first intended for a ZX Spectrum 128 with G+DOS.  The
support for G+DOS is almost complete, both in the kernel and the
library.

=== ZX Spectrum 128 with TR-DOS

TR-DOS is supported but with some limitations, which will be solved:

- There are no words to use disk files yet.
- There's no way to change the current drive yet.  This means the
  library can be used only when the library disk is in drive A.

=== ZX Spectrum +3 with +3DOS

Support for +3DOS is still in a very initial stage.  The Forth system
boots, but there's no way to access the library disks yet, so in
practice it's useless.

=== Future target platforms

The DOS support in Solo Forth is modular, so in theory it would not be
difficult to add support for more advanced DOS, like IDEDOS, ResiDOS,
ESXDOS...

== How to run

=== ZX Spectrum 128 with G+DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Plus D disk interface.
2. "Insert" the file <disks/gplusdos/disk0.mgt> as disk 1 of the Plus D
   disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `run` in BASIC. G+DOS will be loaded from disk and Solo Forth
   will be autoloaded.

In order to use the library disk, follow these steps:

1. "Insert" the file <disks/gplusdos/disk1_lib.mgt> as disk 2 of the
   Plus D disk interface. This is the library disk; the source code is
   on its sectors, without any filesystem.
2. Type `2 load` in Forth. Block 2 will be loaded from disk 2. This
   will load `need` and related words.
3. Type `need name` in Forth, were "name" is the name of the word or
   tool you want to load from the library.

=== ZX Spectrum 128 with TR-DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Beta 128 disk interface.
2. "Insert" the file <disks/trdos/disk0.trd> as disk A of the Beta 128
   disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `randomize usr 15616` in BASIC. This will enter the TR-DOS
   command line, which uses tokens, like the ZX Spectrum 48.
5. Type the `R` key to get the `RUN` command and press the `Enter`
   key. This will autoload Solo Forth.

In order to use the library disk, follow these steps:

1. "Insert" the file <disks/trdos/disk1_lib.trd> as disk A of the
   Beta 128 disk interface. This is the library disk; the source code is
   on its sectors, without any filesystem.
2. Type `2 load` in Forth. Block 2 will be loaded from disk 2. This
   will load `need` and related words.
3. Type `need name` in Forth, were "name" is the name of the word or
   tool you want to load from the library.

=== ZX Spectrum +3 (or ZX Spectrum +3e)

1. Run a ZX Spectrum emulator and select a ZX Spectrum +3.
2. "Insert" the file <disks/plus3dos/disk0.180.dsk> as disk A of the
   ZX Spectrum +3.
3. Choose "Loader" from the ZX Spectrum +3 start menu. Solo Forth will
   be autoloaded.

There's no way to access the library disks yet, so the system is
almost useless on +3DOS.

== How to build

If you modify the kernel or the library, you need to build the system.

See the requirements listed in the header of the Makefile and install
the required programs. Then enter the project directory and use the
`make` command to build the disk images for every supported DOS.

Alternatively, you can build only the disk images of one DOS:

G+DOS::   `make gplusdos`
TR-DOS::  `make trdos`
+3DOS::   `make plus3dos`

== Git repository

The Git repository of Solo Forth was created from development backups
on 2016-03-12. Later commits are "real".
