= Solo Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2017-02-28
:toc:
:linkattrs:

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

// Last modified 201702272047

// tag::description[]

== Description

Solo Forth is a modern http://forth-standard.org[standard
Forth,role="external"] system under development for the ZX Spectrum
128 and compatible computers.

Solo Forth is focused on cross development of Forth programs for ZX
Spectrum 128 using a ZX Spectrum emulator on a GNU/Linux operating
system (in theory, other kind of operating system could be used as
well).

Solo Forth can be used also as a stand-alone Forth System on a ZX
Spectrum emulator or the real computer, but that's not its goal.

== Main features

- Fast Direct Threaded Code (DTC) implementation.
- A kernel as small as possible.
- Dictionary in banked memory, separated from code and data space.
- Transparent access to banked memory.
- Big <<_library,library>> of useful source code.
- Modular <<_computers,DOS support>>.
- Documented source code.
- Detailed documentation.

// end::description[]

// tag::history[]

== History and current status

The development started on 2015-05-30, from the
http://programandala.net/en.program.abersoft_forth[disassembled code
of Abersoft Forth], a tape-based fig-Forth 1.1 for ZX Spectrum 48.

As of 2017-02-18 Solo Forth is under active development. It's very
stable, and it's being used to develop a couple of projects in Forth.

// end::history[]

// tag::computers[]

[id=_computers]
== Supported computers and disk operating systems

Solo Forth needs a ZX Spectrum or compatible computer with disk drives
and at least 128 KiB of RAM.  Therefore it can not run on the original
ZX Spectrum 48, but in theory it could be used to develop Forth
programs that can run on it.

.Supported computers and disk operating systems
|===
| Computer        | Disk interface | DOS

.2+| ZX Spectrum 128
|                   Beta 128       | TR-DOS
|                   Plus D         | G+DOS

.2+| ZX Spectrum +2
|                   Beta 128       | TR-DOS
|                   Plus D         | G+DOS

| ZX Spectrum +3  |                | +3DOS
| ZX Spectrum +3e |                | +3DOS

| Pentagon 128    |                | TR-DOS
| Pentagon 512    |                | TR-DOS
| Pentagon 1024   |                | TR-DOS
| Scorpion ZS 256 |                | TR-DOS

|===

=== Status of the DOS support

==== G+DOS support

The G+DOS support is the most advanced. Only some file-management
words have to be fixed, improved or implemented yet.

==== TR-DOS support

The TR-DOS support is still basic. The blocks disks can be used, but
most file-management words are still under development.

==== +3DOS support

The +3DOS support is still in a very initial stage.  There's no way to
use the blocks disks or manipulate disk files yet, so in practice it's
useless.

// end::computers[]

// tag::tree[]

== Directory tree

....
.
├── backgrounds       Version background images
├── bin               Binary files needed to build disk 0
│   ├── fonts         Fonts for the supported screen modes
│   ├── addons        Code that is loaded from disk
│   │                 because it's not assembled in the library yet
│   └── sys           DOS files
├── disks             Disk images
│   ├── gplusdos      G+DOS disk images
│   ├── plus3dos      +3DOS disk images
│   └── trdos         TR-DOS disk images
├── doc               Documentation
├── make              Files used by `make` to build the system
├── screenshots       Version screenshots
├── src               Sources
│   ├── inc           Z80 symbols files
│   ├── lib           Library
│   ├── loader        BASIC loader for disk 0
│   ├── addons        Code that is loaded from disk
│   └── doc           Files used to build the documentation
├── tmp               Temporary files created by `make`
├── tools             Development and user tools
└── vim               Vim files
    ├── ftplugin      Filetype plugin
    └── syntax        Syntax highlighting
....

// end::tree[]

// tag::disks[]
== Disks

The <disks> directory of the <<_tree,directory tree>> contains the
disk images:

....
disks/*/disk_0_boot.*
disks/*/disk_1_library.*
disks/*/disk_2_games.*
disks/*/disk_3_workbench.*
....

The subdirectory name and the filename extension depend on the DOS.

- Disk 0 is the boot disk. It contains the BASIC loader, the Solo
  Forth binary, some addons (i.e. compiled code that is not part of
  the library yet) and fonts for the supported screen modes.  Two
  +3DOS boot disk images are included, with different sizes.  Several
  TR-DOS disk images are included, for specific models of Pentagon and
  Scorpion computers (in a future version, one single disk will
  contain all the executables, and the right one will be selected
  automatically).
- Disk 1 contains the sources of the library.
- Disk 2 contains some little sample games.
- Disk 3 contains tests and benchmarks used during the development.

WARNING: Disks 1, 2 and 3 are Forth blocks disks: They contain the
source Forth blocks directly on the disk sectors, without any file
system.  Therefore their contents can not be accessed with ordinary
DOS commands.

// end::disks[]

// tag::run[]

[id=_run]
== How to run

=== On ZX Spectrum 128 (or ZX Spectrum +2) with the Plus D interface

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 (or ZX
   Spectrum +2) with the Plus D disk interface.
2. "Insert" the disk image file <disks/gplusdos/disk_0_boot.mgt> as
   disk 1 of the Plus D disk interface.
3. Choose "128 BASIC" from the computer start menu.
4. Type `run` in BASIC. G+DOS will be loaded from disk, and Solo Forth
   as well.

=== On ZX Spectrum 128 (or ZX Spectrum +2) with the Beta 128 interface

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 (or ZX
   Spectrum +2) with the Beta 128 interface.
2. "Insert" the disk image file <disks/trdos/disk_0_boot.trd> as disk
   A of the Beta 128 interface.
3. Choose "128 BASIC" from the computer start menu.
4. Type `randomize usr 15616` in BASIC (or just `run usr15360` to save
   seven keystrokes). This will enter the TR-DOS command
   linefootnoteref:[trdoscli,The TR-DOS command line uses keyboard
   tokens, like the ZX Spectrum 48, but commands typed in 'L' cursor
   mode will be recognized as well, as on the ZX Spectrum 128 editor.
   Unfortunately, the only way to get 'L' cursor mode is typing a
   token first, e.g. `REM` (pressing the 'E' key). Then the DOS
   command can be typed in full after `REM`, which must be removed
   from the start of the line before pressing the Enter key.].
5. Press the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== On ZX Spectrum +3 (or ZX Spectrum +3e)

// XXX REMARK -- A problem with Asciidoctor makes the rendering of the
// ZX Spectrum +3e link text fail. It seems the error condition has to
// do with a combination of "+" be at start of a new line, and the
// presence of the link attribute. The result is the "+3e" part is
// omited. Using `{sp}` to prevent the text from being splitted fixes
// the problem.

1. Run a ZX Spectrum emulator and select a ZX Spectrum +3 (or
   http://www.worldofspectrum.org/zxplus3e/[ZX
   Spectrum{sp}+3e,role="external"]).
2. "Insert" the disk image file <disks/plus3dos/disk_0_boot.180.dsk>
   (or <disks/plus3dos/disk_0_boot.720.dsk>, depending on the capacity
   of the drive) as disk 'A'.
3. Choose "Loader" from the computer start menu. Solo Forth will be
   loaded from disk.

=== On Pentagon 128

1. Run a ZX Spectrum emulator and select a Pentagon 128.
2. "Insert" the disk image file <disks/trdos/disk_0_boot.trd> as disk
   'A'.
3. Choose "TR DOS" from the computer start menu. This will enter the
   TR-DOS command linefootnoteref:[trdoscli].
4. Press the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== On Pentagon 512

1. Run a ZX Spectrum emulator and select a Pentagon 512.
2. "Insert" the disk image file
   <disks/trdos/disk_0_boot.pentagon_512.trd> as disk 'A'.
3. Choose "128k menu"footnoteref:[pentagonboot,In theory, choosing
   option "TR-DOS" from the system service menu should work. But it
   seems it depends on a specific version of TR-DOS.  This alternative
   method is longer, but it works with the TR-DOS 5.03 ROM. It will be
   improved in future versions of the manual.] from the computer start
   menu (the reset service menu). This will enter a ZX Spectrum 128
   style menu. Choose "TR-DOS".  This will enter the TR-DOS command
   linefootnoteref:[trdoscli].
4. Press the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== On Pentagon 1024

1. Run a ZX Spectrum emulator and select a Pentagon 512.
2. "Insert" the disk image file
   <disks/trdos/disk_0_boot.pentagon_512.trd> as disk 'A'.
3. Choose "128k menu"footnoteref:[pentagonboot] from the computer
   start menu (the reset service menu). This will enter a ZX Spectrum
   128 style menu. Choose "TR-DOS".  This will enter the TR-DOS
   command linefootnoteref:[trdoscli].
4. Press the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== On Scorpion ZS 256

1. Run a ZX Spectrum emulator and select a Scorpion ZS 256.
2. "Insert" the disk image file
   <disks/trdos/disk_0_boot.scorpion_zs_256.trd> as disk 'A'.
3. Choose "128 TR DOS" from the computer start menu.  Solo Forth will
   be loaded from disk.

// end::run[]

// tag::library[]

[id=_library]
== The library

NOTE: At the moment, the library can not be used on +3DOS.

The library disk contains the source code in Forth blocks, written
directly on the disk sectors, without any filesystem.  In order to use
the library, follow these steps:

1. <<_run,Run Solo Forth>>.
2. Insert the library disk:
** On G+DOS: "Insert" the file <disks/gplusdos/disk_1_library.mgt> as
   disk 2 of the Plus D disk interface. Type `2 set-drive throw` to
   make drive 2 the current one.
** On TR-DOS: "Insert" the file <disks/trdos/disk_1_library.trd> as
   disk B of the Beta 128 interface. Type `1 set-drive throw` to make
   drive 1footnote:[The TR-DOS BASIC interface uses letters 'A'..'D'
   to identify the disk drives, in commands and filenames. But, under
   the hood, TR-DOS uses numbers 0..3 to identify the disk drives, and
   filenames don't include the drive letter. This is the way Solo
   Forth works too. Usage of `A`..`D` instead of 0..3 maybe
   implemented in a future version of Solo Forth, either by default or
   as an option.] the current one.
3. Type `1 load` to load block 1 from the library disk. By convention,
   block 0 can not be loaded (it is used for comments), and block 1 is
   used as a loader.  In Solo Forth, block 1 contains `2 load`, in
   order to load the `need` tool and related words from block 2.
4. Type `need name`, were "name" is the name of the word or tool you
   want to load from the library.

// end::library[]

== Documentation

A HTML manual is included in the <doc> directory.  It is automatically
built from the source files, which are fully documented, and from
secondary files as well, like this README file, which in fact is an
extract from the manual.

The manual is a work in progress. At the moment it contains the basic
information and a complete glossary with cross references.  A section
to describe the contents of the library modules is under development.

