= Solo Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2017-02-09
:toc:
:linkattrs:

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

== Description

Solo Forth is a modern http://forth-standard.org[standard
Forth,role="external"] system under development for the ZX Spectrum
128 computer and later models.

Solo Forth is focused on cross development of Forth programs for this
platform, using a ZX Spectrum emulator and all modern development
tools provided by a Linux-like OS.

Solo Forth can be used also as a stand-alone Forth System on a ZX
Spectrum emulator or the real computer.  But that's not what Solo
Forth was developed for.

Home page: http://programandala.net/en.program.solo_forth.html

[role="external"]
Git repository: http://github.com/programandala-net/solo-forth

== History and current status

The developmente started on 2015-05-30.

As of 2017-02-07 Solo Forth is under active development. It's very
stable, and it's already used to develop some projects in Forth.

The changes of the latest version are listed in VERSIONS.adoc.

== Target platforms

Solo Forth needs a ZX Spectrum with 128 KiB of RAM and disk drives.
Therefore it can not run on a ZX Spectrum 48, but it can be used to
create programs for a ZX Spectrum 48.

=== ZX Spectrum 128 with G+DOS

Solo Forth was first intended for a ZX Spectrum 128 with G+DOS
(provided by the Plus D interface).  The support for G+DOS is almost
complete.

=== ZX Spectrum 128 with TR-DOS

TR-DOS (provided by the Beta 128 Disk interface) is supported. It can
be used to load blocks from the library, but no word to access disk
files is provided yet.

=== ZX Spectrum +3 and ZX Spectrum +3e

Support for +3DOS is still in a very initial stage.  The Forth system
boots, but there's no way to access the library disks yet, so in
practice it's useless.

=== Other

The DOS support in Solo Forth is modular, so in theory it will not be
difficult to support also more powerful DOSs in future versions, like
http://www.worldofspectrum.org/zxplus3e/technical.html[IDEDOS,role="external"],
http://www.worldofspectrum.org/residos/[ResiDOS,role="external"], and
http://esxdos.org[esxDOS,role="external"]. This will let Solo Forth use hard drives,
flash cards, and much more memory, beside many other new features.

== Directories

....
.
├── backgrounds       Version background images
├── bin               Binary files needed to build disk 0
│   ├── fonts         Fonts for the supported screen modes
│   ├── addons        Code that is loaded from disk
│   │                 because it's not assembled in the library yet
│   └── sys           DOS files
├── disks             Disk images ready to use
│   ├── gplusdos      For G+DOS
│   ├── plus3dos      For +3DOS
│   └── trdos         For TR-DOS
├── doc               Some initial documentation
├── make              Files used by `make` to build the system
├── screenshots       Version screenshots
├── src               Sources
│   ├── inc           Z80 symbols files
│   ├── lib           Library
│   ├── loader        BASIC loader for disk 0
│   └── addons        Code that is loaded from disk
│                     because it's not integrated in the library yet
├── tmp               Temporary files created by `make`
├── tools             Development and user tools
└── vim               Vim files
    ├── ftdetect      File type detection
    └── syntax        Syntax highlighting

....

== How to run

=== On ZX Spectrum 128 with G+DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Plus D disk interface.
2. "Insert" the file <disks/gplusdos/disk0_boot.mgt> as disk 1 of the
   Plus D disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `run` in BASIC. G+DOS will be loaded from disk, and Solo Forth
   as well.

=== On ZX Spectrum 128 with TR-DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Beta 128 disk interface.
2. "Insert" the file <disks/trdos/disk0_boot.trd> as disk A of the
   Beta 128 disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `print usr 15616` in BASIC. This will enter the TR-DOS command
   line, which uses keyboard tokens, like the ZX Spectrum 48.
5. Type the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== On ZX Spectrum +3 or ZX Spectrum +3e

1. Run a ZX Spectrum emulator and select a ZX Spectrum +3 or
   http://www.worldofspectrum.org/zxplus3e/[ZX Spectrum
   +3e,role="external"].
2. "Insert" the file <disks/plus3dos/disk0_boot.180.dsk> as disk A of
   the ZX Spectrum +3.
3. Choose "Loader" from the ZX Spectrum +3 start menu. Solo Forth will
   be loaded from disk.

== How to use the Forth source disks

NOTE: At the moment, the Forth source disks can not be used on +3DOS.

=== How to use the library

The library disk contains the source code in Forth blocks, written
directly on the disk sectors, without any filesystem.  In order to use
the library, follow these steps:

1. <<_how_to_run,Run Solo Forth>>.
2. Insert the library disk:
** In G+DOS: "Insert" the file <disks/gplusdos/disk1_library.mgt> as
   disk 2 of the Plus D disk interface. Type `2 set-drive throw` to
   make drive 2 the current one.
** In TR-DOS: "Insert" the file <disks/trdos/disk1_library.trd> as
   disk B of the Beta 128 disk interface. Type `1 set-drive throw` to
   make drive 1 (="B") the current one.
3. Type `1 load` to load block 1 from the library disk. By convention,
   block 1 is used as a loader.  In Solo Forth, block 1 contains just
   `2 load`, in order to load the `need` tool and related words from
   block 2.
4. Type `need name`, were "name" is the name of the word or tool you
   want to load from the library.

=== How to use the additional source disks

Section pending.

=== Library index

`need` and family search the index line (line 0) of all blocks of the
disk for the first occurence of the required word, within a
configurable range of blocks (using the variables `first-locatable`
and `last-locatable`).  Of course, nested `need` are resolved the same
way: searching the library from the beginning.  This can be slow.
This is not a problem, because the goal of Solo Forth is cross
development, and therefore only the last step of the development loop,
i.e., the compilation of the sources from the disk images created in
the host system, compilation that includes all the slow searching of
library blocks, is done in the real (actually, emulated) machine. But
the system includes a tool to create an index of the library, which is
used to locate their contents instantaneously, what makes things more
comfortable when the Forth system is used interactively.

How to use the library index:

1. Load the indexer with `need make-thru-index`.
2. Make the index and activate it with `make-thru-index`.
3. The default behaviour (no index) can be restored with
   `use-no-index`.  The index can be reactivated with
   `use-thru-index`.

The indexer creates an index (actually, a Forth word list whose
definitions use no code or data space) and changes the default
behaviour of `need` and related words to use it. Then `need name` will
automatically start loading the first block where the word "name" is
defined.

[caption="Time and memory required to make the library index (in v0.12.0)"]
|===
| DOS     | First block | Last block | Seconds | Bytes of far memory

| G+DOS   |           5 |        799 |     154 |               13498
| TR-DOS  |           5 |        635 |     135 |               13027
|===

NOTE: The far memory is the virtual 64-KiB space formed by 4
configurable memory banks. No code or data space is used by the
indexer.

An alternative indexer is under development. It's activated with
`use-fly-index` and does not make and index in advance: Instead, it
indexes the blocks on the fly, when they are searched the first time.
This indexer was included in Solo Forth 0.12.0 but it's not finished
yet.

== Documentation

At the moment, the only documentation is this README file, the
sources, and a file in the <doc/> directory that explains the stack
notation.

Most words are fully documented in the kernel and the library source
files, and those comments are marked in order to extract them from the
sources and build a fully organized and indexed glossary in
http://asciidoctor.org[Asciidoctor,role="external"] format, that will
be automatically converted to HTML, EPUB and other formats.

The tool that will build the documentation is under development,
written in Forth with
http://gnu.org/software/gforth[Gforth,role="external"], and it will be
included in a future version of Solo Forth.

=== How to search the Forth sources

A simple wrapper script is provided to search the Forth sources (not
the Z80 kernel files) for a regular expression. It's used during the
development, but it can be useful for the user too.

Usage examples:

----
tools/search_library.sh make-thru-index
tools/search_library.sh make-thru-index -l
tools/search_library.sh color
tools/search_library.sh ":\scolor\s"
----

The script uses `ack`, but it can be replaced with the more common
`grep`. They are compatible.

== How to write Forth programs

In order to use Solo Forth to write programs for ZX Spectrum,
programmers already acquainted with Forth and Linux systems can
extract all the required information from the <Makefile> of Solo
Forth.

The only difference between building Solo Forth and building a Forth
program is the additional files added to disk image 0 (the boot disk),
if needed, and the library modules included in disk image 1 (the
library disk), which also contains the source of the program.  If
the program does not need to use the disk at run-time, you can
simply copy the default disk 0, and boot it to load your program
from block 1 of your customized disk 1, with a simple `1 load`. When
the loading finishes, you can save a snapshot with the ZX Spectrum
emulator.

Some simple little games are provided as examples, in their own disk.
Some of them are not finished yet.

In order to try and fix the Forth system during its development, two
more complex game projects are being developed at the same time. They
will be published soon in a public Git repository. They will be useful
as examples.

=== Vim support

In order to make Vim recognize and highlight the Solo Forth sources,
with the ".fsb" extension, copy the contents of the <./vim/> directory
to your home <~/.vim/> directory.

== How to build

If you modify the sources, you have to build new disk images for your
DOS of choice.

First, see the requirements listed in the header of the <Makefile>
file and install the required programs. Then enter the project
directory and use one of the following commands to build the disk
images for your DOS of choice:

|===
| DOS          | Command

| G+DOS        | `make gplusdos` or simply `make g`
| TR-DOS       | `make trdos` or simply `make t`
| +3DOS        | `make plus3dos` or simply `make p`
| All of them  | `make all` or simply `make`.
|===

The correspondent disk images will be created in the <disks>
directory.

