= Solo Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2018-03-11
:toc:
:linkattrs:

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

// tag::description[]

== Description

Solo Forth is a modern http://forth-standard.org[standard
Forth,role="external"] system under development for the ZX Spectrum
128 and compatible computers.

Solo Forth is focused on cross development of Forth programs for ZX
Spectrum 128 using a ZX Spectrum emulator on a GNU/Linux operating
system (in theory, other kind of operating system could be used as
well).

Solo Forth is a complete Forth system. Therefore it can be used as a
stand-alone Forth system on a ZX Spectrum emulator or the real
computer, without any limitation, but that's not its goal. Its goal is
to be used as the last step of the development process, i.e. to
compile and debug a Forth program on a ZX Spectrum emulator. The
sources of the Forth program are edited on the host operating system
and converted to Forth block disk images by tools that run on the host
operating system.

== Main features

- Fast DTC (Direct Threaded Code) implementation.
- A kernel as small as possible.
- Dictionary in banked memory, separated from code and data space.
- Transparent access to banked memory.
- Big <<_library,library>> of useful source code.
- Modular <<_computers,DOS support>>.
- Documented source code.
- Detailed documentation.

// end::description[]

// tag::name[]

// == Name

// XXX TODO --

// end::name[]

// tag::history[]

== History and current status

The development of Solo Forth started on 2015-05-30, from the
http://programandala.net/en.program.abersoft_forth.html[disassembled
code of Abersoft Forth], a tape-based fig-Forth 1.1 for ZX Spectrum
48.

The http://github.com/programandala-net/solo-forth[GitHub
repository,role="external"] was created on 2016-03-13 from the
development backups, in order to preserve the change history from the
very beginning.  Besides, there's a
http://programandala.net/en.program.solo_forth.history.html[development
history until v0.12.0 (2016-12-31)].

At the time of writing, Solo Forth is under active development. It's
very stable, and it's being used to develop two projects in Forth:
http://programandala.net/en.program.nuclear_waste_invaders.html[Nuclear
Waste Invaders] and
http://programandala.net/en.program.black_flag.html[Black Flag].

// end::history[]

// tag::computers[]

[id=_computers]
== Supported computers and disk operating systems

Solo Forth needs a ZX Spectrum 128 or compatible computer with at
least one disk drive.  It can not run on the original ZX Spectrum 48,
but it could be used to develop Forth programs for it.

.Supported computers and disk operating systems
|===
| Computer        | Disk interface        | DOS

| Pentagon 128    |                       | TR-DOS
| Pentagon 512    |                       | TR-DOS
| Pentagon 1024   |                       | TR-DOS
| Scorpion ZS 256 |                       | TR-DOS
| ZX Spectrum 128 | Beta 128              | TR-DOS
| ZX Spectrum 128 | Plus D                | G+DOS
| ZX Spectrum +2  | Beta 128              | TR-DOS
| ZX Spectrum +2  | Plus D                | G+DOS
| ZX Spectrum +2A | (External disk drive) | +3DOS
| ZX Spectrum +2B | (External disk drive) | +3DOS
| ZX Spectrum +3  |                       | +3DOS
| ZX Spectrum +3e |                       | +3DOS
|===

// end::computers[]

=== Future targets

The DOS support in Solo Forth is modular, so in theory it would not be
too difficult to support also other DOS in future versions. There are
some ideas:

Porting the G+DOS version of Solo Forth to its close relatives GDOS,
Beta DOS and Uni-DOS will require only minor changes, beside adding
some library code to benefit from their specific features.

Supporting a more powerful and modern DOS like
http://www.worldofspectrum.org/zxplus3e/technical.html[IDEDOS,role="external"],
http://www.worldofspectrum.org/residos/[ResiDOS,role="external"], and
http://esxdos.org[esxDOS,role="external"] would require more effort,
but would let Solo Forth use hard drives, flash cards, and a lot of
memory, beside many other new features.

Porting the G+DOS version of Solo Forth to http://worldofsam.org[SAM
Coupé,role="external"] (the powerful quite compatible cousin of ZX
Spectrum) would not be a trivial task, because of the quite different
OS and memory bank switching, but feasible.

At the time of writing the only planned port is for
http://specnext.com[ZX Spectrum Next].

=== Summary of the DOS support

==== G+DOS

// tag::gplusdos_support_summary[]

Block disks are fully supported, but some file-management words are
not implemented yet, especially the standard Forth words.

// end::gplusdos_support_summary[]

==== TR-DOS

// tag::trdos_support_summary[]

Block disks are fully supported, but many file-management words are
not implemented yet, especially the standard Forth words.

NOTE: Only double-sided 80-track disks (i.e. 640 KiB) are supported
for Forth blocks. Other formats can be used for files.

// end::trdos_support_summary[]

==== +3DOS

// tag::plus3dos_support_summary[]

Block disks are fully supported, but most file-management words are
not implemented yet, though standard Forth words are better supported
than on G+DOS or TR-DOS.

NOTE: Only double-sided 80-track disks (i.e. 780 KiB) are supported.

// end::plus3dos_support_summary[]

// tag::tree[]

[id=_tree]
== Project directories

// XXX FIXME -- This tree was created by `tree`. The UTF-8 graphic
// characters are ruined  by `htmldoc` in the PDF.

// ....
// .
// ├── backgrounds       Version background images
// ├── bin               Binary files needed to build disk 0
// │   ├── fonts         Fonts for the supported screen modes
// │   ├── addons        Code that is loaded from disk
// │   │                 because it's not assembled in the library yet
// │   └── dos           DOS files
// ├── disks             Disk images
// │   ├── gplusdos      G+DOS disk images
// │   ├── plus3dos      +3DOS disk images
// │   └── trdos         TR-DOS disk images
// ├── doc               Documentation
// ├── make              Files used by `make` to build the system
// ├── screenshots       Version screenshots
// ├── src               Sources
// │   ├── inc           Z80 symbols files
// │   ├── lib           Library
// │   ├── loader        BASIC loader for disk 0
// │   ├── addons        Code that is loaded from disk
// │   └── doc           Files used to build the documentation
// ├── tmp               Temporary files created by `make`
// ├── tools             Development and user tools
// └── vim               Vim files
//     ├── ftplugin      Filetype plugin
//     └── syntax        Syntax highlighting
// ....

// XXX OLD -- A table version is not legible enough.

// |===
// | Directory      | Description

// | backgrounds    | Version background images
// | bin            | Binary files needed to build disk 0
// | bin/addons     | Code loaded from disk, not assembled in the library yet
// | bin/dos        | DOS files
// | bin/fonts      | Fonts for the supported screen modes
// | disks          | Disk images
// | disks/gplusdos | G+DOS disk images
// | disks/plus3dos | +3DOS disk images
// | disks/trdos    | TR-DOS disk images
// | doc            | Documentation
// | make           | Files used by `make` to build the system
// | screenshots    | Version screenshots
// | src            | Sources
// | src/addons     | Code that is loaded from disk
// | src/doc        | Files used to build the documentation
// | src/inc        | Z80 symbols
// | src/lib        | Library
// | src/loader     | BASIC loader for disk 0
// | tmp            | Temporary files created by `make`
// | tools          | Development and user tools
// | vim            | Vim files
// | vim/ftplugin   | Filetype plugin
// | vim/syntax     | Syntax highlighting
// |===

* *backgrounds* :  Version background images
* *bin* : Binary files needed to build disk 0
  - *addons* : Code loaded from disk, not assembled in the library yet
  - *dos* : DOS files
  - *fonts* : Fonts for the supported screen modes
* *disks* : Disk images
  - *gplusdos* : G+DOS disk images
  - *plus3dos* : +3DOS disk images
  - *trdos* : TR-DOS disk images
* *doc* : Documentation
* *make* : Files used by `make` to build the system
* *screenshots* : Version screenshots
* *src* : Sources
  - *addons* : Code that is loaded from disk
  - *doc* : Files used to build the documentation
  - *inc* : Z80 symbols
  - *lib* : Library
  - *loader* : BASIC loader for disk 0
* *tmp* : Temporary files created by `make`
* *tools* : Development and user tools
* *vim* : Vim files
  - *ftplugin* : Filetype plugin
  - *syntax* : Syntax highlighting

// end::tree[]

// tag::disks[]
== Disks

The <disks> directory of the <<_tree,directory tree>> contains the
disk images:

....
disks/*/disk_0_boot.*
disks/*/disk_1_library.*
disks/*/disk_2_programs.*
disks/*/disk_3_workbench.*
....

The subdirectory and the filename extension depend on the DOS, as
follows:

|===
| DOS    | Subdirectory | Filename extension

| G+DOS  | gplusdos     | mgt
| TR-DOS | trdos        | trd
| +3DOS  | plus3dos     | dsk
|===


- Disk 0 is the boot disk. It contains the BASIC loader, the Solo
  Forth binary, some addons (i.e. compiled code that is not part of
  the library yet) and fonts for the supported screen modes.  Several
  TR-DOS disk images are included, for specific models of Pentagon and
  Scorpion computers (in a future version, one single disk will
  contain all the executables, and the right one will be selected
  automatically).
- Disk 1 contains the library.
- Disk 2 contains some little sample games, most of them under
  development, and two block editors.
- Disk 3 contains tests and benchmarks. Most of them were used during
  the development and their only documentation is the commented
  source.

WARNING: Disks 1, 2 and 3 are Forth block disks: They contain the
source Forth blocks directly on the disk sectors, without any file
system.  Therefore their contents can not be accessed with ordinary
DOS commands.

// end::disks[]

// tag::run[]

[id=_run]
== How to run

=== Pentagon 128

1. Run a ZX Spectrum emulator and select a Pentagon 128.  Make sure
   the disk drives configuration is double-sided 80-track disks.
2. "Insert" the disk image file <disks/trdos/disk_0_boot.trd> as disk
   'A'.
3. Choose "TR DOS" from the computer start menu. This will enter the
   TR-DOS command linefootnoteref:[trdoscli].
4. Press the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== Pentagon 512

1. Run a ZX Spectrum emulator and select a Pentagon 512.  Make sure
   the disk drives configuration is double-sided 80-track disks.
2. "Insert" the disk image file
   <disks/trdos/disk_0_boot.pentagon_512.trd> as disk 'A'.
3. Choose "128k menu"footnoteref:[pentagonboot,In theory, choosing
   option "TR-DOS" from the system service menu should work. But it
   seems it depends on a specific version of TR-DOS.  This alternative
   method is longer, but it works with the TR-DOS 5.03 ROM. It will be
   improved in future versions of the manual.] from the computer start
   menu (the reset service menu). This will enter a ZX Spectrum 128
   style menu. Choose "TR-DOS".  This will enter the TR-DOS command
   linefootnoteref:[trdoscli].
4. Press the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== Pentagon 1024

1. Run a ZX Spectrum emulator and select a Pentagon 1024.  Make sure
   the disk drives configuration is double-sided 80-track disks.
2. "Insert" the disk image file
   <disks/trdos/disk_0_boot.pentagon_1024.trd> as disk 'A'.
3. Choose "128k menu"footnoteref:[pentagonboot] from the computer
   start menu (the reset service menu). This will enter a ZX Spectrum
   128 style menu. Choose "TR-DOS".  This will enter the TR-DOS
   command linefootnoteref:[trdoscli].
4. Press the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== Scorpion ZS 256

1. Run a ZX Spectrum emulator and select a Scorpion ZS 256.  Make sure
   the disk drives configuration is double-sided 80-track disks.
2. "Insert" the disk image file
   <disks/trdos/disk_0_boot.scorpion_zs_256.trd> as disk 'A'.
3. Choose "128 TR DOS" from the computer start menu.  Solo Forth will
   be loaded from disk.

=== ZX Spectrum 128/+2 with the Plus D interface

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 (or ZX
   Spectrum +2) with the Plus D disk interface.
2. "Insert" the disk image file <disks/gplusdos/disk_0_boot.mgt> as
   disk 1 of the Plus D disk interface.
3. Choose "128 BASIC" from the computer start menu.
4. Type `run` in BASIC. G+DOS will be loaded from disk, and Solo Forth
   as well.

=== ZX Spectrum 128/+2 with the Beta 128 interface

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 (or ZX
   Spectrum +2) with the Beta 128 interface.  Make sure the disk
   drives configuration is double-sided 80-track disks.
2. "Insert" the disk image file <disks/trdos/disk_0_boot.trd> as disk
   A of the Beta 128 interface.
3. Choose "128 BASIC" from the computer start menu.
4. Type `randomize usr 15616` in BASIC (or just `run usr15360` to save
   seven keystrokes). This will enter the TR-DOS command
   linefootnoteref:[trdoscli,The TR-DOS command line uses keyboard
   tokens, like the ZX Spectrum 48, but commands typed in 'L' cursor
   mode will be recognized as well, as on the ZX Spectrum 128 editor.
   In order to get the 'L' cursor mode you can type a quote (Symbol
   Shift + 'P') or press 'E' to get keyword `REM`. When the DOS
   command is typed in full, the quote or the `REM` must be removed
   from the start of the line before pressing 'Enter'.].
5. Press the `R` key to get the `RUN` command and press the Enter key.
   Solo Forth will be loaded from disk.

=== ZX Spectrum +3/+3e

// XXX REMARK -- A problem with Asciidoctor makes the rendering of the
// ZX Spectrum +3e link text fail. It seems the error condition has to
// do with a combination of "+" be at start of a new line, and the
// presence of the link attribute. The result is the "+3e" part is
// omited. Using `{sp}` to prevent the text from being splitted fixes
// the problem.

1. Run a ZX Spectrum emulator and select a ZX Spectrum +3 (or
   http://www.worldofspectrum.org/zxplus3e/[ZX
   Spectrum{sp}+3e,role="external"]).  Make sure the disk drives
   configuration is double-sided 80-track disks.
2. "Insert" the disk image file <disks/plus3dos/disk_0_boot.180.dsk>
   (or <disks/plus3dos/disk_0_boot.720.dsk>, depending on the capacity
   of the drive) as disk 'A'.
3. Choose "Loader" from the computer start menu. Solo Forth will be
   loaded from disk.

// end::run[]

// tag::library[]

[id=_library]
== The library

The library disk contains the source code in Forth blocks, written
directly on the disk sectors, without any filesystem.  In order to use
the library, follow these steps:

1. <<_run,Run Solo Forth>>.
2. Insert the library disk:
** On G+DOS: "Insert" the file <disks/gplusdos/disk_1_library.mgt> as
   disk 2 of the Plus D disk interface. Type `2 set-drive throw` to
   make drive 2 the current one.
** On TR-DOS: "Insert" the file <disks/trdos/disk_1_library.trd> as
   disk B of the Beta 128 interface. Type `1 set-drive throw` to make
   drive 1footnote:[The TR-DOS BASIC interface uses letters 'A'..'D'
   to identify the disk drives, in commands and filenames. But, under
   the hood, TR-DOS uses numbers 0..3 to identify the disk drives, and
   filenames don't include the drive letter. This is the way Solo
   Forth works too. Usage of `A`..`D` instead of 0..3 maybe
   implemented in a future version of Solo Forth, either by default or
   as an option.] the current one.
** On +3DOS: "Insert" the file <disks/plus3dos/disk_1_library.dsk> as
   disk A.
3. Type `1 load` to load block 1 from the library disk. By convention,
   block 0 can not be loaded (it is used for comments), and block 1 is
   used as a loader.  In Solo Forth, block 1 contains `2 load`, in
   order to load the `need` tool and related words from block 2.
4. Type `need name`, were "name" is the name of the word or tool you
   want to load from the library.

// end::library[]

== Documentation

An HTML manual is included in the <doc> directory (actually, there are
three versions of the manual, one for each supported DOS, but at the
moment the only difference is the glossary).  The manual is
automatically built from the source files, which are almost fully
documented, and from secondary files as well, like this README file,
which in fact is an extract from the manual.

The manual is a work in progress. At the moment it contains only the
basic information required to use the Forth system and an almost
complete glossary with cross references.

The following sections are planned for a future version:

- A reference guide by subject, e.g. graphics, sound, blocks, files,
  control flow structures, etc.
- A description of the library modules.

Beside, in a next version of the manual, all Forth words will be links
to the glossary entries. At the moment, only Forth words mentioned in
the glossary are cross references.

NOTE: Glossary cross references to Forth words that contain a
backslash, or that are included in code examples, are corrupted. This
problem will be fixed in a future version.
