= Solo Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2016-12-31
:toc:

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

== Description

Solo Forth is a modern http://forth-standard.org[standard Forth]
system under development for the ZX Spectrum 128 computer and later
models.

Solo Forth is focused on cross development of Forth programs for this
platform, using a ZX Spectrum emulator and all modern development
tools provided by a Linux-like OS.

Solo Forth can be used also as a stand-alone Forth System on a ZX
Spectrum emulator or the real computer.  But that's not what Solo
Forth was developed for.

Home page: http://programandala.net/en.program.solo_forth.html

Git repository: http://github.com/programandala-net/solo-forth

== History and current status

The
http://programandala.net/en.program.solo_forth.history.html[development
history] started on 2015-05-30.

As of 2016-12-31 Solo Forth is under active development. It's very
stable, and it's already used to develop some projects in Forth.

== Target platforms

Solo Forth needs a ZX Spectrum with 128 KiB of RAM and disk drives.
Therefore it can not run on a ZX Spectrum 48, but it can be used to
create programs for a ZX Spectrum 48.

=== ZX Spectrum 128 with G+DOS

Solo Forth was first intended for a ZX Spectrum 128 with G+DOS
(provided by the Plus D interface).  The support for G+DOS is almost
complete, both in the kernel and the library.

=== ZX Spectrum 128 with TR-DOS

TR-DOS (provided by the Beta 128 Disk interface) is supported but with
some limitations, which will be solved in a future version of Solo
Forth:

- There are no words to use disk files yet.
- There's no way to change the current drive yet.  This means the
  library can be used only when the library disk is in drive A.

=== ZX Spectrum +3 and ZX Spectrum +3e

Support for +3DOS is still in a very initial stage.  The Forth system
boots, but there's no way to access the library disks yet, so in
practice it's useless.

=== Other

The DOS support in Solo Forth is modular, so in theory it would not be
difficult to add support for more powerful DOSs in future versions,
like IDEDOS, ResiDOS and ESXDOS.

== Directories

....
.
├── backgrounds       background images
├── bin               binary files needed to build disk 0
│   ├── fonts         fonts for the supported screen modes
│   ├── modules       special modules, not integrated in the library yet
│   └── sys           DOSs
├── disks             disk images ready to use
│   ├── gplusdos      for G+DOS
│   ├── plus3dos      for +3DOS
│   └── trdos         for TR-DOS
├── doc               some initial documentation
├── make              files used by make to build the system
├── src               sources
│   ├── inc           included Z80 symbols
│   ├── lib           library
│   ├── loader        BASIC loader for disk 0
│   └── modules       special modules, not integrated in the library yet
├── tmp               temporary files used by make during the building
├── tools             development and user tools
└── vim               Vim files
    ├── ftdetect      file type detection
    └── syntax        syntax highlighting

....

== How to run

=== ZX Spectrum 128 with G+DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Plus D disk interface.
2. "Insert" the file <disks/gplusdos/disk0.mgt> as disk 1 of the Plus D
   disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `run` in BASIC. G+DOS will be loaded from disk and Solo Forth
   will be autoloaded.

=== ZX Spectrum 128 with TR-DOS

1. Run a ZX Spectrum emulator and select a ZX Spectrum 128 with the
   Beta 128 disk interface.
2. "Insert" the file <disks/trdos/disk0.trd> as disk A of the Beta 128
   disk interface.
3. Choose "128 BASIC" from the ZX Spectrum start menu.
4. Type `randomize usr 15616` in BASIC. This will enter the TR-DOS
   command line, which uses tokens, like the ZX Spectrum 48.
5. Type the `R` key to get the `RUN` command and press the `Enter`
   key. This will autoload Solo Forth.

=== ZX Spectrum +3 and ZX Spectrum +3e

1. Run a ZX Spectrum emulator and select a ZX Spectrum +3 or
   http://www.worldofspectrum.org/zxplus3e/[ZX Spectrum +3e].
2. "Insert" the file <disks/plus3dos/disk0.180.dsk> as disk A of the
   ZX Spectrum +3.
3. Choose "Loader" from the ZX Spectrum +3 start menu. Solo Forth will
   be autoloaded.

There's no way to access the library disks yet, so the Forth system is
almost useless on +3DOS.

== How to use the library

The library disk contains the source code in Forth blocks, written
directly on the disk sectors, without any filesystem.  In order to use
the library, follow these steps:

1. Run Solo Forth.
2. Insert the the library disk:
** In G+DOS: "Insert" the file <disks/gplusdos/disk1_lib.mgt> as disk
   2 of the Plus D disk interface.
** In TR-DOS: "Insert" the file <disks/trdos/disk1_lib.trd> as disk A
   of the Beta 128 disk interface.
3. Type `1 load` to load block 1 from the library disk. By convention,
   block 1 is used as a loader.  In this case, block 1 contains `2
   load`, in order to load `need` and related words from block 2.
4. Type `need name`, were "name" is the name of the word or tool you
   want to load from the library.

Disk image number 1 contains only the library.  Disk images from
number 2 contain the library plus sample games, benchmarks and tests,
as their filenames read.

=== Library index

`need` and family search the index line (line 0) of all blocks of the
disk for the first occurence of the required word, within a
configurable range of blocks (using the variables `first-locatable`
and `last-locatable`).  Of course, nested `need` are resolved the same
way: searching the library from the beginning.  This can be slow.
This is not a problem, because the goal of Solo Forth is cross
development, and therefore only the last step of the development loop,
i.e., the compilation of the sources from the disk images created in
the host system, compilation that includes all the slow searching of
library blocks, is done is the real (actually, emulated) machine. But
the system includes a tool to create an index of the library, which is
used to locate their contents instantaneously, what makes things more
comfortable when the Forth system is used interactively.

How to use the library index:

1. Load the indexer with `need make-thru-index`.
2. Make the index and activate it with `make-thru-index`.
3. The default behaviour (no index) can be restored with
   `use-no-index`.  The index can be reactivated with
   `use-thru-index`.

The indexer creates an index (actually, a Forth word list whose
definitions use no code or data space) and changes the default
behaviour of `need` and related words to use it. Then `need name` will
automatically start loading the first block where the word "name" is
defined.

[caption="Time and memory required to make the library index"]
|===
| DOS     | First block | Last block | Seconds | Far memory

| G+DOS   |           5 |        799 |     154 |      13498
| TR-DOS  |           5 |        635 |     135 |      13027
|===

NOTE: The far memory is the virtual 64-KiB space formed by 4
configurable memory banks. No code or data space is used by the
indexer.

An alternative indexer is under development. It's activated with
`use-fly-index` and does not make and index in advance: Instead, it
indexes the blocks on the fly, when they are searched the first time.
This indexer is included in version 0.12.0 but it's not finished yet.

== Documentation

At the moment, the only documentation is this README file, the
sources, and a file in the <doc/> directory that explains the stack
notation.

Most words are fully documented in the kernel and the library source
files, and those comments are marked in order to extract them from the
sources and build a fully organized and indexed glossary in
http://asciidoctor.org[Asciidoctor] format, that will be automatically
converted to HTML, EPUB and other formats.

The tool that will build the documentation is under development,
written in Gforth, and it will be included in a future version of Solo
Forth.

=== How to search the library

A simple wrapper script is provided to search the library for a
regular expression. It's used during the development, but it can be
useful for the user too.

Usage examples:

----
tools/search_library.sh make-thru-index
tools/search_library.sh make-thru-index -l
tools/search_library.sh color
tools/search_library.sh ":\scolor\s"
----

The script uses `ack`, but it can be replaced with the more common
`grep`. They are compatible.

== How to write Forth programs

In order to use Solo Forth to write programs for ZX Spectrum,
programmers already acquainted with Forth and Linux systems can
extract all the required information from the <Makefile> of Solo
Forth.

The only difference between building Solo Forth and building a Forth
program is the additional files added to disk image 0 (the boot disk),
if needed, and the library modules included in disk image 1 (the
library disk), which also contains the source of the program.  If
the program does not need to use the disk at run-time, you can simply
copy the default disk 0, and boot it to load your program from block
1 of your customized disk 1, with a simple `1 load`. When the
program is finished, you can save a snapshot with the ZX Spectrum
emulator.

Some simple little games are provided as examples in the library.
They are in their own disk image, which contains also the whole
library. Some of them are not finished yet.

In order to try and fix the Forth system during its development, two
more complex game projects are being developed at the same time. They
will be published soon in a public Git repository. They will be useful
as examples.

=== Vim support

In order to make Vim recognize and highlight the Solo Forth sources,
with the ".fsb" extension, copy the contents of the <./vim/> directory
to your home <~/.vim/> directory.

== How to build

If you modify the kernel or the library, you need to build the system.

First, see the requirements listed in the header of <Makefile> file
and install the required programs. Then enter the project directory
and use one of the following commands to build the disk images for
your DOS of choice:

|===
| DOS          | Command

| G+DOS        | `make gplusdos`
| TR-DOS       | `make trdos`
| +3DOS        | `make plus3dos`
| All of them  | `make all` or simply `make`
|===

The correspondent disk images will be recreated in the <disks>
directory.

