= Solo Forth history

.2015-06-02:

Start, based on the disassembled code of Abersoft Forth
(http://programandala.net/en.program.abersoft_forth.html).

First changes:

Some fig-Forth words are renamed with their modern forms: `vlist` as
`words`, `-dup` as `?dup`, `minus` as `negate`, `dminus` as
`dnegate`, `s->d` as `s>d`, `mon` as `bye`, `free` as `unused`.

Old synonyms are removed: `end` and `endif`.

The editor is removed.

`branch` and `back` are modified to do absolute branches.  The
branches are converted with a simple substitution, thanks to the
comments prepared by the disassembling of Abersoft Forth.

New words, from the Afera library: `\`, `.(`, `char` and `[char]`,
`2-`, `1-`, `2*`.

`2+` and `1+` are converted to Z80.

`forth` is not immediate any more.

`'` is converted to non-immediate; new immediate version: `[']`.

.2015-06-03:

`dliteral` is renamed as `2literal`.

Removed: `verify`.

.2015-06-04:

New: `upperc` and `uppers`.

Improvement: `-find` is made case insensitive.

`key` is documented.

Removed: `udg`, `init-disc`, `.cpu`.

New: `<>`.

Improvement: the lower part of the screen can be used.

Removed: `loadt`, `savet`, `(tape)` and tape headers.

Removed: `triad`.

Change: `inp` renamed as `p@`; `outp` renamed as `p!`.

Change: stacks and buffers are moved to the bottom of the memory map,
before the interpreter. They must be below 0xC000 in order to use the
memory banks.

Change: `r` renamed as `r@`; the Z80 code of `i` is moved to `r@`, and
the cfa of `i` is pointed to the pfa of `r@`. This is logical and
faster (formerly `r` was a colon word that called `i`).

New: `clit` and `cliteral`. Their code ocuppies 46 bytes, but there
are 84 compiled bytes that save one byte when using `clit` instead of
`lit`, and it's faster.

Change: `bleep` is moved to the blocks disk.

Improvement: `quit` is optimized: faster and smaller.

New: `bounds`; used in `type`.

Removed: `not` (synonym of `0=`).

Change: `offset` deactivated.

New: `block>sector` and first tries with the new version of `r/w`,
that uses the sectors of the disk.  The screens can be listed, but
only the first time. They are shown corrupted when trying to access
them more than once. Something is wrong.

.2015-06-05:

New: `nip`, `tuck`.

Improvement: `2drop` rewritten in Z80.

New: `rdrop`, in Z80 (`exit` is pointed to it); `2rdrop` and `unloop`.

Removed: `plot` (faster version, from Afera, added to the blocks
disk); `draw` (faster version will be create).

Improvement: Error messages are included in screens 4 and 5 of the
blocks disk.  In order to avoid numbers 0 and 16 (that coincide with
the first lines of screens 4 and 5, and are incompatible with the fsb
format), some error messages are reorganized (and updated in the main
source).

New: `-rot` in the blocks disk.

New: `recurse`.

Change: `pfa` is renamed as `nfa>pfa`; the rest of the family is
renamed with the prefix "pfa>". This is a first step before
reorganizing the headers to make them faster, probably moving the lfa
before the nfa, and also modifying `'` and `[']` to return the cfa
instead of the pfa.

Fix: there was an old relative branch calculation in `then`.

Fix: `cliteral`, recently implemented, used `comma`!

Fix: `+buf` used `clit` for the new `b/buf 4 + `, that is greater than
0xFF! Now the blocks in disk work fine.

Change: The first six user variables, unused, are moved to the end of
the space. All the related pointers are apdated. Conditional
compilation is used, just in case. The final goal is to reorganize the
parameter area, removing all unnecessary fig-Forth stuff.

Change: Entry points are moved to the start (new origin).

.2015-06-06:

New: `msg-scr`, idea from lina ciforth, useful to customize the
organization of the screens on disk.

.2015-06-07:

Change: faster and smaller versions of `ink` and `paper`, from the Afera library.
This saves 264 bytes!

New: constants `true` and `false`; primitives `on` and `off`.

Change: conditional compilation flag to free the IX register,
originally used as the user variables pointer, in order to hold
`next`. This way jumps to `next` are faster and save one byte per jump
(52 bytes saved).

Change: `user_variables_pointer_init_value` is removed. The fig-Forth
model uses it in `cold`, but it's not needed because the memory map is
not calculated during the cold start.  In fact it is not used by
Abersoft Forth.

Fix: The new version of `at`, taken from Spectrum Forth-83, had a
copying mistake, a missing `dup`.

New: `continued`, as a factor of `load`.

Change: optimizations in the definitions, thanks to the new words:
`1-` instead of `1 minus`, `2-` instead of `2 -`.
Also `2dup` instead of `over over`, an oversight of Abersoft Forth.

Improvement: Some operators are (re)written, using Z80 code from DZX-Forth.

.2015-06-08:

Improvement: faster `blanks` and `erase`, with Z80 jumps into `fill`.

Improvement: the branches of `x` (the null word) are optimized.

Improvement: one branch removed from `."` (2 bytes less, and faster in
compiling mode).

Change: Now `'` and `[']` return the cfa, not the pfa.

New: `cfa>pfa`, `cfa>lfa`, `cfa>nfa` (`pfa>nfa` and `pfa>lfa` could be removed).

Change: `forget` is updated to the new behaviour of `'` and moved to
the blocks file; also the code in the blocks file is updated.

.2015-06-09:

Change: `flash`, `bright`, `gover` and `inverse` are moved to the disk.

Problem detected with `(emit)` and those four booleans attributes.

New: `pick`, from DZX-Forth.

Change: The original system to print out with `link` wasn't
practical, because it copied to the printer everything that was
printed on the screen.  It is removed. Now the new words `printer` and
`display` are used instead.

.2015-06-10:

Changes in `(emit)`, in order to fix the problems with boolean
attributes. It seems the channel must be opened every time; or the
temporary attributes must be set.  Finally, all color words are
written in Z80, in the kernel, sharing one main routine: printing the
chars required to set the temporary attribute, and then calling the
ROM routine that makes it permanent. This method works for all
attributes and print flags. Example:

----
paper_nfa:
  db 0x05+0x80,'PAPE','R'+0x80
paper_lfa:
  dw bright_nfa
paper_:
  dw paper_pfa
paper_pfa:
  ld a,paper_char
  jp color

ink_nfa:
  db 0x03+0x80,'IN','K'+0x80
ink_lfa:
  dw paper_nfa
ink_:
  dw ink_pfa
ink_pfa:
  ld a,ink_char
color:
  ; Set a color attribute (ink, paper, bright, flash, inverse or gover).
  ; a = attribute control char
  ; (tos) = color attribute value
  rst 0x10
  pop hl
  ld a,l
  rst 0x10
  call rom_set_permanent_colors_0x1CAD
  _jp_next
----

The color words are removed from the blocks disk.

Improvement: smaller and faster `?terminal`.

Change: the use of the IX register to hold the address of `next` is
made definitive. The conditional compilation for the old method is
removed.

Improvement: when the IX register must be preserved because of ROM
calls, now `ld ix,next` is used instead of `push ix` and `pop ix`;
it's faster and easier, and uses the same memory (4 bytes).

.2015-06-11:

The parameters of `enclose` have been exchanged. This saves a `swap` in `word`.

.2015-06-13:

The parsing bug has been found. The problem is `enclose` use an 8-bit
register as offset counter. It can not be used to scan a 512-byte buffer.
The code has been rewritten to use a pair register as offset counter.

There's a second bug: something fails when the parsing of the screen
passes from the first to the second disk block.

Some experimental changes to the null word, with simpler and faster
flow.

.2015-06-17:

Modification in `expect`; the code that manages the delete key wasted some bytes.

Fix: `on` and `off` changed only the first part of the value! That was
the reason the second block of screens was not parsed: `in` was not
properly set to zero in the null word.

Improvement: One byte saved in `id.`.

Fix: typo in number in `pixel`. Now the new `point` and `plot` work
with Y coordinate range 0..191.

New: the strings module of the Afera library is included in the disk.

New: `code` (based on `create`, that will be rewritten), `end-code`,
`assembler` (empty vocabulary).

New: `[defined]`, `[undefined]`, `?-->` and `?\` are included in the
kernel, copied from the Afera library. They are essential to manage
the disk screens.

Improvement: `2swap` is rewritten is Z80, copying the code from
DZX-Forth.

Change: `size` is moved to the disk. It's needed only by `system`.

Change: `-find` is renamed as `find`, and factored out with
`context-find`, in order to implement `defined?`, needed by `required`.

Change: `i'` is moved to the disk.

New: `rp`, required to rewrite `i'` outside the kernel.

.2015-06-18:

Improvement: Macros are used to create the headers.

Fix: `?exit`.

Improvement: faster and smaller `2@` and `2over`, `do_two_constant`.

----
if 0 ; XXX OLD -- From Abersoft Forth

  inc hl    ; T06  1
  inc hl    ; T06  1 ; high part
  ld e,(hl) ; T07  1
  inc hl    ; T06  1
  ld d,(hl) ; T07  1
  push de   ; T11  1
  dec hl    ; T06  1
  dec hl    ; T06  1
  ld d,(hl) ; T07  1
  dec hl    ; T06  1
  ld e,(hl) ; T07  1
  push de   ; T11  1
  _jp_next  ; T08  2
            ;T104 14 TOTAL

else ; XXX NEW -- From DZX-Forth

  ld e,(hl) ; T07  1
  inc hl    ; T06  1
  ld d,(hl) ; T07  1
  inc hl    ; T06  1
  ld a,(hl) ; T07  1
  inc hl    ; T06  1
  ld h,(hl) ; T07  1
  ld l,a    ; T04  1
  ex de,hl  ; T04  1
  jp pushde ; T10  3
            ; T11  0 push de
            ; T11  0 push hl
            ; T86 12 TOTAL
----


New: `2r@`.

Change: First changes to modify the format of the name field, removing
the end bit of the last char. The new format will make some things
easier.

Change: `dr0` removed.

Improvement: `nip` used in `/` and `*/`.

.2015-06-19:

Improvement: The new format of name fields is finished and working.
The old format can be selected with conditional compilation, just in
case, until the system is fully tested.

Some things, like `id.`, are simpler now:

----
  _colon_header id_dot_,'ID','.'

if fig_name_field?

  dw pad_
  dw c_lit_
  db max_word_length+1
  dw c_lit_
  db 0x5F ; XXX why this char?
  dw fill_
  dw dup_,nfa_to_lfa_,over_ ; ( nfa lfa nfa )
  dw minus_ ; ( nfa len+1 )
  dw pad_,swap_,cmove_
  dw pad_,count_ ; ( pad len+name_bound_bit_mask+n )
  dw c_lit_
  db max_word_length
  dw and_ ; ( pad len )
  dw two_dup_,plus_,one_minus_ ; address of the last char ( pad len pad+len-1 )
if 0 ; XXX OLD
  dw dup_,fetch_
  dw lit_,0xFF7F,and_
  dw swap_,store_
else ; XXX NEW
  dw dup_,c_fetch_
  dw c_lit_
  db 0x7F
  dw and_,swap_,c_store_
endif
  dw type_,space_
  dw semicolon_s_

else ; XXX NEW -- name field without end bit in the last char

  dw count_
  dw c_lit_
  db max_word_length_bit_mask
  dw and_
  dw type_,space_
  dw semicolon_s_

endif
----

The main change is `(find)`:

----
  _code_header paren_find_,'(FIND',')'

; (FIND)  ( ca nfa --- pfa b tf | ff )

if fig_name_field?

  ; XXX TODO optimize speed with absolute jumps?
  ; XXX TODO -- return cfa instead of pfa
  ; XXX TODO -- always return two elements, after Forth-94
  pop de ; nfa
paren_find.begin:
  ; (sp) = string address
  ; de = nfa
  pop hl ; string address
  push hl ; save for next iteration
  ld a,(de) ; length byte
  xor (hl) ; filter deviations
  and 0x3F ; mask msb and precedence bit
  jr nz,paren_find.skip_name_field ; lengths differ
paren_find.compare_next_char:
  inc hl ; next character in string
  inc de ; next character in name field
  ld a,(de)
  xor (hl) ; filter deviations
  add a,a
  jr nz,paren_find.not_a_match ; no match
  jr nc,paren_find.compare_next_char ; match so far, loop again
  ; The string matches.
  ; de = address of the last char of the name field
  ld hl,0x0005 ; offset from lfa-1 to pfa
  add hl,de
  ex (sp),hl ; pfa to stack
paren_find.search_for_length_byte:
  dec de ; position de on nfa
  ld a,(de)
  or a ; msb=1?; if so, length byte
  jp p,paren_find.search_for_length_byte ; no, try next char
  ld e,a ; length byte
  ld d,0x00
  ld hl,true
  jp pushde ; name field found, return
paren_find.not_a_match:
  ; Above name field not a match, try next one
  jr c,paren_find.name_field_skipped ; carry = end of name field
paren_find.skip_name_field:
  ; Find end of name field
  inc de
  ld a,(de)
  or a ; msb=1?
  jp p,paren_find.skip_name_field ; no, loop
paren_find.name_field_skipped:
  inc de ; lfa
  ex de,hl
  ld e,(hl)
  inc hl
  ld d,(hl)
  ld a,d
  or e ; end of dictionary?
  jp nz,paren_find.begin ; if not, continue
  ; No match found, return
  pop hl ; drop string address
  jp false_pfa

else

  ld (ip_backup),bc ; save Forth IP
  pop de ; nfa
  pop hl ; string address
  ld (paren_find.string_address),hl
paren_find.begin:
  ; Compare the string with a new word.
  ; de = nfa
  ld (paren_find.nfa_backup),de ; save for later
paren_find.string_address: equ $+1
  ld hl,0 ; string address
  ld a,(de) ; name field length byte
  ld c,a    ; save for later
  and max_word_length_bit_mask  ; actual length
  cp (hl)
  jr nz,paren_find.not_a_match ; lengths differ
  ; Lengths match.
  ld a,c ; name field length byte
  and max_word_length_bit_mask  ; actual length
  ld b,a
paren_find.compare_next_char:
  inc hl ; next character in string
  inc de ; next character in name field
  ld a,(de)
  cp (hl)
  jr nz,paren_find.not_a_match ; no match
  djnz paren_find.compare_next_char ; match so far, loop again

  ; The string matches.
  ; de = address of the last char of the name field
  ; c = name field length byte
  ld hl,5 ; offset from lfa-1 to pfa
  add hl,de
  push hl ; pfa
  ld e,c ; length byte
  ld d,0
  ld hl,true
  ld bc,(ip_backup) ; restore Forth IP
  jp pushde

paren_find.not_a_match:
  ; Not a match, try next one.
paren_find.nfa_backup: equ $+1
  ld hl,0 ; nfa
  ld a,c ; length byte
  and max_word_length_bit_mask  ; actual length
  ld c,a ; actual length
  inc c ; plus the length byte
  ld b,0
  add hl,bc ; hl = lfa
  ld e,(hl)
  inc hl
  ld d,(hl)
  ld a,d
  or e ; end of dictionary?
  jp nz,paren_find.begin ; if not, continue

  ; No match found, return.
  ld bc,(ip_backup) ; restore Forth IP
  jp false_pfa

endif
----

Change: The new word `header` substitutes `create`. `create` is
changed after Forth-94. Its role in fig-Forth was already taken by
`code`.

Change: First steps to implement a modern version of `find`, after
Forth-83 and Forth-94.

Fix: `message` had a strange condition, from Abersoft Forth,
to prevent from printing message number zero when `warning` is on.

.2015-06-20:

The new version of `find`, rewritten after Forth-83 and Forth-94, seems to work fine.
Also the new version of the name field works fine.
Conditional compilation is used for both changes, just in case.

New: `error` does not push the values of `blk` and `in`, but stores
them in a new double variable called `error-pos`. `where` fetchs them
from there. This is cleaner and more flexible, because the last error
position can be shown any time.

New: `label`, a define word that returns the address of its pfa, like
a variable, but stores nothing into it. Useful to create machine code
routines or data buffers.

New: `nfa>string`, adapted from DZX-Forth. It was a natural factor of
the new version of `id.`.
