= Solo Forth history

.2015-06-02:

Start, based on the disassembled code of Abersoft Forth
(http://programandala.net/en.program.abersoft_forth.html).

First changes:

Some fig-Forth words are renamed with their modern forms: `vlist` as
`words`, `-dup` as `?dup`, `minus` as `negate`, `dminus` as
`dnegate`, `s->d` as `s>d`, `mon` as `bye`, `free` as `unused`.

Old synonyms are removed: `end` and `endif`.

The editor is removed.

`branch` and `back` are modified to do absolute branches.  The
branches are converted with a simple substitution, thanks to the
comments prepared by the disassembling of Abersoft Forth.

New words, from the Afera library: `\`, `.(`, `char` and `[char]`,
`2-`, `1-`, `2*`.

`2+` and `1+` are converted to Z80.

`forth` is not immediate any more.

`'` is converted to non-immediate; new immediate version: `[']`.

.2015-06-03:

`dliteral` is renamed as `2literal`.

Removed: `verify`.

.2015-06-04:

New: `upperc` and `uppers`.

Improvement: `-find` is made case insensitive.

`key` is documented.

Removed: `udg`, `init-disc`, `.cpu`.

New: `<>`.

Improvement: the lower part of the screen can be used.

Removed: `loadt`, `savet`, `(tape)` and tape headers.

Removed: `triad`.

Change: `inp` renamed as `p@`; `outp` renamed as `p!`.

Change: stacks and buffers are moved to the bottom of the memory map,
before the interpreter. They must be below 0xC000 in order to use the
memory banks.

Change: `r` renamed as `r@`; the Z80 code of `i` is moved to `r@`, and
the cfa of `i` is pointed to the pfa of `r@`. This is logical and
faster (formerly `r` was a colon word that called `i`).

New: `clit` and `cliteral`. Their code ocuppies 46 bytes, but there
are 84 compiled bytes that save one byte when using `clit` instead of
`lit`, and it's faster.

Change: `bleep` is moved to the blocks disk.

Improvement: `quit` is optimized: faster and smaller.

New: `bounds`; used in `type`.

Removed: `not` (synonym of `0=`).

Change: `offset` deactivated.

New: `block>sector` and first tries with the new version of `r/w`,
that uses the sectors of the disk.  The screens can be listed, but
only the first time. They are shown corrupted when trying to access
them more than once. Something is wrong.

.2015-06-05:

New: `nip`, `tuck`.

Improvement: `2drop` rewritten in Z80.

New: `rdrop`, in Z80 (`exit` is pointed to it); `2rdrop` and `unloop`.

Removed: `plot` (faster version, from Afera, added to the blocks
disk); `draw` (faster version will be create).

Improvement: Error messages are included in screens 4 and 5 of the
blocks disk.  In order to avoid numbers 0 and 16 (that coincide with
the first lines of screens 4 and 5, and are incompatible with the fsb
format), some error messages are reorganized (and updated in the main
source).

New: `-rot` in the blocks disk.

New: `recurse`.

Change: `pfa` is renamed as `nfa>pfa`; the rest of the family is
renamed with the prefix "pfa>". This is a first step before
reorganizing the headers to make them faster, probably moving the lfa
before the nfa, and also modifying `'` and `[']` to return the cfa
instead of the pfa.

Fix: there was an old relative branch calculation in `then`.

Fix: `cliteral`, recently implemented, used `comma`!

Fix: `+buf` used `clit` for the new `b/buf 4 + `, that is greater than
0xFF! Now the blocks in disk work fine.

Change: The first six user variables, unused, are moved to the end of
the space. All the related pointers are apdated. Conditional
compilation is used, just in case. The final goal is to reorganize the
parameter area, removing all unnecessary fig-Forth stuff.

Change: Entry points are moved to the start (new origin).

.2015-06-06:

New: `msg-scr`, idea from lina ciforth, useful to customize the
organization of the screens on disk.

.2015-06-07:

Change: faster and smaller versions of `ink` and `paper`, from the Afera library.
This saves 264 bytes!

New: constants `true` and `false`; primitives `on` and `off`.

Change: conditional compilation flag to free the IX register,
originally used as the user variables pointer, in order to hold
`next`. This way jumps to `next` are faster and save one byte per jump
(52 bytes saved).

Change: `user_variables_pointer_init_value` is removed. The fig-Forth
model uses it in `cold`, but it's not needed because the memory map is
not calculated during the cold start.  In fact it is not used by
Abersoft Forth.

Fix: The new version of `at`, taken from Spectrum Forth-83, had a
copying mistake, a missing `dup`.

New: `continued`, as a factor of `load`.

Change: optimizations in the definitions, thanks to the new words:
`1-` instead of `1 minus`, `2-` instead of `2 -`.
Also `2dup` instead of `over over`, an oversight of Abersoft Forth.

Improvement: Some operators are (re)written, using Z80 code from DZX-Forth.

.2015-06-08:

Improvement: faster `blanks` and `erase`, with Z80 jumps into `fill`.

Improvement: the branches of `x` (the null word) are optimized.

Improvement: one branch removed from `."` (2 bytes less, and faster in
compiling mode).

Change: Now `'` and `[']` return the cfa, not the pfa.

New: `cfa>pfa`, `cfa>lfa`, `cfa>nfa` (`pfa>nfa` and `pfa>lfa` could be removed).

Change: `forget` is updated to the new behaviour of `'` and moved to
the blocks file; also the code in the blocks file is updated.

.2015-06-09:

Change: `flash`, `bright`, `gover` and `inverse` are moved to the disk.

Problem detected with `(emit)` and those four booleans attributes.

New: `pick`, from DZX-Forth.

Change: The original system to print out with `link` wasn't
practical, because it copied to the printer everything that was
printed on the screen.  It is removed. Now the new words `printer` and
`display` are used instead.

.2015-06-10:

Changes in `(emit)`, in order to fix the problems with boolean
attributes. It seems the channel must be opened every time; or the
temporary attributes must be set.  Finally, all color words are
written in Z80, in the kernel, sharing one main routine: printing the
chars required to set the temporary attribute, and then calling the
ROM routine that makes it permanent. This method works for all
attributes and print flags. Example:

----
paper_nfa:
  db 0x05+0x80,'PAPE','R'+0x80
paper_lfa:
  dw bright_nfa
paper_:
  dw paper_pfa
paper_pfa:
  ld a,paper_char
  jp color

ink_nfa:
  db 0x03+0x80,'IN','K'+0x80
ink_lfa:
  dw paper_nfa
ink_:
  dw ink_pfa
ink_pfa:
  ld a,ink_char
color:
  ; Set a color attribute (ink, paper, bright, flash, inverse or gover).
  ; a = attribute control char
  ; (tos) = color attribute value
  rst 0x10
  pop hl
  ld a,l
  rst 0x10
  call rom_set_permanent_colors_0x1CAD
  _jp_next
----

The color words are removed from the blocks disk.

Improvement: smaller and faster `?terminal`.
