= Solo Forth TO-DO

.2015-06-04:

Move the most used words to the top of the `forth` vocabulary: `:`,
`;`, stack words, control structures, etc.  This should speed up the
compilation of sources.

.2015-06-05:

Fix `?exit`.

Fix: `begin` structures produce compilation errors in screens, but not
in the terminal!

Still strange problems with the stacks:

The problem seems to be, `?stack` is used only by `interpret`, but not
during the execution of a word. When a word stacks several numbers,
they can corrupt the zone below the stack before `?stack` detects the
overflow.

.2015-06-06:

Save the error code, in case `warning` is -1.

Make `where` to use values saved somewhere, not on the stack.

DZX-Forth implements `exit` simple as `compile (exit)`, and
`exit` is the word called by `;`. Compare both implementations.

Define `rp`, like in Afera:

  HEX  5E68 CONSTANT RP  DECIMAL

.2015-06-07:

Write a version of `screen` that recognizes the UDG.

Change: move key to the blocks, as `mode-key` or similar, and use a
simpler `key` (`akey` from Afera).

.2015-06-09:

In order to save compilation time, move inner words to the bottom of
the dictionary. Example: `(loop)`, `clit`, `back`, `digit`...

.2015-06-10:

Adapt this word from Spectrum Forth-83, that uses it in `cold` and `query`:

  : TERMINAL ( --- )
    LIT PKEY (KEY) !    \ Set default handler for KEY.
    >S ;                \ And initialize screen output.

Fix?: in 128, typing graphics T and U prints the new tokens.

New: A printing routine instead the ROM routines, with two fonts: for
chars 0..127 and for chars 128..255.

.2015-06-17:

Change the header format:

lfa   dw nfa
nfa   db len+bits,"name"
cfa   dw a
pfa   ...

Then write a macro to create the link field and the name field.


