= Solo Forth TO-DO

.2015-06-06:

DZX-Forth implements `exit` simple as `compile (exit)`, and
`exit` is the word called by `;`. Compare both implementations.

.2015-08-12:

Solve `;s` vs `exit`. Compare CamelForth, DZX-Forth...

.2015-06-07:

Write a version of `screen` that recognizes the UDG.

Change: move key to the blocks, as `mode-key` or similar, and use a
simpler `key` (`akey` from Afera).

.2015-06-09:

In order to save compilation time, move inner words to the bottom of
the dictionary. Example: `(loop)`, `clit`, `back`, `digit`...

.2015-06-10:

Adapt this word from Spectrum Forth-83, that uses it in `cold` and `query`:

  : TERMINAL ( --- )
    LIT PKEY (KEY) !    \ Set default handler for KEY.
    >S ;                \ And initialize screen output.

New: A printing routine instead the ROM routines, with two fonts: for
chars 0..127 and for chars 128..255.

.2015-06-17:

New:
- Case-sensitive mode.
- Create words in lowercase.
- Improve `parse-name` with case conversion and move it to the kernel.

.2015-06-20:

New: `executing?` after DZX-Forth.

New: `rshift` and `lshift`, from DZX-Forth.

.2015-06-22:

New: `within`, `between`, from DZX-Forth.

This error happens in all fig-Forth systems:

----
: test 6 literal ;  RAL ? [ rubbish ] MGS # 2
----

.2015-06-25:

New: `??`. A control structure than executes the next compiled word if
TOS is non-zero, else skip it.

.2015-06-28:

Fix: Something went wrong after the massive of the `_number` macro:
`.` does not print well; `require` gives error 0!...  The problem is
`_number -1`! Why? I wrote the autor of Pasmo. (He helped).

.2015-06-30:

New: command history, stored in the names bank.

Change: remove double `;s` from the colon words in the kernel. Use
`exit` instead, else the word can not be decoded. [2015-08-12: Two
cases found and marked.]

Change: modify `expect` after Spectrum Forth-83.

Change: modify `key` after Forth-83 and ANS Forth.

Change: compare the user variables with those of Spectrum Forth-83.

.2015-07-05:

From F83:

----
: MAP  ( n pfa --- addr )
  \ Given the pfa of a case word and the index n for case
  \ selection, return the execution address selected. Abort if the
  \ index is out of range.
  2DUP @  \ Fetch the range from pfa.
  U< IF  \ Is the index n within range?
    2+ SWAP 2* +  \ Address of the execution code.
  ELSE OUT  \ Abort if out of range.
  THEN
  ;

: CASE:  ( n --- )
  \ A positional case statement. The range n is used for error checking.  At runtime, the nth word is executed, depending on the value on stack when executed.
  CONSTANT  \ Compile the range n as a constant.
  HIDE  \ Smudge the name field as : would do.
  ]  \ Now, use the colon compiler to compile the cases.
     \ Compilation will be terminated by the ; command.
  DOES>  ( index --- )  \ At runtime, use the index to find the execution address among the compiled cases and execute it.
    MAP  \ Return the address pointing to one of the cases compiled.
    PERFORM  \ Execute it.
  ;
----


.2015-07-23:

Study how to save and load the main code and the name bank apart, in
two files. This way `turnkey` could be used also to save a modified
copy of the system, not just Forth programs. Simpler solution: use the
snapshop option of the +D.

Adapt the markups of Z88 CamelForth to extract the glossary from the
source.

Fix: the string searched for by `(find)` must be in the string buffer,
below 0xC000! This is not a problem now, during the development,
because the dictionary is small. A specific buffer is needed.

New: `lower` and `lowers`.

Idea: 2 more bytes for `base`, to be used as save-restore space.

----
  : exchange  ( a1 a2 -- )  2dup @ swap @  rot ! swap !  ;
    \ Exchange the 16-bit contents of a1 and a2.

  : cexchange  ( ca1 ca2 -- )  2dup c@ swap c@  rot c! swap c!  ;
    \ Exchange the 8-bit contents of a1 and a2.

  : switch  ( a1 -- )  dup cell+ exchange  ;
    \ Exchange the 16-bit contents of a1 and the following cell.

  \ Example:

  base switch hex

  base switch
----

.2015-08-12:

Change: remove the control structure checking (`?pairs`). (now it's
conditionally compiled in the kernel)

Change: make the vocabulary links point to the pfa of the
vocabularies? `vocabulary` should be adapted too. The advantage is the
pfa is also the id used in search order and returned by `wordlist`.
A word `pfa>vlfa` would be helpful.

New: `cvariable`.

Fix: `attr`.

Improve: version in the greeting message.

.2015-08-14:

Fix: problem when compiler security is off.

.2015-08-15:

Idea: maybe 0 could be used instead of 0x7fff to init the block number of a buffer.

Idea: instead of update bit, `negate` the number. Then `abs` can be used.

.2015-08-26:

Finish `sound:`.

New: `cvalue`, `2value`.
