= Solo Forth TO-DO
:author: Marcos Cruz (programandala.net)
:revdate: 2017-01-19

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

// Assembler {{{1
== Assembler ==

.2017-01-13:

Modify words that restore IX: use the current contents of `next` instead of its
default value. This way the value of IX can be changed to implement a debugger
or multitasking.

.2017-01-13:

Move standard `end-code` to the library and use `;c` in the kernel instead?
Space is precious in blocks.

.2016-12-30..2017-01-02:

NOTE: Milestone: 0.13.0

Rewrite all small code words in Z80 opcodes, without assembler.  Example:
`lshift`, `(g-emit)` and family, `f!`, `f@`, `fast-rnd`, `get-drive`,
`set-drive`, `crnd`, `(delete-file)`, `n>r`, `nr>`...

.2016-12-20:

Data space used by the assemblers:

`z80-asm` :: 1817 B
`z80-asm,`:: 1664 B

// Benchmarks {{{1
== Benchmarks ==

NOTE: Milestone: 0.14.0

- Benchmark current `times` and new version that keeps the xt in the return
  stack in the loop: `do dup r> execute r> loop drop`.
- Benchmark two library versions of `m*/`.
- Benchmark two library versions of `d=` and `d<>`.

.2016-12-06:

NOTE: Milestone: 0.14.0

Rename `bench{` and `}bench` and family. Maybe after SwiftForth: `counter` and
`timer`.

.2016-04-25:

Benchmark the system without constants `0`, `1` and `2`.

With constants::    32598 B free
Without constants:: 32572 B free
Diff::              +26 B

// Bugs {{{1
== Bugs ==

.2017-01-11:

`view` gets trapped in `wait-for-key` at the end, why?

.2017-01-04:

Check some of the RNG benchs.  The machine resets at the end of some
of them. They are marked in the source.

// Code style {{{1
== Code style ==

.2017-01-06:

Change the code style after Pygmy Forth:

- Remove the last space in paren comment.
- Use only one space before and after paren comments.
- Use a single dash in stack comments.

// Interpreter/compiler {{{1
== Interpreter/compiler ==

.2017-01-05:

Rewrite `there` in Z80 or remove it?

.2016-12-03:

Use a new kind of unconditional high-level branch at the end of `nest-source`
and `unnest-source`:

----
goto  ( a -- )
----

Make it consistent with the planned changes in the current low-level branches.

.2016-11-20:

Add `fast` and `slow`, after ACE Forth, to deactivate/activate some checks:
`?stacks`, `limit` and `farlimit` (not used yet), etc.

.2016-05-17:

Improve the search order words, after Forth-2012.

.2016-04-27:

Rewrite `'` after Gforth. See Gforth's `(')`, `name?int`,
`name>int`, etc. Factor `defined` and `comp'` accordingly.

.2016-05-18:

Remove the `root` word list. Set the minimum search order to `forth`.

.2016-11-13:

Make `dp` an ordinary variable? Then `here`, `there` and `allot` could be
improved, rewritten in Z80.

.2016-05-31:

Add `''` to get the execution token pointer of a name, so the actual name of
an alias could be get this way:

----
'' wordname >>name .name
----

.2016-05-15:

Check if `current-latest`, used in the library, can be replaced with `latest`.

.2016-05-09:

Idea: in DX-Forth, `last` is a 2-cell variable that holds both the nt and the
xt: `last @ ( nt )` and `last 2@ ( xt nt )`.

.2016-04-29:

Factor the return stack manipulation done by `(.")` in order to
reuse it in `(abort")` and `(warning")`. Use a variant of pForth's `param`.

.2016-04-28:

Finish the implementation of control stack words.

.2016-04-21:

Make `jp pushhlde` a macro dependent of `size_optimization`: compile `jp
pushhlde` or `push de / push hl / jp (ix)`. The second option needs one more
byte but is 2 T-cycles faster.

.2015-11-12:

`+bal`, `-bal` or similar, to change `csp`:

----
: [+csp]  ( -- )  [ cell negate ] literal csp +!  ; immediate compile-only
: [-csp]  ( -- )  cell csp +!  ; immediate compile-only
----

But to compile an external number inside a definition,
a trick is `[ dup ] literal` and a `drop` after `;`.

.2015-06-09:

In order to save compilation time, move inner words to the bottom of
the dictionary. Example: `(loop)`, `clit`, `back`, `digit`...

.2016-03-19:

Separate header flags from the length byte of the name field.  This way more
bits will fit (alias, deferred, special behaviour), and word names will be
actual strings.

// Control structures {{{1
== Control structures ==

.2016-12-26:

Add default execution token to `switch:`.

.2016-12-26:

Choose a better name for `?repeat`.

.2016-12-20:

Document the variants of `of`.

.2016-12-07:

Use `>bstring` (new name for `>cell-string`), `2>bstring`, `c>bstring`
(already exists as `char>string`).
 
.2016-11-26:

Change `??` to its old version, which is more useful:

----
  \ XXX TODO -- 2016-11-26: It seems more useful the old
  \ version, extended as the rest of alternative conditionals:
  \
  \ : ??   ( f -- )   0= if  r> cell+ >r  then  ; compile-only
  \ : 0??  ( f -- )      if  r> cell+ >r  then  ; compile-only
  \ : -??  ( f -- )  0>= if  r> cell+ >r  then  ; compile-only
  \ : +??  ( f -- )   0< if  r> cell+ >r  then  ; compile-only
----

.2016-11-26:

Move old versions of `case` to an <old> directory.

.2016-05-07:

Idea: Rename `branch`, `0branch` and `?branch` to `(branch)`, `(0branch)` and
`(?branch)`.  Then write `branch`, `0branch` and `?branch` to compile them, as
control structures.

----
: branch  ( a -- )  postpone (branch) ,  ; immediate compile-only
: ?branch  ( a -- )  postpone (?branch) ,  ; immediate compile-only
: 0branch  ( a -- )  postpone (0branch) ,  ; immediate compile-only
----

Also `-branch`, in the library.

.2015-11-14:

Forth Dimensions v06n1p26: `it endit` control structure.

.2015-10-25:

Ideas from cmForth:

____

LOOP         Test the top item on the return stack.  If it is zero,
pop it off the return stack and continue executing the next
instruction. If it is not zero, decrement it and jump to the address
specified in this instruction.  Address specifier is the same as in
BRANCH.  LOOP is compiled by NEXT.

REPEATS      Repeat the next instruction if the count on top of the
return stack is not zero.  The count is also decremented.  If count is
zero, pop the return stack and continue executing the following
instruction.  REPEATS is  compiled by        TIMES or OF(.

The REPEATS instruction is used frequently to implement complicated
math operations, like shifts, multiply, divide and square root, from
appropriate math step instructions.  It is also useful in repeating
auto-indexing memory instructions.

____

// Data structures {{{1
== Data structures ==

.2017-01-18:

Write far-memory versions of `avalue`, `2avalue` and `cavalue`.

// Strings {{{2
=== Strings ===

.2017-01-07:

Rename `char>string` or write after `c>bstring`, which
does the same but in `pad`.

.2016-12-29:

NOTE: Milestone: 0.14.0

Move the circular string buffer right below `limit`. This way the application
can move it without wasting its original space.

.2016-12-23:

Document `s\"` and `.\"`.

.2016-12-16:

Remove bounds checking from `}` (Noble's arrays)
and keep a copy of it as `?}`, for debugging.

.2016-12-07:

Choose a clear convention for suffixes ">str" and ">string". Depending on the
location of the string (circular string buffer, `pad` or another temporary
area)? Another option: "stringer" (after renaming the circular string buffer,
as planned).

`X>string` :: string in the circular string buffer
`X>stringer` :: string in the circular string buffer
`X>bstring` :: binary string in the circular string buffer
`X>bstringer` :: binary string in the circular string buffer
`X>#str` :: temporary string in the pictured numeric string buffer
`X>padstr` :: temporary string in `pad`
`X>bpadstr` :: temporary binary string in `pad`
`X>padbstr` :: temporary binary string in `pad`
`X>padzone` :: temporary binary string in `pad`

.2016-11-26:

Compact <strings.replaces.fsb>.

.2016-11-19:

Study the strings stack included in Spectrum Forth-83
(file <objects>).

.2016-05-11:

Compact <strings.MISC.fsb>.

.2015-09-12:

Implement a configurable case mode for `search` and `compare`? See how
Z88 CamelForth does it. Also DX-Forth has this feature.

.2015-07-23:

New: `lower` and `lowers`.

.2016-06-10:

NOTE: Milestone: 0.14.0

Rename "csb" to "stringer":

|===
| Now         | "stringer"

| >csb        | >stringer
| ?csb        | ?stringer
| csb-size    | /stringer
| csb0        | stringer
| empty-csb   | empty-stringer
| unused-csb  | unused-stringer
|===

// Local variables {{{2
=== Local variables ===

Examples from Forth Dimensions:

|===
| Title                                    | Vo  | N  | Pag | Note

| Turning the Stack into Local Variables   | 03  | 6  | 185 | Implemented: locals.arguments.fsb
| Anonymous Variables                      | 06  | 1  | 033 | Implemented: locals.anon.fsb
| Local Definitions                        | 06  | 6  | 016 | :( `privatize` is simpler
| Letter "Stack Your Locals"               | 07  | 5  | 005 | :( modification of Vo06N6
| Local Variables                          | 09  | 4  | 009 | :( complete but complex, and not recursive
| Letters "Local Variables"                | 09  | 5  | 005 | Implemented: locals.local.fsb
| Letters "Code for Local Variables"       | 10  | 1  | 006 | Modification for FD Vo09N4
| Headless Local Variables and Constants   | 10  | 1  | 019 | Interesting, but for F83
| Letters "Local Variables Revisited"      | 10  | 5  | 005 |
| Local Variables and Arguments            | 11  | 1  | 013 | Seen
| Local Variables - Another Technique      | 11  | 1  | 018 | Seen
| Prefix Frame Operators                   | 11  | 1  | 023 |
|===

// User variables {{{2
=== User variables ===

.2016-11-18:

Rename `(user)` to `user`? That was the original name in fig-Forth, Forth-79
and Forth-83. Choose an alternative for the current `user`, defined in the
library.

// Other {{{2
== Other ==

.2016-12-30:

Add `aconstant`, an array of constants, after `avalue` and `avariable`.

// Documentation {{{1
== Documentation ==

.2016-11-26:

Change to title case the word sets of Forth-79 and Forth-83.

.2016-11-21:

Change _n_ to _u_ for blocks and block lines. Consult the notation used in
Forth-2012.

.2016-08-09:

Change the format of stack notation:

----
xn..x1 --> x[n] ... x[1] 
       --> x[n]..x[1] 
----

.2016-10-24:

Common notation for:

- text coordinates: "col row" --> "x y"?
- graphic coordinates: "x y" --> "gx gy"?

.2016-06-01:

Change the stack notation back to classic Forth?:

- xt -> cfa
- nt -> nfa
- pfa
- lfa

And change also:

- xtp -> cfaa

The problem with the standard notation is it does not has alternatives to pfa
and lfa, because they are system dependent and may not exist in all systems.
This make the notations xt, nt, pfa, lfa look heterogeneous. Beside, xt and nt
are abstract terms, while cfa and nfa are precise definitions for the
implemention.

.2016-06-01:

Put the "Origin" section of the glossary entries at the end of each entry.

.2016-05-11:

Homogenize the stack notation for character/bytes: only _c_.

.2016-04-29:

Homogenize the stack notation for blocks and block lines.

.2016-04-28:

Homogenize the notation "Run-time" to "Execution".

.2016-04-11:

Homogenize the following stack notations:

- double, triple and quadruple numbers (or include all used
  conventions in the documentation).

.2015-07-23:

Adapt the markups of Z88 CamelForth to extract the glossary from the
source.

// DOS {{{1
== DOS ==

// G+DOS {{{2
=== G+DOS ===

.2017-01-05:

Simplify `!dos,`, `c!dos` and family.

.2017-01-05:

Try `plusd-in,` instead of `patch hook,`.

.2015-08-31:

Problem: SZX snapshots don't preserve the mounted disks or G+DOS!

The Plus D own snapshots can be used, but this means programs have to
be started manually, typing `run` in BASIC to load G+DOS, and then
loading the snapshot file from BASIC or an Autoload file.

.2015-08-31:

Fix: `transfer-block` changes the current drive to 2!

.2015-07-23:

Study how to save and load the main code and the name bank apart, in
two files. This way `turnkey` could be used also to save a modified
copy of the system, not just Forth programs. Simpler solution: use the
snapshop option of the Plus D, or save a snapshot from the emulator.

.2016-03-16:

Investigate how to use the free memory of the Plus D RAM.

// +3DOS {{{2
=== +3DOS ===

.2016-08-14:

`set-drive`, `open-disk` and `close-file` work on drive "a".  But when drive
"b" is used, `close-file` returns ior -1006 (unrecognised disk format). This
is a problem of fsb2's fb2dsk.

// TR-DOS {{{2
=== TR-DOS ===

.2016-12-27:

The games disk needs 648 KiB, it does not fit the 636 KiB usable in a TR-DOS
disk.

.2016-09-01:

`read-mode 0 22528 1 transfer-sectors` works after but `read-mode 80 22528 1
transfer-sectors` hangs. `0 set-drive` or `1 set-drive` makes no difference.

.2016-08-11:

Make also 40S, 40D and 80S TRD disk images?

.2016-08-11:

Investigate if TR-DOS uses the IX register. If not, remove the restorings.

// Errors {{{1
== Errors ==

.2016-11-27:

Rename?:

- `warn.throw` to `error-code-warn`
- `warn-throw` to `error-warn`
- `warn.message` to `message-warn`

.2016-11-25:

Rename exception messages "required" to "needed" in comments of modules.
Already done in the error messages module.

.2016-04-25:

Idea: Add `where` to the default exception message. In order to save space,
`where` should be in the library and patch itself into the default message.

.2015-09-20:

Idea:
____

The correlation between DX-Forth exception code and DOS error code
is given below:

 Exception   DOS
     0        0     no error
   -511       1     function number invalid (not used)
   -510       2     file not found
   -509       3     path not found
   -508       4     too many open files
   -507       5     access denied
   -506       6     invalid handle
    ...     ...
   -257     255     unspecified error

Note: To convert an exception code in the range -257 to -511 to its
corresponding DOS error code, use: 255 AND
____

.2015-10-18:

`.warning`

// Files {{{1
== Files ==

.2016-04-11:

Make the tape words return a standard _ior_.

Rename the tape and disk words after a common convention. Maybe after
Gforth `slurp-file` and Galope `unslurpe-file`: `slurp-tape-file`,
`unslurp-tape-file`, `slurp-file`, `unslurp-file`.

.2016-03-02:

Adapt all file words to standard _ior_; remove _f n_.

2016-04-09: already done?

.2015-09-18:

New: `.files` (from Pygmy Forth).

// Games {{{1
== Games ==

.2016-12-27, 2017-01-13:

Extract the games, make them independent projects?

.2016-05-13, 2017-01-13:

Convert the sample games to .fs.  and load them with `load-app`.  This will
save several blocks of source.

// Graphics {{{1
== Graphics ==

.2017-01-13:

Rename `attr` to `get-attr` or similar. Write its corresponding `set-attr  ( b
col row -- )`.

Maybe `xy-attr@` and `xy-attr!` or
`xy-color@` and `xy-color!`,
depending on the final naming convention about "color/attr".

.2017-01-13:

Improve `ocr`: Return a flag apart from the code, in order to make it possible
to recognize character zero:
  
----
  \ ocr  ( col row -- c true | false )
----

Or write a variant:

----
  \ ocr?  ( col row -- c true | false )
----

.2017-01-09, 2017-01-12, 2017-01-13:

- Rename `color!` and family to `temp-attr!` or `t-attr!`...?
- Rename `permcolor!` and family to `perm-attr!` or `p-attr!`...?
- Rename `permament-colors` to `permanent-attrs` or `temp>perm-attrs` or
  `t>p-attrs` or `temp-attr>perm` or `t-attr>p-attr`...?

"color" is more readable. It can be used to name an 8-bit color attribute:

- `temp-color@`, `perm-color@`
- `temp-color!`, `perm-color!`
- `temp>perm-colors`
- `xy-color@`, `xy-color!`
- `temp-color-mask@`, `perm-color-mask@`
- `temp-color-mask!`, `perm-color-mask!`

.2017-01-09:

Simplify the management of UDG: Use only the 0-index words, and make an
optional layer to use 128-index codes, to make conversion of BASIC programs
easier.

Problem: general print words must use 128..255 codes for the first 128 UDGs.

.2017-01-09:

Add `.udg"` as a fast way to print strings of UDG (0..255).

.2017-01-09:

Finish `udg-block[`.

.2016-12-26:

Factor `adraw176` to write `aline176`, which uses `set-pixel` and is faster.
Write a similar alternative to `rdraw`, `rline`.

.2016-12-02:

Use constants for bitmasks and "unbitmasks" in <printing.color.fsb>.

.2016-12-02:

Rewrite in Z80 the low-level words of <printing.color.fsb>.

.2016-12-02:

Factor `inverse` to `inverse-on` and `inverse-off`.

Factor `overprint` to `overprint-on` and `overprint-off`.

.2015-09-01:

Possible names for text and graphic cursor words.

|===
| set txt pos| get txt pos| set graph pos   | get graph pos   | graph home

| at         | at@        | at-pixel        | at-pixel@       | home-pixel
| at         | at@        | gat             | gat@            | ghome
| at         | at@        | graphic-at      | graphic-at@     | graphic-home
| at         | at@        | xy-at           | xy-at@          | xy-home
| at-xy      | ?at        | gat-xy          | ?gat            | ghome
| at-xy      | at-xy@     | gat-xy          | gat-xy@         | ghome
| at-xy      | xy         | at-coord        | coord           | coord-home
| at-xy      | xy         | at-coord        | coord           | home-coord
| at-xy      | xy         | at-coords       | coords          | coords-home
| at-xy      | xy         | at-coords       | coords          | home-coords
| at-xy      | xy         | at-g-xy         | g-xy            | g-home
| at-xy      | xy         | at-gxy          | gxy             | ghome
| at-xy      | xy@        | at-coords       | coords@         | home-coords
| at-xy      | xy@        | at-gxy          | gxy@            | ghome
| at-xy      | xy@        | gat-xy          | gxy@            | ghome
| cursor!    | cursor@    | gcursor!        | gcursor@        | ghome
| cursor!    | cursor@    | graph-cursor!   | graph-cursor@   | graph-home
| cursor!    | cursor@    | graphic-cursor! | graphic-cursor@ | graphic-home
| cursor!    | cursor@    | xy!             | xy@             | xy-home
| cursor!    | cursor@    | xy-cursor!      | xy-cursor@      | xy-home
| set-cursor | get-cursor | set-coords      | get-coords      | home-coords
| set-cursor | get-cursor | set-xy          | get-xy          | home-xy
| set-xy     | get-xy     | set-gxy         | get-gxy         | ghome
|===

So far (2016-04-23) the best are:

|===
| set txt pos| get txt pos| set graph pos   | get graph pos   | graph home

| at-xy      | xy         | at-coord        | coord           | coord-home
| at-xy      | xy         | at-coord        | coord           | home-coord
| at-xy      | xy         | at-coords       | coords          | coords-home
| at-xy      | xy         | at-coords       | coords          | home-coords
| at-xy      | xy         | at-gxy          | gxy             | ghome
| at-xy      | xy         | at-g-xy         | g-xy            | g-home
|===

.2015-09-05:

Name for graphic fill: `flood`.

// Keyboard {{{1
== Keyboard ==

.2016-12-26:

Remove `discard-key`? It does exactly the same as `key drop`, but faster, and
it uses only two bytes of data space (for `push ix`).

.2016-12-26:

Test `break?`.

.2016-11-25:

`akey` for `accept`, after SwiftForth.

.2015-06-30:

New: command history, stored in the names bank.

.2015-06-07:

Change: move key to the blocks, as `mode-key` or similar, and use a
simpler `key` (`akey` from Afera).

.2015-06-30:

Change: modify `expect` after Spectrum Forth-83.

// Kernel {{{1
== Kernel ==

.2016-10-27:

Use `_jump` macros at the end of `umax`, `umin`, `dabs`, `abs`, etc.

.2016-04-24:

Words that can be moved to the library: `catch`, `?\`,
`[defined]`, `[undefined]`, `umin`, `umax`...

Study how to move `line>string` and `undefined?` to the library.  They are not
used in the kernel, but they are needed by the `need` utility.

.2016-05-06:

Remove the routine `compare_de_hl_signed`, if possible.

// Makefile {{{1
== Makefile ==

.2016-04-16:

Fix Makefile: The loader and the main disk are built also when the sources
have not changed.

.Update 2016-11-15:

The problem is the rules of the BASIC loader. They run also when their
prerequisites are older than the target.

// Maths {{{1
== Maths ==

.2016-12-30:

NOTE: Milestone: 0.13.0

Rewrite `du<` in Z80.

.2016-12-30:

NOTE: Milestone: 0.13.0

Make both versions of `lshift` and `rshift` accessible, or remove them.

.2016-12-30:

NOTE: Milestone: 0.13.0

Remove module <math.number.prefix.fsb>.

.2016-12-28:

----
: ?ifelse  ( x1 x2 f -- x1 | x2 )  if  drop  else  nip  then  ;
: ifelse  ( x1 x2 f -- x1 | x2 )  rot ?ifelse  ;
: ?dup  ( x1 f -- x1 | )  if  dup  then  ;
: ?nip  ( x1 x2 f -- x1 x2 | x2 )  if  nip  then  ;
----

.2016-12-27:

Add `binary` to the library.  If `base` were not a user variable, `binary` and
`decimal` would be smaller in Z80 than in Forth.

.2016-12-22:

NOTE: Milestone: 0.13.0

Rewrite `odd?` and `even?` in Z80.

.2016-11-26:

Remove old z80-asm versions of `d2*` and `d2/`.
Search for similar cases.

.2016-11-26:

NOTE: Milestone: 0.13.0

Rewrite `d-` with Z80 opcodes, without `z80-asm`.
Search for similar cases.

.2015-07-23:

Idea: 2 more bytes for `base`, to be used as save-restore space.

----
  : switch  ( a1 -- )  dup cell+ exchange  ;
    \ Exchange the 16-bit contents of a1 and the following cell.

  \ Example:

  base switch hex

  base switch
----


.2015-09-12:

....

ROTATE         n1 n2 -- n3

     Rotate  the value n1 left n2 bits if n2 is positive, right  n2
     bits  if n2 is negative.  Bits shifted out of one end  of  the
     cell are shifted back in at the opposite end.

  \ Standard: Forth-79 (Reference Word Set); Forth-83 (Appendix
  \ B.  Uncontrolled Reference Words).
....

.2016-05-31:

The idiom `-1 =` is used 3 times in the kernel. It could be defined this way:

----
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  ld a,$FF
  cp h
  jp nz,false_
  cp l
  jp nz,false_
  jp true_

  ; 14 B
----

Or:

----
  _code_header rminus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  ld a,$FF
  cp h
  jr nz,false_
  cp l
  jr nz,false_
  jr true_

  ; 11 B
----

And an alias `true=` could be defined.

6 bytes would be saved in the kernel thanks to any of these definitions, but
they need 14 or 11 bytes...

More options (2016-08-05):

----
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  inc h
  inc l
  ld a,h
  or l
  jp nz,false_
  jp true_

  ; 11 B
----

----
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  inc h
  inc l
  ld a,h
  or l
  jr nz,false_
  jr true_

  ; 09 B
----

.2016-05-07:

Implement 2-cell operators from Spectrum Forth-83. Most of them are written in
Z80.

.2016-05-01:

Change the order of the parameters of `%` and `u%`, after _Starting Forth_ pp
103..105.

.2016-04-27:

Adapt `d>q`, `q>d`, `s>q`, `q+`, `q-`, `udm*` from Pygmy, in module
"math.operators.4-cell.fsb".

.2016-04-18:

Modify `interpret` to be patched by a floating-point implementation in order
to recognize floating-point numbers.

Make `number?` deferred, in order to add floating-point support.

.2016-04-17:

`factorial`, from Forth-2012 documentation: examples in `recurse` and
`repeat`.

.2015-12-24:

Fractional arithmetic, Forth Dimensions volume 4-1.

.2016-03-16:

Idea to improve `number?`, or to write an optional alternative: Return the
chars and positions of every point, not only the last one. Convert `dpl` to a
backwards compatible array:

----
+0 cell: position of the last point
+2 byte: last point
+3 cell: position of the last but one point
+5 byte: last but one point
etc.
----

A new variable `#dpl` would hold the number of points.

// Floating point {{{2
=== Floating point ===

.2016-04-22:

Document floating point.

.2016-04-22:

Idea: Use the ROM calculator memories (0..5) as floating-point non-recursive
locals. Problem: some calculator's words use them (eg. `over`).  They could be
recursive, because their address can be changed with the system variable MEM;
they could be pointed to a frame in the return stack.

Simpler idea: use the calculator memories them as is, as temporary storage.
The ROM allocates 6*5 bytes, but 32*5 can be used.

.2016-04-19:

Floating-point words `flit`, `fliteral`. From PFE: `fround>s`, `ftrunc>s`
(being `f>s` a synonym), `1/f`, `f^2`, `f^n`, `f2/`, `f2*`.

// Memory {{{1
== Memory ==

.2016-11-15:

Write far-memory versions of some of the following words from the
<memory.MISC.fsb> module:

----
  \ -!
  \ /! *! 2/! 2*!
  \ bit>mask bit? set-bit reset-bit
  \ c1+! c1-! 1+! 1-!
  \ c@and ctoggle
  \ exchange reserve alloted
  \ n, nn, n@ nn@ n! nn!
----

.2016-11-13:

Remove `get-default-bank` and `set-default-bank`.

.2016-10-28:

Remove the old `alias!` when the extra-memory system becomes definitive.

Remove `s!` and related words when the extra-memory system becomes definitive.

// Misc {{{1
== Misc ==

.2016-05-18:

Factor `new-needed-word  2dup undefined?`.

.2016-04-16:

Write `behead  ( "name" -- )`. DX-Forth uses `behead ( "name1" "name2" -- )`.
`hided  ( nt -- )` is already in the kernel.

.2016-11-12:

Ideas from
http://www.bedroomlan.org/hardware/cft/book/forth-programming-d2-reference[CFT
Forth]:

....

BASE>R

R>BASE

#CONTEXT ( -- a ) (numCONTEXT) The number of entries in the vocabulary stack.

#WORDS ( -- n ) (countwords) Returns the number of words in the CURRENT
vocabulary.

!BITS ( 16b1 addr 16b2 -- ) (store-BITS) Store the value of 16b1 masked by
16b2 into the equivalent masked part of the contents of addr, without
affecting bits outside the mask.

+FLAG! ( u a -- ) (set-FLAG-store) The value at address a is ORred with u
in-place.

-FLAG! ( u a -- ) (clear-FLAG-store) The value at address a is ANDed with (NOT
u) in-place.

.BANKS ( -- ) (dot-BANKS) Prints out the current memory banking scheme.

.BASE ( -- ) (dot-BASE) Prints out the base.

.DATE ( -- ) (dot-DATE) Read and print out the date from the the real-time clock.

.TIME ( -- ) (dot-TIME) Read and print out the time from the the real-time
clock.

.rs ( -- ) (dot-rs) Prints out the return stack non-destructively.

16* ( w -- w ) (16mul) Shift left four bits.

16/ ( u -- u ) (16div) Shift right four bits (one nybble). No sign extension.

1MS ( -- ) Delay for approximately 1 millisecond.

256* ( w -- w ) (256mul) Shift left eight bits.

256/ ( w -- w ) (256div) Shift right eight bits.

>FLAGS ( a -- u ) (to-FLAGS-fetch) Given the PFA of a word, return its ﬂags.

>LINK@ ( a -- a | f ) (to-LINK-fetch) Given the PFA of a word, return the head address of the word preceding it in the vocabulary. If this is the first word in the vocabulary, false (zero) is returned.

CONTEXT@ ( u -- a ) (CONTEXT-fetch) Get the u-th (from the top) entry in the
vocabulary stack. The value returned is the address of a variable holding the
address of the last entry in that dictionary. It’s also the PFA of the
vocabulary word.

....

.2015-06-10:

Adapt this word from Spectrum Forth-83, which uses it in `cold` and
`query`:

----
  : TERMINAL ( --- )
    LIT PKEY (KEY) !    \ Set default handler for KEY.
    >S ;                \ And initialize screen output.
----

.2015-09-22:

`console` to do `display` and init the keyboard and `tib` (see
Spectrum Forth-83).

// Multitasking {{{1
== Multitasking ==

.2017-01-19:

Study the way v.Forth manages the interrupts and adapt it.

// Library {{{1
== Library ==

.2017-01-02:

Move all tests to the tests module.

.2017-01-02:

NOTE: Milestone 0.13.0

Rename <modules> directories to <addons>, to avoid confusion with
library modules.

.2017-01-02:

NOTE: Milestone 0.13.0

Compact the `g-emit` module.

.2016-12-30:

NOTE: Milestone 0.13.0

Make words in <printing.color.fsb> accessible to `need`.

.2016-12-30:

NOTE: Milestone 0.15.0

Make it possible to use any number of disks, in any order, for the library.
This way, the main library could be only on its own disk, not copied to all the
disks.

`lib-order`, `set-lib-order`, `get-lib-order` are in the kernel, but no used
yet.

.2016-12-08:

Rename <math.number.print.fsb> to <printing.number.fsb>.

// Loading {{{1
== Loading ==

.2017-01-06:

Improve `load-app`: save and restore the source, in order to continue loading
after `load-app`. This ways, several programs can be loaded this way.
Also, rename it to `load-program`.

.2016-12-30:

Add `//` to ignore the rest of the source, as a shorter alternative to `exit`
to exit the current block.

.2016-12-29:

`(located)  ( ca len -- block | false )` returns _false_ also when _ca len_ is
empty, therefore the exception code thrown by the calling word is always #-268
(needed but not located).  This is not a big problem, but exceptions #-16
(attempt to use zero-length string as a name) or #-32 (invalid name argument)
would be clearer.

.2016-12-03:

Make `need-here` unnecessary: Always check the current block, just in case.
Many needed words are in the same block.

.2016-11-22:

Write `needs` to do multiple `need` on one line of a block,
saving space

----
needs word1 word2 word3 word4
needs word5 word6 word7 word8
----

Or `need( )` to do the same without the one-line limit:

----
need( word1 word2 word3 word4
      word5 word6 word7 word8 )
----

----
: need(  ( "name#1" ... "name#n" "<paren>" -- )
  begin  parse-name 2dup s" )" str= 0=
  while  needed  repeat  2drop  ;
----

Update 2016-12-31: `need\` is clearer than `needs` to parse the current line.

.2016-11-19, 2016-12-29:

NOTE: Milestone: 0.15.0

Finish the alternative version of `indexer` to index the blocks on the fly as
they are being searched by `need` and family, i.e., not in advance.

.2016-05-18:

Improve `need` to make several index lines possible, by making `(` executable:

----
( very-long-word-1 very-long-word-2 very-long-word-3
very-long-word-4 very-long-word-5 very-long-word-6 )
----

Problem: this would force changes in fsb and fsb2.

// Modules {{{1
== Modules

.2017-01-05:

`>>link far!` is used in `forget-transient`, but it's what `unlink-internal`
does. Factor and reuse.

.2016-12-29:

Improve `transient` to actually unlink all the transient words?  This means
backuping and restoring the latest definition of all word lists...

.2016-12-07:

....
Newsgroups: comp.lang.forth
Date: Wed, 3 Aug 2016 01:18:18 -0700 (PDT)
In-Reply-To: <0a8d7b8a-8367-4e92-a482-ee8b6728325a@googlegroups.com>
Message-ID: <c5aa8e30-1dee-4d64-9022-e24f46b20437@googlegroups.com>
Subject: Re: Code management with wordlists
From: hheinrich.hohl ...
....

Excising

This method was used in LMI PC/FORTH and UR/FORTH.

EXCISE <word1> <word5>

This command hides the headers of <word1> through <word5> 
by excising their headers from the linked list in the dictionary.

Together with the ability to create binary overlays, the LMI FORTH compilers
enabled the user to create modules that showed only words that are relevant
for the end user.

.2016-12-07:

NOTE: Milestone: 0.13.0

Combine `begin-module` and `package`.

// Names {{{1
== Names ==

.2017-01-18:

Change "screen" and "scr" to "block", e.g. in `list` and `where`.

.2017-01-17:

Rename old "rec" to "sectors", for example in `rec/blk`.

.2017-01-05:

Use parens after a convention: `(name)` for words not useful for the
user, not accessible in the library; `(name` for internal words that
may be useful for the user and are accessible in the library. Beside,
this avoids the need to use backslash-delimited index block lines in
the library.

.2017-01-02:

Improve definition names in the `ocr` module: Use "font" instead of
"charset".

.2016-12-31:

Rename all paren words to use only the opening paren? This would make the
block index line backslash notation unnecesary.

// Optimizations {{{1
== Optimizations ==

.2016-12-30:

NOTE: Milestone: 0.13.0

Convert `'x' emit` to `." x"`. It saves one byte and is faster.

// Parsing {{{1
== Parsing ==

.2016-05-13:

Improve `?(` with `refill`, to cross block boundaries?
This would be needed  for `load-app`. Maybe two versions:
if `load-app` has been compiled, then compile the improved version of `?(`.

.2016-06-01:

When loading an app with `load-app`, make `(` behave like in the
Forth-2012 FILE word set.

.2015-10-15:

NOTE: Milestone: 0.13.0

Adapt from Gforth: `noname`, analogous to `nextname`.

// Printing {{{1
== Printing ==

.2017-01-18:

Current versions of `type-right` and `type-center` use
spaces, which create a banner of the current colors.

Write alternative versions that move the cursor position instead.

.2017-01-02:

Adapt the banked screen mode, which uses the unfinsihed implementation
of a code bank for addons, to far memory or remove it.

.2016-12-30:

Combine `clear-block` and family with the text windows.

.2016-12-24:

Windows:

- Scroll support, with configurable pause.
- Rewrite `wcls` in Z80.
- Save and restore windows, in Z80.

.2016-12-20:

Move `.0000` and `.00` from the time module to the printing module, and factor
them for double numbers.

.2016-11-26:

NOTE: Milestone: 0.13.0

Make `type-ascii` configurable: store the common char in a character variable.
In fact, it would be enough to write `emit-ascii`, because `emit` is deferred,
and use `type`.

Make `type` deferred, to be configured as `fartype` or other when needed.

.2016-11-21:

Add support for more control characters to alternative version of `mode64`.

.2016-11-21:

In mode 32, one `cr` does nothing when the cursor is at the end of a line.
That is the default behaviour in Sinclair BASIC. The driver of `mode42` works
the same way.  But the driver of `mode64` always prints the carriage return,
increasing the line number. Somehow the behaviour must be unified in all
modes. The behaviour of `mode64` seems more logical.

.2016-10-28:

NOTE: Milestone: 0.13.0

Simplify `u.r`.

.2016-08-11:

Remove the 64 cpl font from the library (4 blocks), and use the binary file
(336 bytes) instead? Or provide the file as an alternative.

.2015-09-05:

There's an example how to change and restore a channel in print-42, by
Ricardo Serral Wigge. Beside, it supports many (all?) control
characters, unlike the implementation by Andy Jenkinson.

.2015-09-11:

Idea: screen modes table?

- 0: 32 cpl original (ROM routines)
- 1: 32 cpl improved (bold, italic).
- 3: 36 cpl
- 4: 42 cpl
- 5: 51 cpl
- 6: 64 cpl

It seems more versatile to create one word to select every mode and provide a
common user interface to row, column, cpl, window...

.2016-10-27:

Add `vemits`, inspired by TI BASIC's `call vchar()`.

.2016-04-17:

Improve tab control.

// Stacks {{{1
== Stacks ==

.2017-01-07:

Notes about nested `need`:

Each nested `need` uses 14 cells of the return stack: `nest-source` uses 6
cells for data, `need` uses 2 cells for the string, the rest must be used for
calls.

.2016-12-30:

Improve needing of `xstack` words.

// Sound {{{1
== Sound ==

.2017-01-19:

Use `>bleep` to write a table of notes for `bleep`.

.2016-10-10:

Finish the conversion of 128K sound explosions. More details in the source.

// Time {{{1
== Time ==

.2016-12-20:

Use `chars` in offsets of `get-date` and `set-date`.

.2016-12-20:

Fix `pause`.

.2015-12-14:

Update the date with interrupts.

.2016-11-18:

Rename `frames@` to `ticks@`, etc.?

2016-11-19: `utime`? `cputime`? (See Gforth)

// Tools {{{1
== Tools ==

.2017-01-06:

Study the editor of Pygmy Forth.

.2016-11-28:

Improve `see`: decode `does>`.

.2016-11-26:

Rename `.unused` to `.free`.

.2016-11-25:

NOTE: Milestone: 0.13.0

Write `ed:` after TurboForth.

.2016-11-19:

Make `editor` defered, in order to load more than one editor at the same time.

// User variables {{{1
== User variables ==

.2016-11-27:

Update the user variables that are initialized (`warnings` has been removed,
but its place is used by `lastblk`, which does not need initialization).

.2015-09-13:

NOTE: Milestone: 0.13.0

`rp` should be a user variable.

.2015-06-30:

Change: compare the user variables with those of Spectrum Forth-83.


