= Solo Forth TO-DO
:author: Marcos Cruz (programandala.net)
:revdate: 2017-02-17

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

// Assembler {{{1
== Assembler ==

.2017-02-16:

Try `;code`. Its definition should include `asm`.

.2017-02-12:

NOTE: Milestone: 0.14.0

Make the absolute-jump flow structures optional.

.2017-02-12:

NOTE: Milestone: 0.14.0

Deprecate `unresolved`. Use labels instead. Adapt the words that still
use it.

.2017-01-26:

Homogenize the notation of assembly comments in the library: use the
same code that would be used in the kernel. Example: the `_jp_pushhl`
macro for `jppushhl,`, not `jp push_hl`.

.2017-01-13:

Modify words that restore IX: use the current contents of `next` instead of its
default value. This way the value of IX can be changed to implement a debugger
or multitasking.

.2017-01-13, 2017-02-16:

Rename `end-code` to `;c`?  `end-code` is more legible, but space is
precious in blocks.  `end-code` is not in Forth-94 or Forth-2012 (only
mentioned), but it was in Forth-79 and Forth-83, and it's in Gforth.

.2016-11-26, 2016-12-30..2017-01-02:

NOTE: Milestone: 0.14.0

Rewrite all small code words in Z80 opcodes, without assembler.
1xamples: `lshift`, `(g-emit)` and family, `f!`, `f@`, `fast-rnd`,
`get-drive`, `set-drive`, `crnd`, `(delete-file)`, `n>r`, `nr>`,
`d-`, `@dos`, `c@dos`...

// Benchmarks {{{1
== Benchmarks ==

NOTE: Milestone: 0.14.0

- Benchmark current `times` and new version that keeps the xt in the return
  stack in the loop: `do dup r> execute r> loop drop`.
- Benchmark two library versions of `m*/`.
- Benchmark two library versions of `d=` and `d<>`.

// Bugs {{{1
== Bugs ==

.2017-02-11:

Fix: Crash when loading `mode64` or `mode42`. It seems a return stack
problem.

.2017-01-11, 2017-01-24, 2017-01-25:

`view` gets trapped in `wait-for-key` at the end, why?

It happens when `view` is used on its own, but not when used right
after being loaded, example `need view view see`.

Update: It has nothing to do with `view`. The same happened after an
error #-268. Somehow the flag of the last key pressed is not updated
by the OS and the code is trapped in a loop. An emulator issue?

.2017-01-04:

Check some of the RNG benchs.  The machine resets at the end of some
of them. They are marked in the source.

// Code style {{{1
== Code style ==

.2017-02-13:

Align comments of the kernel.

.2017-01-06, 2017-02-13:

Change the code style after Pygmy Forth:

- Remove the last space in paren comment.
- Use only one space before and after paren comments.
- Use a single dash in stack comments.

Also:

- Use a single space before `;`, `end-code`, `end-asm`, `endm`.
- Use a single space after `?(`.

All this will make the code more compact, saving a handful of blocks.
Many times a word does not fit a block line because of the current
convention.

// Interpreter/compiler {{{1
== Interpreter/compiler ==

.2017-01-23:

Rewrite `here` in Z80. `dp` must be an ordinary variable first.

.2017-01-05, 2017-01-23:

Rewrite `there` in Z80 (`dp` must be an ordinary variable first) or remove it?

.2016-12-03:

Use a new kind of unconditional high-level branch at the end of `nest-source`
and `unnest-source`:

----
goto  ( a -- )
----

Make it consistent with the planned changes in the current low-level branches.

.2016-11-20:

Add `fast` and `slow`, after ACE Forth, to deactivate/activate some checks:
`?stacks`, `limit` and `farlimit` (not used yet), etc.

.2016-05-17:

Improve the search order words, after Forth-2012.

.2016-04-27:

Rewrite `'` after Gforth. See Gforth's `(')`, `name?int`,
`name>int`, etc. Factor `defined` and `comp'` accordingly.

.2016-05-18:

Remove the `root` word list. Set the minimum search order to `forth`.

.2016-11-13:

Make `dp` an ordinary variable? Then `here`, `there` and `allot` could be
improved, rewritten in Z80.

.2016-05-15:

Check if `current-latest`, used in the library, can be replaced with `latest`.

.2016-05-09:

Idea: in DX-Forth, `last` is a 2-cell variable that holds both the nt and the
xt: `last @ ( nt )` and `last 2@ ( xt nt )`.

.2016-04-29:

Factor the return stack manipulation done by `(.")` in order to
reuse it in `(abort")` and `(warning")`. Use a variant of pForth's `param`.

.2016-04-28:

Finish the implementation of control stack words.

.2016-04-21:

Make `jp pushhlde` a macro dependent of `size_optimization`: compile `jp
pushhlde` or `push de / push hl / jp (ix)`. The second option needs one more
byte but is 2 T-cycles faster.

.2015-11-12:

`+bal`, `-bal` or similar, to change `csp`:

----
: [+csp]  ( -- )  [ cell negate ] literal csp +!  ; immediate compile-only
: [-csp]  ( -- )  cell csp +!  ; immediate compile-only
----

But to compile an external number inside a definition,
a trick is `[ dup ] literal` and a `drop` after `;`.

.2015-06-09:

In order to save compilation time, move inner words to the bottom of
the dictionary. Example: `(loop)`, `clit`, `back`, `digit`...

.2016-03-19:

Separate header flags from the length byte of the name field.  This way more
bits will fit (alias, deferred, special behaviour), and word names will be
actual strings.

// Control structures {{{1
== Control structures ==

.2016-12-26:

Add default execution token to `switch:`.

.2016-12-20:

Document the variants of `of`.

.2016-12-07:

Use `>bstring` (new name for `>cell-string`), `2>bstring`, `c>bstring`
(already exists as `char>string`).
 
.2016-11-26, 2017-01-23:

Change `??` to its old version, which is more useful:

----
  \ XXX TODO -- 2016-11-26: It seems more useful the old
  \ version, extended as the rest of alternative conditionals:
  \
  \ : ??   ( f -- )   0= if  r> cell+ >r  then  ; compile-only
  \ : 0??  ( f -- )      if  r> cell+ >r  then  ; compile-only
  \ : -??  ( f -- )  0>= if  r> cell+ >r  then  ; compile-only
  \ : +??  ( f -- )   0< if  r> cell+ >r  then  ; compile-only
----

Alternative:

----
  \ : ??   ( f -- )     0exit  r> cell+ >r  ; compile-only
  \ : 0??  ( f -- )     ?exit  r> cell+ >r  ; compile-only
  \ : -??  ( f -- )  0> ?exit  r> cell+ >r  ; compile-only
  \ : +??  ( f -- )  0< ?exit  r> cell+ >r  ; compile-only
----

.2016-11-26:

Move old versions of `case` to an <old> directory.

.2016-05-07:

Idea: Rename `branch`, `0branch` and `?branch` to `(branch)`, `(0branch)` and
`(?branch)`.  Then write `branch`, `0branch` and `?branch` to compile them, as
control structures.

----
: branch  ( a -- )  postpone (branch) ,  ; immediate compile-only
: ?branch  ( a -- )  postpone (?branch) ,  ; immediate compile-only
: 0branch  ( a -- )  postpone (0branch) ,  ; immediate compile-only
----

Also `-branch`, in the library.

.2015-11-14:

Forth Dimensions v06n1p26: `it endit` control structure.

.2015-10-25:

Ideas from cmForth:

____

LOOP         Test the top item on the return stack.  If it is zero,
pop it off the return stack and continue executing the next
instruction. If it is not zero, decrement it and jump to the address
specified in this instruction.  Address specifier is the same as in
BRANCH.  LOOP is compiled by NEXT.

REPEATS      Repeat the next instruction if the count on top of the
return stack is not zero.  The count is also decremented.  If count is
zero, pop the return stack and continue executing the following
instruction.  REPEATS is  compiled by        TIMES or OF(.

The REPEATS instruction is used frequently to implement complicated
math operations, like shifts, multiply, divide and square root, from
appropriate math step instructions.  It is also useful in repeating
auto-indexing memory instructions.

____

// Data structures {{{1
== Data structures ==

.2017-01-18:

Write far-memory versions of `avalue`, `2avalue` and `cavalue`.

// Dictionary {{{1
== Dictionary ==

.2017-01-20, 2017-01-21:

Problem: when data are compiled into the headers space, `>name` can not work,
because it searches the dictionary from oldest to newest.

Solution 1: Search backwards like `find-name`, but search every word list in
the system? 

Solution 2: Add a second link to every header, pointing to the next definition.

Solution 3: Search all word lists, which are chained from
`latest-wordlist`. Of course, the search will be from newest to oldest
word list and from newest to oldest word... But the process should
examine all words of the system, and keep the _nt_ of the oldest word
this the _xt_ that is searched for. This is slow, but saves the
additional link.

// Strings {{{2
=== Strings ===

.2017-01-27:

Generalize `parse-esc-string` and `(parse-esc-string)` to accept a
delimiter char, like `parse`. Then implement `.\(`.

.2017-01-22:

Improve `substitute` and `replaces` with a configurable search order, similar
to that implemented for escaped strings.

.2017-01-07:

Rename `char>string` or write after `c>bstring`, which
does the same but in `pad`.

.2016-12-29:

NOTE: Milestone: 0.14.0

Move the circular string buffer right below `limit`. This way the application
can move it without wasting its original space.

.2016-12-23:

Document `s\"` and `.\"`.

.2016-12-16:

Remove bounds checking from `}` (Noble's arrays)
and keep a copy of it as `?}`, for debugging.

.2016-12-07:

NOTE: Milestone: 0.14.0

Choose a clear convention for suffixes ">str" and ">string". Depending on the
location of the string (circular string buffer, `pad` or another temporary
area)? Another option: "stringer" (after renaming the circular string buffer,
as planned).

`X>string` :: string in the circular string buffer
`X>stringer` :: string in the circular string buffer
`X>bstring` :: binary string in the circular string buffer
`X>bstringer` :: binary string in the circular string buffer
`X>#str` :: temporary string in the pictured numeric string buffer
`X>padstr` :: temporary string in `pad`
`X>bpadstr` :: temporary binary string in `pad`
`X>padbstr` :: temporary binary string in `pad`
`X>padzone` :: temporary binary string in `pad`

.2016-11-19:

Study the strings stack included in Spectrum Forth-83
(file <objects>).

.2015-09-12:

Implement a configurable case mode for `search` and `compare`? See how
Z88 CamelForth does it. Also DX-Forth has this feature.

.2016-06-10:

NOTE: Milestone: 0.14.0

Rename "csb" to "stringer":

|===
| Now         | "stringer"

| >csb        | >stringer
| ?csb        | ?stringer
| csb-size    | /stringer
| csb0        | stringer
| empty-csb   | empty-stringer
| unused-csb  | unused-stringer
|===

// Local variables {{{2
=== Local variables ===

Examples from Forth Dimensions:

|===
| Title                                    | Vo  | N  | Pag | Note

| Turning the Stack into Local Variables   | 03  | 6  | 185 | Implemented: locals.arguments.fsb
| Anonymous Variables                      | 06  | 1  | 033 | Implemented: locals.anon.fsb
| Local Definitions                        | 06  | 6  | 016 | :( `privatize` is simpler
| Letter "Stack Your Locals"               | 07  | 5  | 005 | :( modification of Vo06N6
| Local Variables                          | 09  | 4  | 009 | :( complete but complex, and not recursive
| Letters "Local Variables"                | 09  | 5  | 005 | Implemented: locals.local.fsb
| Letters "Code for Local Variables"       | 10  | 1  | 006 | Modification for FD Vo09N4
| Headless Local Variables and Constants   | 10  | 1  | 019 | Interesting, but for F83
| Letters "Local Variables Revisited"      | 10  | 5  | 005 |
| Local Variables and Arguments            | 11  | 1  | 013 | Seen
| Local Variables - Another Technique      | 11  | 1  | 018 | Seen
| Prefix Frame Operators                   | 11  | 1  | 023 |
|===

// User variables {{{2
=== User variables ===

.2016-11-18:

Rename `(user)` to `user`? That was the original name in fig-Forth, Forth-79
and Forth-83. Choose an alternative for the current `user`, defined in the
library.

// Other {{{2
== Other ==

.2016-12-30:

Add `aconstant`, an array of constants, after `avalue` and `avariable`.

// Documentation {{{1
== Documentation ==

.2017-02-17:

In glossary entries, change "its equivalent code" to "its equivalent
definition".  The reason is "Definition:" is used as heading in normal
cases.

.2017-02-15:

Remove the documentation of DOS subroutines that is duplicated in its
corresponding entry constant, and put a note instead.

.2017-02-15:

Replace "See:" with "See also:" and remove from it the words that are
mentioned in the main description, because they will be cross
references as well.

.2017-02-11:

Update acknowledgements file. Add 4tH.

.2017-02-08:

NOTE: Milestone: 0.14.0

Build the HTML version of <README.adoc>.

.2017-01-23:

Homogenize and fix the notation about interpretation, compilation and
execution/run-time semantics. Better yet, use the simpler convention of
Forth-83.

.2016-08-09:

Change the format of stack notation:

----
xn..x1 --> x[n] ... x[1] 
       --> x[n]..x[1] 
----

.2016-10-24:

Common notation for:

- text coordinates: "col row" --> "x y"?
- graphic coordinates: "x y" --> "gx gy"?

.2016-06-01:

Change the stack notation back to classic Forth?:

- xt -> cfa
- nt -> nfa
- pfa
- lfa

And change also:

- xtp -> cfaa

The problem with the standard notation is it does not provide
alternatives to _pfa_ and _lfa_, because they are system dependent.
This makes the notations _xt_, _nt_, _pfa_, _lfa_ look heterogeneous.
Beside, _xt_ and _nt_ are abstract terms, while _cfa_ and _nfa_ are
precise definitions for the implemention.

.2016-05-11:

Homogenize the stack notation for character/bytes: only _c_.

.2016-04-29, 2016-11-21:

Homogenize the stack notation for blocks and block lines.

Change _n_ to _u_ for blocks and block lines. Consult the notation used in
Forth-2012.

.2016-04-28:

Homogenize the notation "Run-time" to "Execution".

.2016-04-11:

Homogenize the following stack notations:

- double, triple and quadruple numbers (or include all used
  conventions in the documentation).

.2015-07-23:

Adapt the markups of Z88 CamelForth to extract the glossary from the
source.

// DOS {{{1
== DOS ==

.2017-02-13:

Decide if lower-level factor words return a _dosior_ or an _ior_.

Making the low-level words do the conversion needs either a push and a
jump to `dosior>ior` (4 bytes in total), or a direct jump to a
specific routine in the kernel (3 bytes in total), which can save some
bytes, depending on the number of calls done in the kernel and the
library.

Making the conversion in the upper-level calling words means pushing
the _dosior_ in the factor, returning to `next`, and using
`dosior>ior` in the calling word (5 bytes in total).

.2017-02-09:

Study if `flush` should be added to `set-drive`.

.2017-02-05:

Unify G+DOS `transfer-sector` and TR-DOS `transfer-sectors`. Make
their behaviour and names identical. Write the +3DOS version too.

// G+DOS {{{2
=== G+DOS ===

.2017-02-13:

Factor this common code to a routine to jump to:

----
  b pop, next ix ldp#, \ restore the Forth registers
  af push, ' dosior>ior jp, end-code
----

It could be in the kernel, right before `dosior>ior`, and run into it.

.2017-02-13:

Fix: When the current disk is removed before doing `cat`, the
corresponding exception is thrown. But the system does not recognize
the disk when it's inserted back. The same code is thrown: #-1006
(check disk in drive), even after `set-drive`. It seems something more
is needed to make G+DOS be aware of the change.

.2017-02-12:

Factor the following code, which reads a file header; it's used by two
words:

----
    hd00 d ldp#, 9 b ld#,  \ file header destination and count
    rbegin  lbyte hook, d stap, d incp,  rstep
----

.2017-02-12:

Rename the UFIA fields. See TR-DOS File Description Area.

.2017-02-08:

Make `cat` and family check and use `printing`.

----
  \ XXX REMARK -- The disk catalogues can be printed out on a
  \ printer by storing the number 3 into SSTR1 (a field of UFIA
  \ that holds the stream number to use) before doing `CAT`.
  \ The default value is 2 (screen) and should be restored.
  \ Example:
  \
  \   3 sstr1 c! s" forth?.*" wcat 2 sstr1 c!
----

.2017-02-08:

Improve `set-drive`: check if there's a disk in the drive.

.2017-01-05:

Simplify `!dos,`, `c!dos` and family.

.2016-03-16, 2017-02-16:

Study what the unused RAM of the Plus D can be useful for.

// TR-DOS {{{2
=== TR-DOS ===

.2017-02-12:

Implement the original command `LIST` as `cat`, and rename the current
`cat` to `acat`, after the name used in G+DOS.

.2017-02-12:

Make the DOS commands independent to `need`.

.2017-02-12:

Rewrite `dosior>ior` after G+DOS: Convert the AF register. Make the
low-level words return it unchanged.

.2017-02-05:

Define the Z80-symbol constants in the assembler word list:
`dos-routine`, etc.

// +3DOS {{{2
=== +3DOS ===

.2017-02-09:

Adjust the far-memory system to the requirements of +3DOS (RAM disk
and DOS buffers).

.2017-02-06:

Replace `transfer-bytes` with `transfer-sector`. Use the DOS calls DD
READ SECTOR and DD WRITE SECTOR.

.2017-02-06:

Save `jp (ix)` using the code of `noop` instead. Add a label `call_ix`
to make it clear.

.2016-08-14:

`set-drive`, `open-disk` and `close-file` work on drive "a".  But when drive
"b" is used, `close-file` returns ior -1006 (unrecognised disk format). This
is a problem of fsb2's fb2dsk.

// Errors {{{1
== Errors ==

.2016-11-27:

Rename?:

- `warn.throw` to `error-code-warn`
- `warn-throw` to `error-warn`
- `warn.message` to `message-warn`

.2016-04-25:

Idea: Add `where` to the default exception message. In order to save space,
`where` should be in the library and patch itself into the default message.

.2015-09-20:

Idea:
____

The correlation between DX-Forth exception code and DOS error code
is given below:

 Exception   DOS
     0        0     no error
   -511       1     function number invalid (not used)
   -510       2     file not found
   -509       3     path not found
   -508       4     too many open files
   -507       5     access denied
   -506       6     invalid handle
    ...     ...
   -257     255     unspecified error

Note: To convert an exception code in the range -257 to -511 to its
corresponding DOS error code, use: 255 AND
____

.2015-10-18:

`.warning`

// Files {{{1
== Files ==

.2016-04-11:

Make the tape words return a standard _ior_.

Rename the tape and disk words after a common convention. Maybe after
Gforth `slurp-file` and Galope `unslurpe-file`: `slurp-tape-file`,
`unslurp-tape-file`, `slurp-file`, `unslurp-file`.

.2016-03-02:

Adapt all file words to standard _ior_; remove _f n_.

2016-04-09: already done?

.2015-09-18:

New: `.files` (from Pygmy Forth).

// Games {{{1
== Games ==

.2016-12-27, 2017-01-13:

Extract the games, make them independent projects?

.2016-05-13, 2017-01-13:

Convert the sample games to .fs.  and load them with `load-app`.  This will
save several blocks of source.

// Graphics {{{1
== Graphics ==

.2017-02-12:

Rename `border` to `set-border` and add `get-border`.

.2017-02-08:

Make `circle-pixel` throw an error by default. It can not be a
deferred word, because it must return the address of a routine.

.2017-02-06:

Alternative method to set paper colors:

----
: on-blue  ( b1 -- b2 )  blue papery +  ;
: on-red   ( b1 -- b2 )  red papery +  ;
' noop alias on-black immediate
----

The names were borrowed from Pygmy Forth.

Better in Z80:

----
code on-blue  ( b1 -- b2 )
  h pop, h a ld, blue papery add#, pusha jp,  end-code
----

.2017-02-04:

Document the usage of UDG codes greater than 255. `emit-udg` admits them.

.2017-02-02:

Test the new version of `(cursor-addr)` and rename it to `(xy>address`
or similar, and so its family. Be consistent with the planned names to
get attribute addresses from cursor and graphic coordinates.

.2017-02-02:

Fix `g-emit-routine`.

.2017-02-01:

Finish `rdraw`.

.2017-01-24:

NOTE: Milestone: 0.14.0

Write `g-xy-attr@  ( x y -- b )` and `g-xy-attr!  ( b x y -- )`.

.2017-01-22:

NOTE: Milestone: 0.14.0

Write `xy-attr@  ( x y -- b )` and `xy-attr!  ( b x y -- )`.

.2017-01-13:

Improve `ocr`: Return a flag apart from the code, in order to make it possible
to recognize character zero:
  
----
  \ ocr  ( col row -- c true | false )
----

Or write a variant:

----
  \ ocr?  ( col row -- c true | false )
----

.2017-01-09, 2017-02-04:

Add `.udg"` as a fast way to print strings of UDG (0..255).

.2017-01-09:

Finish `udg-block[`.

.2016-12-26:

Factor `adraw176` to write `aline176`, which uses `set-pixel` and is faster.
Write a similar alternative to `rdraw`, `rline`.

.2016-12-02:

Rewrite in Z80 the low-level words of <printing.color.fsb>.

.2015-09-05:

Name for graphic fill: `flood`.

// Keyboard {{{1
== Keyboard ==

.2016-12-26:

Remove `discard-key`? It does exactly the same as `key drop`, but faster, and
it uses only two bytes of data space (for `push ix`).

.2016-12-26:

Test `break?`.

.2016-11-25:

`akey` for `accept`, after SwiftForth.

.2015-06-30:

New: command history, stored in the names bank.

.2015-06-07:

Change: move key to the blocks, as `mode-key` or similar, and use a
simpler `key` (`akey` from Afera).

.2015-06-30:

Change: modify `expect` after Spectrum Forth-83.

// Kernel {{{1
== Kernel ==

.2016-10-27:

Use `_jump` macros at the end of `umax`, `umin`, `dabs`, `abs`, etc.

.2016-04-24:

Words that can be moved to the library: `catch`, `?\`,
`[defined]`, `[undefined]`, `umin`, `umax`...

Study how to move `line>string` and `undefined?` to the library.  They are not
used in the kernel, but they are needed by the `need` utility.

.2016-05-06:

Remove the routine `compare_de_hl_signed`, if possible.

// Makefile {{{1
== Makefile ==

.2017-02-14:

Fix:

When a kernel file is modified, the boot disk is built twice before
`make` informs there's nothing to do. The first time the kernel and
the BASIC loader are built; the second time, only the BASIC loader.

This does not happen doing `make clean;make all`: the next `make all`
does nothing, as expected.

// Maths {{{1
== Maths ==

.2017-01-24:

Rewrite `?shift` in Z80.

.2016-12-30:

Rewrite `du<` in Z80.

.2016-12-30:

NOTE: Milestone: 0.14.0

Remove module <math.number.prefix.fsb>.

.2016-12-28:

----
: ?ifelse  ( x1 x2 f -- x1 | x2 )  if  drop  else  nip  then  ;
: ifelse  ( x1 x2 f -- x1 | x2 )  rot ?ifelse  ;
----

.2016-12-27, 2017-02-04:

If `base` were not a user variable, `binary`, `hex` and `decimal`
would be smaller in Z80 than in Forth.

.2015-07-23, 2017-01-26:

Idea: 2 more bytes for `base`, to be used as save-restore space.

----
  : switch  ( a1 -- )  dup cell+ exchange  ;
    \ Exchange the 16-bit contents of a1 and the following cell.

  \ Example:

  base switch hex

  base switch
----

Use this to factor `dec.` and write `decu.` or `udec.` (useful in
`where`).

`switch` is taken by a control flow structure.

.2015-09-12:

....

ROTATE         n1 n2 -- n3

     Rotate  the value n1 left n2 bits if n2 is positive, right  n2
     bits  if n2 is negative.  Bits shifted out of one end  of  the
     cell are shifted back in at the opposite end.

  \ Standard: Forth-79 (Reference Word Set); Forth-83 (Appendix
  \ B.  Uncontrolled Reference Words).
....

.2016-05-31:

The idiom `-1 =` is used 3 times in the kernel. It could be defined this way:

----
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  ld a,$FF
  cp h
  jp nz,false_
  cp l
  jp nz,false_
  jp true_

  ; 14 B
----

Or:

----
  _code_header rminus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  ld a,$FF
  cp h
  jr nz,false_
  cp l
  jr nz,false_
  jr true_

  ; 11 B
----

And an alias `true=` could be defined.

6 bytes would be saved in the kernel thanks to any of these definitions, but
they need 14 or 11 bytes...

More options (2016-08-05):

----
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  inc h
  inc l
  ld a,h
  or l
  jp nz,false_
  jp true_

  ; 11 B
----

----
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  inc h
  inc l
  ld a,h
  or l
  jr nz,false_
  jr true_

  ; 09 B
----

Better (2017-02-04):

----
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  inc hl
  ld a,h
  or l
  jp nz,false_
  jp true_

  ; 10 B
----

.2016-05-07:

Implement 2-cell operators from Spectrum Forth-83. Most of them are written in
Z80.

.2016-05-01:

Change the order of the parameters of `%` and `u%`, after _Starting Forth_ pp
103..105.

.2016-04-27:

Adapt `d>q`, `q>d`, `s>q`, `q+`, `q-`, `udm*` from Pygmy, in module
"math.operators.4-cell.fsb".

.2016-04-18:

Modify `interpret` to be patched by a floating-point implementation in order
to recognize floating-point numbers.

Make `number?` deferred, in order to add floating-point support.

.2016-04-17:

`factorial`, from Forth-2012 documentation: examples in `recurse` and
`repeat`.

.2015-12-24:

Fractional arithmetic, Forth Dimensions volume 4-1.

.2016-03-16:

Idea to improve `number?`, or to write an optional alternative: Return the
chars and positions of every point, not only the last one. Convert `dpl` to a
backwards compatible array:

----
+0 cell: position of the last point
+2 byte: last point
+3 cell: position of the last but one point
+5 byte: last but one point
etc.
----

A new variable `#dpl` would hold the number of points.

// Floating point {{{2
=== Floating point ===

.2016-04-22:

Document floating point.

.2016-04-22:

Idea: Use the ROM calculator memories (0..5) as floating-point non-recursive
locals. Problem: some calculator's words use them (eg. `over`).  They could be
recursive, because their address can be changed with the system variable MEM;
they could be pointed to a frame in the return stack.

Simpler idea: use the calculator memories them as is, as temporary storage.
The ROM allocates 6*5 bytes, but 32*5 can be used.

.2016-04-19:

Floating-point words `flit`, `fliteral`. From PFE: `fround>s`, `ftrunc>s`
(being `f>s` a synonym), `1/f`, `f^2`, `f^n`, `f2/`, `f2*`.

// Memory {{{1
== Memory ==

.2017-01-26:

Rewrite `exchange`, `cexchange`, `!exchange`  and `c!exchange` in Z80.

.2017-01-24:

----
: /pad  ( -- len )  limit @ pad -  ;
----

.2016-11-15:

Write far-memory versions of some of the following words from the
<memory.MISC.fsb> module:

----
  \ -!
  \ /! *! 2/! 2*!
  \ bit>mask bit? set-bit reset-bit
  \ c1+! c1-! 1+! 1-!
  \ c@and ctoggle
  \ exchange reserve alloted
  \ n, nn, n@ nn@ n! nn!
----

.2016-11-13:

Remove `get-default-bank` and `set-default-bank`.

// Misc {{{1
== Misc ==

.2017-02-06:

NOTE: Milestone 0.14.0

Adapt the zx7 decompressor (written by Einar Saukas).

.2016-05-18:

Factor `new-needed-word  2dup undefined?`.

.2016-04-16:

Write `behead  ( "name" -- )`. DX-Forth uses `behead ( "name1" "name2" -- )`.
`hided  ( nt -- )` is already in the kernel.

.2016-11-12:

Ideas from
http://www.bedroomlan.org/hardware/cft/book/forth-programming-d2-reference[CFT
Forth]:

....

BASE>R

R>BASE

#CONTEXT ( -- a ) (numCONTEXT) The number of entries in the vocabulary stack.

#WORDS ( -- n ) (countwords) Returns the number of words in the CURRENT
vocabulary.

!BITS ( 16b1 addr 16b2 -- ) (store-BITS) Store the value of 16b1 masked by
16b2 into the equivalent masked part of the contents of addr, without
affecting bits outside the mask.

+FLAG! ( u a -- ) (set-FLAG-store) The value at address a is ORred with u
in-place.

-FLAG! ( u a -- ) (clear-FLAG-store) The value at address a is ANDed with (NOT
u) in-place.

.BANKS ( -- ) (dot-BANKS) Prints out the current memory banking scheme.

.BASE ( -- ) (dot-BASE) Prints out the base.

.DATE ( -- ) (dot-DATE) Read and print out the date from the the real-time clock.

.TIME ( -- ) (dot-TIME) Read and print out the time from the the real-time
clock.

.rs ( -- ) (dot-rs) Prints out the return stack non-destructively.

16* ( w -- w ) (16mul) Shift left four bits.

16/ ( u -- u ) (16div) Shift right four bits (one nybble). No sign extension.

1MS ( -- ) Delay for approximately 1 millisecond.

256* ( w -- w ) (256mul) Shift left eight bits.

256/ ( w -- w ) (256div) Shift right eight bits.

>FLAGS ( a -- u ) (to-FLAGS-fetch) Given the PFA of a word, return its ﬂags.

>LINK@ ( a -- a | f ) (to-LINK-fetch) Given the PFA of a word, return the head address of the word preceding it in the vocabulary. If this is the first word in the vocabulary, false (zero) is returned.

....

.2015-06-10:

Adapt this word from Spectrum Forth-83, which uses it in `cold` and
`query`:

----
  : TERMINAL ( --- )
    LIT PKEY (KEY) !    \ Set default handler for KEY.
    >S ;                \ And initialize screen output.
----

.2015-09-22:

Add `console` to do `display` and init the keyboard and `tib` (see
Spectrum Forth-83).

// Multitasking {{{1
== Multitasking ==

.2017-01-28:

Make the following environment question depend on the current values,
which can change when multitasking is active:

----
$2C +origin @ constant return-stack-cells ( -- n )
    \ Maximum size of the return stack, in cells.

$2A +origin @ constant stack-cells ( -- n )
    \ Maximum size of the data stack, in cells.
----

.2017-01-19:

Study the way v.Forth manages the interrupts and adapt it.

// Library {{{1
== Library ==

.2017-02-16:

Move `>name` to the library, and make the alternative slower
implementation optional.

.2017-02-08:

Move `?(` to the kernel. Since `exit` is not used after conditional
compilation, `?(` must be loaded most of the times, because the whole
block is interpreted.

.2017-01-31:

Words that could be moved to the library, if the `need` tool didn't use them:
`2over`, `line>string`.

.2016-12-08:

Rename <math.number.print.fsb> to <printing.number.fsb>.

// Loading {{{1
== Loading ==

.2017-02-12:

Idea for a faster version of `(locate)`: Load only the first sector of
the blocks, and do the search directly in the buffer, without the
`line>string` step. It will be faster, but it's lower level and may
give problems with recursion.

.2017-01-06:

Improve `load-app`: save and restore the source, in order to continue loading
after `load-app`. This ways, several programs can be loaded this way.
Also, rename it to `load-program`.

.2016-12-30:

Add `//` to ignore the rest of the source, as a shorter alternative to `exit`
to exit the current block.

.2016-12-29:

`(located)  ( ca len -- block | false )` returns _false_ also when _ca len_ is
empty, therefore the exception code thrown by the calling word is always #-268
(needed but not located).  This is not a big problem, but exceptions #-16
(attempt to use zero-length string as a name) or #-32 (invalid name argument)
would be clearer.

.2016-12-03:

Make `need-here` unnecessary: Always check the current block, just in case.
Many needed words are in the same block.

.2016-11-22, 2016-12-31, 2017-02-16:

Write `needs` to do multiple `need` on one line of a block,
saving space

----
needs word1 word2 word3 word4
needs word5 word6 word7 word8
----

NOTE: Milestone: 0.14.0

Write `need( )` to do the same without the one-line limit:

----
need( word1 word2 word3 word4
      word5 word6 word7 word8 )
----

----
: need(  ( "name#1" ... "name#n" "<paren>" -- )
  begin  parse-name 2dup s" )" str= 0=
  while  needed  repeat  2drop  ;
----

`need\` is clearer than `needs` to parse the current line, but `need(`
seems the best option.

.2016-11-19, 2016-12-29:

NOTE: Milestone: 0.15.0

Finish the alternative version of `indexer` to index the blocks on the fly as
they are being searched by `need` and family, i.e., not in advance.

.2016-05-18:

Improve `need` to make several index lines possible, by making `(` executable:

----
( very-long-word-1 very-long-word-2 very-long-word-3
very-long-word-4 very-long-word-5 very-long-word-6 )
----

Problem: this would force changes in fsb and fsb2.

// Forth modules {{{1
== Forth modules

.2017-01-05:

`>>link far!` is used in `forget-transient`, but it's what `unlink-internal`
does. Factor and reuse.

.2016-12-29:

Improve `transient` to actually unlink all the transient words?  This means
backuping and restoring the latest definition of all word lists...

.2016-12-07:

....
Newsgroups: comp.lang.forth
Date: Wed, 3 Aug 2016 01:18:18 -0700 (PDT)
In-Reply-To: <0a8d7b8a-8367-4e92-a482-ee8b6728325a@googlegroups.com>
Message-ID: <c5aa8e30-1dee-4d64-9022-e24f46b20437@googlegroups.com>
Subject: Re: Code management with wordlists
From: hheinrich.hohl ...
....

Excising

This method was used in LMI PC/FORTH and UR/FORTH.

EXCISE <word1> <word5>

This command hides the headers of <word1> through <word5> 
by excising their headers from the linked list in the dictionary.

Together with the ability to create binary overlays, the LMI FORTH compilers
enabled the user to create modules that showed only words that are relevant
for the end user.

.2016-12-07, 2017-02-16:

NOTE: Milestone: 0.14.0

Combine `begin-module` and `package`.

Also, `end-module` is used by modules `module` and `begin-module`.

// Names {{{1
== Names ==

.2017-02-16:

Decide a naming convention for words that return the address of a Z80
routine. Now several conventions are used, e.g. "-routine", parens,
no-hyphen, and others.

Maybe "-mc" for "machine code"? Too cryptic.

.2017-01-31:

NOTE: Milestone: 0.14.0

Rename `>defer` to `>action`, after the standard `action-of`

.2017-01-30:

NOTE: Milestone: 0.14.0

Current names of some screen filters are too generic. Rename them:

- `water` to `wave-screen`
- `inverted` to `invert-screen`
- `fade` to `fade-screen`

.2017-01-28:

Rename `(pixel-addr)` to `(pixel-addr`, and family.

.2017-01-28:

Rename `bitmap>attr-addr` to `screen>attr-addr`? More clear?

.2017-01-17:

Rename old "rec" to "sectors", for example in `rec/blk`.

.2017-01-05:

Use parens after a convention: `(name)` for words not useful for the
user, not accessible in the library; `(name` for internal words that
may be useful for the user and are accessible in the library. Beside,
this avoids the need to use backslash-delimited index block lines in
the library.

.2017-01-02:

Improve definition names in the `ocr` module: Use "font" instead of
"charset".

.2016-12-31:

Rename all paren words to use only the opening paren? This would make the
block index line backslash notation unnecesary.

// Optimizations {{{1
== Optimizations ==

.2017-02-04:

Rewrite `hide` in Z80, move it before `hidden` and use this one as
its tail code.

Rewrite `reveal` in Z80, move it before `revelead` and use this one as
its tail code.

.2017-02-04:

Make `cold` a code word in order to save space from basic init
operations, e.g. modifying memory. Then continue execution into a
colon word called `(cold)`, which finishes the high-level tasks.

Identify operations in `cold` that can be factored out as code words,
to save space. For example, the patching of `cold.home`.

// Parsing {{{1
== Parsing ==

.2016-05-13:

Improve `?(` with `refill`, to cross block boundaries?
This would be needed  for `load-app`. Maybe two versions:
if `load-app` has been compiled, then compile the improved version of `?(`.

.2016-06-01:

When loading an app with `load-app`, make `(` behave like in the
Forth-2012 FILE word set.

.2015-10-15:

NOTE: Milestone: 0.14.0

Adapt from Gforth: `noname`, analogous to `nextname`.

// Printing {{{1
== Printing ==

.2017-02-04:

Rename `mode32-emit` to `mode32-rom-emit` and write an alternative
word `mode32-iso-emit` to print characters 128..255 also from the
current font.  This will make it possible to use 8-bit character sets.

.2017-01-18, 2017-02-04:

Current versions of `type-right-field` and `type-center-field` use
spaces. This creates a banner.

Write alternative versions that move the cursor position instead.

Choose shorter names:

|===
| Current name        | New name        | Common name with factored execution table

| `type-left-field`   | `<type-field`   | `left-type type-field`
| `type-center-field` | `<type-field>`  | `center-type type-field`
| `type-right-field`  | `type-field>`   | `right-type type-field`
|===

Using the execution table as parameter has a problem:
`type-left-field` does not use execution table. Besides, the execution
tables will be different for the future set of words that type without
padding spaces, so finally the number of different words will grow
anyway.

.2017-01-02:

Adapt the banked screen mode (which uses the unfinsihed implementation
of a code bank for addons) to far memory or remove it.

.2016-12-30:

Combine `clear-block` and family with the text windows.

.2016-12-24, 2017-02-03:

Windows:

- Scroll support, with configurable pause.
- Rewrite `wcls` in Z80, or use `spaces` instead of `type`
- Save and restore windows, in Z80.

.2016-12-20:

Move `.0000` and `.00` from the time module to the printing module, and factor
them for double numbers.

.2016-11-26:

NOTE: Milestone: 0.14.0

Make `type-ascii` configurable: store the common char in a character variable.
In fact, it would be enough to write `emit-ascii`, because `emit` is deferred,
and use `type`.

Make `type` deferred, to be configured as `fartype` or other when needed.

.2016-11-21:

Add support for more control characters to alternative version of `mode64`.

.2016-11-21:

In mode 32, one `cr` does nothing when the cursor is at the end of a line.
That is the default behaviour in Sinclair BASIC. The driver of `mode42` works
the same way.  But the driver of `mode64` always prints the carriage return,
increasing the line number. Somehow the behaviour must be unified in all
modes. The behaviour of `mode64` seems more logical.

.2016-10-28:

NOTE: Milestone: 0.14.0

Simplify `u.r`.

.2016-08-11:

Remove the 64 cpl font from the library (4 blocks), and use the binary file
(336 bytes) instead? Or provide the file as an alternative.

.2015-09-05:

There's an example how to change and restore a channel in print-42, by
Ricardo Serral Wigge. Beside, it supports many (all?) control
characters, unlike the implementation by Andy Jenkinson.

.2015-09-11:

Idea: screen modes table?

- 0: 32 cpl original (ROM routines)
- 1: 32 cpl improved (bold, italic).
- 3: 36 cpl
- 4: 42 cpl
- 5: 51 cpl
- 6: 64 cpl

It seems more versatile to create one word to select every mode and provide a
common user interface to row, column, cpl, window...

.2016-10-27:

Add `vemits`, inspired by TI BASIC's `call vchar()`.

.2016-04-17:

Improve tab control.

// Project tree {{{1
== Project tree ==

NOTE: Milestone: 0.14.0

.2017-02-07:

Rename <bin/sys> to <bin/dos>.

// Stacks {{{1
== Stacks ==

.2017-01-20:

Make the return stack grow toward high memory and move it below the data stack.
This way both stacks can share a common free space.  This is an advantage
because you can have programs which need quite some return stack depth, but few
data elements - or the inverse.  "Stack overflow" means both pointers cross.
The idea was taken from 4tH:

....
Message-ID: <57f3f915bash75@news.xs4all.nl>
From: Hans Bezemer
Subject: Re: Stack Sizes
Newsgroups: comp.lang.forth
Date: Tue, 04 Oct 2016 20:46:33 +0200
....

.2017-01-20:

Implement this, as a simpler alternative to `xstack`:

-----
: stack dup ! ;                        ( stack --)
: a@ @ @ ;                             ( stack -- n)
: >a 1 cells over +! @ ! ;             ( n stack --)
: a> dup a@ -1 cells rot +! ;          ( stack -- n)
: adepth dup @ swap - ;                ( stack -- n)
-----

Credit:

Code from 4tH:

....
Message-ID: <57f3f915bash75@news.xs4all.nl>
From: Hans Bezemer
Subject: Re: Stack Sizes
Newsgroups: comp.lang.forth
Date: Tue, 04 Oct 2016 20:46:33 +0200
....

.2017-01-07:

Notes about nested `need`:

Each nested `need` uses 14 cells of the return stack: `nest-source` uses 6
cells for data, `need` uses 2 cells for the string, the rest must be used for
calls.

// Sound {{{1
== Sound ==

.2017-01-24:

Convert `middle-scale` to mHz (milihertzs) for greater accuracy and
write `mhz>bleep`.

.2016-10-10:

Finish the conversion of 128K sound explosions. More details in the source.

// Tape {{{1
== Tape ==

.2017-02-08:

Rename `read-tape-file` and `write-tape-file` after a new convention
shared with similar disk operations.

.2017-02-08:

Fix `read-tape-file`: when the file length attribute is not zero
(=undefined) or the real file lenght to be loaded, the ROM routine
returns to BASIC with "Tape loading error". This crashes the system
(because the message can not be printed, because the lower screen has
no lines). This will be avoided in a future version of Solo Forth.

The simplest solution seems to remove the parameter and always use 0
internally.

// Time {{{1
== Time ==

.2017-02-13:

Try simpler alternative to `ms`, based on this loop found in the Plus
D disassembly:

----
  ; Wait about 1 ms
  ld   b,0
rest_1:
  djnz rest_1 ; 13/08 T
  ; 255*13+8= 3323 T
----

.2017-01-24:

From SwiftForth:

EXPIRED  ( u — flag )

Return true if the current millisecond timer reading has passed u. For
example, the following word will execute the hypothetical word TEST
for u milliseconds:

----
: TRY ( u -- ) COUNTER + BEGIN TEST DUP EXPIRED UNTIL ;
----

.2016-12-06, 2017-01-24:

NOTE: Milestone: 0.14.0

Rename `bench{` and `}bench` and family.

Maybe after SwiftForth: `counter` and `timer`:

----
counter  ( -- ms )
Return the current value of the millisecond timer.
----

----
: timer  ( ms -- )  counter swap - u.  ;
----

.2016-12-20:

Use `chars` in offsets of `get-date` and `set-date`.

.2015-12-14:

Update the date with interrupts.

.2016-11-18, 2016-11-19:

Rename `frames@` to `ticks@`, etc.?

`utime`, `cputime`? (See Gforth)

// Tools {{{1
== Tools ==

.2017-02-09:

Improve `search_library.sh` to include the kernel, or write an
alternative.

.2017-01-06:

Study the editor of Pygmy Forth.

.2016-11-28:

Improve `see`: decode `does>`.

.2016-11-26, 2017-02-06:

Rename `.unused` to `.free` (if other info is added).

.2016-11-25:

NOTE: Milestone: 0.14.0

Write `ed:` after TurboForth.

.2016-11-19:

Make `editor` defered, in order to load more than one editor at the same time.

// User variables {{{1
== User variables ==

.2016-11-27:

Update the user variables that are initialized (`warnings` has been removed,
but its place is used by `lastblk`, which does not need initialization).

.2015-09-13:

NOTE: Milestone: 0.14.0

`rp` should be a user variable.

.2015-06-30:

Change: compare the user variables with those of Spectrum Forth-83.


