= Solo Forth TO-DO

.2015-06-04:

Move the most used words to the top of the `forth` vocabulary: `:`,
`;`, stack words, control structures, etc.  This should speed up the
compilation of sources.

.2015-06-05:

Fix: `begin` structures produce compilation errors in screens, but not
in the terminal! [Already solved?]

Still strange problems with the stacks:

The problem seems to be, `?stack` is used only by `interpret`, but not
during the execution of a word. When a word stacks several numbers,
they can corrupt the zone below the stack before `?stack` detects the
overflow.

.2015-06-06:

DZX-Forth implements `exit` simple as `compile (exit)`, and
`exit` is the word called by `;`. Compare both implementations.

Define `rp`, like in Afera:

  HEX  5E68 CONSTANT RP  DECIMAL

.2015-06-07:

Write a version of `screen` that recognizes the UDG.

Change: move key to the blocks, as `mode-key` or similar, and use a
simpler `key` (`akey` from Afera).

.2015-06-09:

In order to save compilation time, move inner words to the bottom of
the dictionary. Example: `(loop)`, `clit`, `back`, `digit`...

.2015-06-10:

Adapt this word from Spectrum Forth-83, that uses it in `cold` and `query`:

  : TERMINAL ( --- )
    LIT PKEY (KEY) !    \ Set default handler for KEY.
    >S ;                \ And initialize screen output.

Fix?: in 128, typing graphics T and U prints the new tokens.

New: A printing routine instead the ROM routines, with two fonts: for
chars 0..127 and for chars 128..255.

.2015-06-17:

New:
- Case-sensitive mode.
- Create words in lowercase.
- Improve `parse-name` with case conversion and move it to the kernel.

.2015-06-20:

New: `compiling?` and `executing?` after DZX-Forth.

New: `rshift` and `lshift`, from DZX-Forth.

.2015-06-22:

New: `within`, `between`, from DZX-Forth.

This error happens in all fig-Forth systems:

----
: test 6 literal ;  RAL ? [ rubbish ] MGS # 2
----

Fix:

----
123 16384 2!  ? [ rubbish ] MSG # 2
----

.2015-06-23:

Fix:

`require`.

Fix:

`continued` does strange things, when used in the command line.

Fix:

`require` does strange things, because the strings are overwritten.  A
circular buffer is needed, and a heap would be useful to implement it
without a fixed size.

Fix:

`2>r` and `2r>`. (done?)

.2015-06-25:

Change:

fig-Forth `leave` --> `last-loop` | `no-loops` | `enough-loop` |
`exhaust` | `exhausted` | `last` | `last-do`

New:

ANS Forth `leave` (code from DZX-Forth) --> `exit-loop` | `break-loop`
| `enough` | `break` | `abandon`

New: `??`. A control structure than executes the next compiled word if
TOS is non-zero, else skip it.

.2015-06-26:

Fix: `plot` and `point`.
