= Solo Forth TO-DO

.2015-06-04:

Move the most used words to the top of the `forth` vocabulary: `:`,
`;`, stack words, control structures, etc.  This should speed up the
compilation of sources.

.2015-06-05:

Still strange problems with the stacks:

The problem seems to be, `?stack` is used only by `interpret`, but not
during the execution of a word. When a word stacks several numbers,
they can corrupt the zone below the stack before `?stack` detects the
overflow.

.2015-06-06:

DZX-Forth implements `exit` simple as `compile (exit)`, and
`exit` is the word called by `;`. Compare both implementations.

.2015-06-07:

Write a version of `screen` that recognizes the UDG.

Change: move key to the blocks, as `mode-key` or similar, and use a
simpler `key` (`akey` from Afera).

.2015-06-09:

In order to save compilation time, move inner words to the bottom of
the dictionary. Example: `(loop)`, `clit`, `back`, `digit`...

.2015-06-10:

Adapt this word from Spectrum Forth-83, that uses it in `cold` and `query`:

  : TERMINAL ( --- )
    LIT PKEY (KEY) !    \ Set default handler for KEY.
    >S ;                \ And initialize screen output.

Fix?: in 128, typing graphics T and U prints the new tokens.

New: A printing routine instead the ROM routines, with two fonts: for
chars 0..127 and for chars 128..255.

.2015-06-17:

New:
- Case-sensitive mode.
- Create words in lowercase.
- Improve `parse-name` with case conversion and move it to the kernel.

.2015-06-20:

New: `executing?` after DZX-Forth.

New: `rshift` and `lshift`, from DZX-Forth.

.2015-06-22:

New: `within`, `between`, from DZX-Forth.

This error happens in all fig-Forth systems:

----
: test 6 literal ;  RAL ? [ rubbish ] MGS # 2
----

Fix:

----
123 16384 2!  ? [ rubbish ] MSG # 2
----

.2015-06-25:

Change:

fig-Forth `leave` --> `last-loop` | `no-loops` | `enough-loop` |
`exhaust` | `exhausted` | `last` | `last-do`

New:

ANS Forth `leave` (code from DZX-Forth) --> `exit-loop` | `break-loop`
| `enough` | `break` | `abandon`

New: `??`. A control structure than executes the next compiled word if
TOS is non-zero, else skip it.

.2015-06-26:

Fix: `plot` and `point`.

.2015-06-28:

Fix: Something went wrong after the massive of the `_number` macro:
`.` does not print well; `require` gives error 0!...  The problem is
`_number -1`! Why? I wrote the autor of Pasmo. (He helped).

.2015-06-30:

New: command history, stored in the names bank.

Change: remove double `;s` from the colon words in the kernel. Use
`exit` instead, else the word can not be decoded.

Change: modify `expect` after Spectrum Forth-83.

Change: modify `key` after Forth-83 and ANS Forth.

Change: compare the user variables with those of Spectrum Forth-83.

Change: rewrote `word` to return and address, after Forth-83 or ANS Forth.

.2015-07-05:

From F83:

----
: MAP  ( n pfa --- addr )
  \ Given the pfa of a case word and the index n for case
  \ selection, return the execution address selected. Abort if the
  \ index is out of range.
  2DUP @  \ Fetch the range from pfa.
  U< IF  \ Is the index n within range?
    2+ SWAP 2* +  \ Address of the execution code.
  ELSE OUT  \ Abort if out of range.
  THEN
  ;

: CASE:  ( n --- )
  \ A positional case statement. The range n is used for error checking.  At runtime, the nth word is executed, depending on the value on stack when executed.
  CONSTANT  \ Compile the range n as a constant.
  HIDE  \ Smudge the name field as : would do.
  ]  \ Now, use the colon compiler to compile the cases.
     \ Compilation will be terminated by the ; command.
  DOES>  ( index --- )  \ At runtime, use the index to find the execution address among the compiled cases and execute it.
    MAP  \ Return the address pointing to one of the cases compiled.
    PERFORM  \ Execute it.
  ;
----


.2015-07-06:

Fix: `parse-word`.

.2015-07-21:

New words in the assembler vocabulary:

`next,` :: `jp (ix)`
`pushhl` :: `jp pushhl`
`pushde` :: `jp pushde`

