= Solo Forth TO-DO

.2015-06-04:

Move the most used words to the top of the `forth` vocabulary: `:`,
`;`, stack words, control structures, etc.  This should speed up the
compilation of sources.

.2015-06-05:

Fix `exit`, `?exit`, `rdrop`...

Fix: `begin` structures produce compilation errors in screens, but not
in the terminal!

Still strange problems with the stacks:

The problem seems to be, `?stack` is used only by `interpret`, but not
during the execution of a word. When a word stacks several numbers,
they can corrupt the zone below the stack before `?stack` detects the
overflow.

Often the stack gets full during compilation of screens.


.2015-06-06:

Save the error code, in case `warning` is -1.

Make `where` to use values saved somewhere, not on the stack?


DZX-Forth implements `exit` simple as `compile (exit)`, and
`exit` is the word called by `;`. Compare both implementations.

Define `rp`, like in Afera:

  HEX  5E68 CONSTANT RP  DECIMAL

.2015-06-07:

Write a version of `screen` that recognizes the UDG.

Fix: `17 load` corrupts the system.
