= Solo Forth TO-DO
:author: Marcos Cruz (programandala.net)
:revdate: 2016-11-13

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

// }}}
== Misc ==
// {{{

.2016-11-13:

Remove `get-default-bank` and `set-default-bank`.

.2016-11-13:

Make `dp` an ordinary variable? Then `here`, `there` and `allot` could be
improved, rewritten in Z80.

.2016-11-12:

Move the lex bits off the length byte of the name field.

.2016-11-12:

Ideas from
http://www.bedroomlan.org/hardware/cft/book/forth-programming-d2-reference[CFT
Forth]:

....

BASE>R

R>BASE

#CONTEXT ( -- a ) (numCONTEXT) The number of entries in the vocabulary stack.

#WORDS ( -- n ) (countwords) Returns the number of words in the CURRENT
vocabulary.

!BITS ( 16b1 addr 16b2 -- ) (store-BITS) Store the value of 16b1 masked by
16b2 into the equivalent masked part of the contents of addr, without
affecting bits outside the mask.

+FLAG! ( u a -- ) (set-FLAG-store) The value at address a is ORred with u
in-place.

-FLAG! ( u a -- ) (clear-FLAG-store) The value at address a is ANDed with (NOT
u) in-place.

.BANKS ( -- ) (dot-BANKS) Prints out the current memory banking scheme.

.BASE ( -- ) (dot-BASE) Prints out the base.

.DATE ( -- ) (dot-DATE) Read and print out the date from the the real-time clock.

.TIME ( -- ) (dot-TIME) Read and print out the time from the the real-time
clock.

.rs ( -- ) (dot-rs) Prints out the return stack non-destructively.

16* ( w -- w ) (16mul) Shift left four bits.

16/ ( u -- u ) (16div) Shift right four bits (one nybble). No sign extension.

1MS ( -- ) Delay for approximately 1 millisecond.

256* ( w -- w ) (256mul) Shift left eight bits.

256/ ( w -- w ) (256div) Shift right eight bits.

>FLAGS ( a -- u ) (to-FLAGS-fetch) Given the PFA of a word, return its ﬂags.

>LINK@ ( a -- a | f ) (to-LINK-fetch) Given the PFA of a word, return the head address of the word preceding it in the vocabulary. If this is the first word in the vocabulary, false (zero) is returned.

CONTEXT@ ( u -- a ) (CONTEXT-fetch) Get the u-th (from the top) entry in the
vocabulary stack. The value returned is the address of a variable holding the
address of the last entry in that dictionary. It’s also the PFA of the
vocabulary word.

....

.2016-10-28:

Simplify `u.r`.

Remove the old `alias!` when the extra-memory system becomes definitive.

Remove `split` and `join` from the kernel when the extra-memory system
becomes definitive.

Remove `s!` and related words when the extra-memory system becomes definitive.

Fix the extra-memory system:

- Finish `>name`.

.2016-10-27:

Finish the extra-memory system in the kernel.

Use `_jump` macros at the end of `umax`, `umin`, `dabs`, `abs`, etc.

.2016-08-11:

Remove the 64 cpl font from the library (4 blocks), and use the binary file
(336 bytes) instead? Or provide the file as an alternative.

.2016-08-09:

Change the format of stack notation:

----
xn..x1 --> x[n] ... x[1] 
       --> x[n]..x[1] 
----

.2016-06-01:

Fix warnings during compilation of the tt game.

.2016-05-31:

The idiom `-1 =` is used 3 times in the kernel. It could be defined this way:

----
; ----------------------------------------------
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  ld a,$FF
  cp h
  jp nz,false_
  cp l
  jp nz,false_
  jp true_

  ; 14 B
----

Or:

----
; ----------------------------------------------
  _code_header rminus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  ld a,$FF
  cp h
  jr nz,false_
  cp l
  jr nz,false_
  jr true_

  ; 11 B

----

And an alias `true=` could be defined.

6 bytes would be saved in the kernel thanks to any of these definitions, but
they need 14 or 11 bytes...

More options (2016-08-05):

----
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  inc h
  inc l
  ld a,h
  or l
  jp nz,false_
  jp true_

  ; 11 B
----

----
  _code_header minus_one_equals_,'-1='

  pop hl
minus_one_equals.hl:
  inc h
  inc l
  ld a,h
  or l
  jr nz,false_
  jr true_

  ; 09 B
----

.2016-05-18:

Remove the `root` word list. Set the minimum search order to `forth`.

.2016-05-18:

Improve `need` to make several index lines possible, by making `(` executable:

----
( very-long-word-1 very-long-word-2 very-long-word-3
very-long-word-4 very-long-word-5 very-long-word-6 )
----

Problem: this would force changes in fsb and fsb2.

.2016-05-18:

Factor `new-needed-word  2dup undefined?`.

.2016-05-17:

Improve the search order words, after Forth-2012.

.2016-05-17:

Add conditional compilation to the `user` module.

.2016-05-13:

Convert the sample games to .fs.

.2016-05-13:

Improve `?(` with `refill`, to cross block boundaries?
This would be needed  for `load-add`. Maybe two versions:
if `load-app` has been compiled, then compile the improved version of `?(`.

.2016-05-11:

Compact "strings.misc.fsb" and make `lengths` needed.

.2016-05-07:

Fix the `indexer` tool: indexing all words from the library (>800) fills the
system memory bank were headers are created.  The solution is a configurable
system bank: the indexer could use a different system bank, and reset the
names pointer temporarily. Update 2016-10-27: the extra-memory system is being
implemented, using 4 banks.

Document the Noble arrays.

.2016-05-06:

Remove the routine `compare_de_hl_signed`, if possible.

.2016-04-27:

Idea: `variable lastblk`, only for `block`, instead of `scr`, which will be
used only for `list`.

Rewrite `'` after Gforth. See Gforth's `(')`, `name?int`,
`name>int`, etc. Factor `defined` and `comp'` accordingly.

.2016-04-25:

Idea: Add `where` to the default exception message. In order to save space,
`where` should be in the library and patch itself into the default message.

.2016-04-25:

Benchmark the system without constants `0`, `1` and `2`.

2016-05-30:

With constants:    32598 B free.
Without constants: 32572 B free.
Diff:                +26 B

.2016-04-24:

Write faster, Z80 versions of words that fetch from and store to memory banks.

Words that can be moved to the library: `there`, `catch`, `?\`,
`[defined]`, `[undefined]`, `umin`, `umax`...

Study how to move `line>string` and `undefined?` to the library.  They are not
used in the kernel, but they are needed by the `need` utility.

Add `noname`, analogous to `nextname`, after Gforth.

.2016-04-16:

Fix Makefile: The loader and the main disk are built when the sources have not
changed.

Write `behead  ( "name" -- )`. DX-Forth uses `behead ( "name1" "name2" -- )`.
`hided  ( nt -- )` is already in the kernel.

// }}}
== Data ==
// {{{

// }}}
== Compilation ==
// {{{

.2016-10-24:

Change `need [if]` to `need ?(` in the library, when `[else]` is not needed.
`?(` is smaller and faster than `[if]`.

.2016-10-22:

16 KiB for the headers is not enough in some cases.
Make a second bank usable...

.2016-05-31:

Add `''` to get the execution token pointer of a name, so the actual name of
an alias could be get this way:

----
'' wordname >>name .name
----

.2016-05-15:

Check if `current-latest`, used in the library, can be replaced with `latest`.

.2016-05-09:

Idea: in DX-Forth, `last` is a 2-cell variable that holds both the nt and the
xt: `last @ ( nt )` and `last 2@ ( xt nfa )`.

.2016-04-29:

Factor the return stack manipulation done by `(.")` in order to
reuse it in `(abort")` and `(warning")`. Use a variant of pForth's `param`.

.2016-04-28:

Finish the implementation of control stack words.

.2016-04-21:

Make `jp pushhlde` a macro dependent of `size_optimization`: compile `jp
pushhlde` or `push de / push hl / jp (ix)`. The second option needs one more
byte but is 2 T-cycles faster.

.2015-11-12:

`+bal`, `-bal` or similar, to change `csp`:

----
: [+csp]  ( -- )  [ cell negate ] literal csp +!  ; immediate compile-only
: [-csp]  ( -- )  cell csp +!  ; immediate compile-only
----

But for compiling an external number inside a definition,
a trick is `[ dup ] literal` and a `drop` after `;`.

.2015-06-09:

In order to save compilation time, move inner words to the bottom of
the dictionary. Example: `(loop)`, `clit`, `back`, `digit`...

.2015-06-30:

Change: compare the user variables with those of Spectrum Forth-83.

.2016-03-19:

Separate header flags from the length byte of the name field.  This way more
bits will fit (alias, deferred, special behaviour), and word names will be
actual strings.

// }}}
== User interface ==
// {{{

.2015-06-30:

New: command history, stored in the names bank.

// }}}
== Local variables ==
// {{{

Examples from Forth Dimensions:

|===
| Title                                    | Vo  | N  | Pag | Note

| Turning the Stack into Local Variables   | 03  | 6  | 185 | Implemented: locals.arguments.fsb
| Anonymous Variables                      | 06  | 1  | 033 | Implemented: locals.anon.fsb
| Local Definitions                        | 06  | 6  | 016 | :( `privatize` is simpler
| Letter "Stack Your Locals"               | 07  | 5  | 005 | :( modification of Vo06N6
| Local Variables                          | 09  | 4  | 009 | :( complete but complex, and not recursive
| Letters "Local Variables"                | 09  | 5  | 005 | Implemented: locals.local.fsb
| Letters "Code for Local Variables"       | 10  | 1  | 006 | Modification for FD Vo09N4
| Headless Local Variables and Constants   | 10  | 1  | 019 | Interesting, but for F83
| Letters "Local Variables Revisited"      | 10  | 5  | 005 |
| Local Variables and Arguments            | 11  | 1  | 013 | Seen
| Local Variables - Another Technique      | 11  | 1  | 018 | Seen
| Prefix Frame Operators                   | 11  | 1  | 023 |
|===

// }}}
== Control structures ==
// {{{

.2016-05-07:

Idea: Rename `branch`, `0branch` and `?branch` to `(branch)`, `(0branch)` and
`(?branch)`.  Then write `branch`, `0branch` and `?branch` to compile them, as
control structures.

----
: branch  ( a -- )  postpone (branch) ,  ; immediate compile-only
: ?branch  ( a -- )  postpone (?branch) ,  ; immediate compile-only
: 0branch  ( a -- )  postpone (0branch) ,  ; immediate compile-only
----

Also `-branch`, in the library.

.2015-11-14:

Forth Dimensions v06n1p26: `it endit` control structure.

.2015-10-25:

Ideas from cmForth:

____

LOOP         Test the top item on the return stack.  If it is zero,
pop it off the return stack and continue executing the next
instruction. If it is not zero, decrement it and jump to the address
specified in this instruction.  Address specifier is the same as in
BRANCH.  LOOP is compiled by NEXT.

REPEATS      Repeat the next instruction if the count on top of the
return stack is not zero.  The count is also decremented.  If count is
zero, pop the return stack and continue executing the following
instruction.  REPEATS is  compiled by        TIMES or OF(.

The REPEATS instruction is used frequently to implement complicated
math operations, like shifts, multiply, divide and square root, from
appropriate math step instructions.  It is also useful in repeating
auto-indexing memory instructions.

____

// }}}
== Documentation ==
// {{{

.2016-10-24:

Common notation for text coordinates: "col row" --> "x y"?
Common notation for graphic coordinates: "x y" --> "gx gy"?

.2016-06-01:

Change the stack notation back to classic Forth?:

- xt -> cfa
- nt -> nfa
- pfa
- lfa

And change also:

- xtp -> cfaa

The problem with the standard notation is it does not has alternatives to pfa
and lfa, because they are system dependent and may not exist in all systems.
This make the notations xt, nt, pfa, lfa look heterogeneous. Beside, xt and nt
are abstract terms, while cfa and nfa are precise definitions for the
implemention.

.2016-06-01:

Put the "Origin" section of the glossary entries at the end of each entry.

.2016-05-11:

Homogenize the stack notation for character/bytes: only _c_.

.2016-04-29:

Homogenize the stack notation for blocks and block lines.

.2016-04-28:

Homogenize the notation "Run-time" to "Execution".

.2016-04-11:

Homogenize the following stack notations:

- double, triple and quadruple numbers (or include all used
  conventions in the documentation).

.2015-07-23:

Adapt the markups of Z88 CamelForth to extract the glossary from the
source.

// }}}
== Graphics ==
// {{{

.2015-09-01:

Possible names for text and graphic cursor words.

|===
| set txt pos| get txt pos| set graph pos   | get graph pos   | graph home

| at         | at@        | at-pixel        | at-pixel@       | home-pixel
| at         | at@        | gat             | gat@            | ghome
| at         | at@        | graphic-at      | graphic-at@     | graphic-home
| at         | at@        | xy-at           | xy-at@          | xy-home
| at-xy      | ?at        | gat-xy          | ?gat            | ghome
| at-xy      | at-xy@     | gat-xy          | gat-xy@         | ghome
| at-xy      | xy         | at-coord        | coord           | coord-home
| at-xy      | xy         | at-coord        | coord           | home-coord
| at-xy      | xy         | at-coords       | coords          | coords-home
| at-xy      | xy         | at-coords       | coords          | home-coords
| at-xy      | xy         | at-g-xy         | g-xy            | g-home
| at-xy      | xy         | at-gxy          | gxy             | ghome
| at-xy      | xy@        | at-coords       | coords@         | home-coords
| at-xy      | xy@        | at-gxy          | gxy@            | ghome
| at-xy      | xy@        | gat-xy          | gxy@            | ghome
| cursor!    | cursor@    | gcursor!        | gcursor@        | ghome
| cursor!    | cursor@    | graph-cursor!   | graph-cursor@   | graph-home
| cursor!    | cursor@    | graphic-cursor! | graphic-cursor@ | graphic-home
| cursor!    | cursor@    | xy!             | xy@             | xy-home
| cursor!    | cursor@    | xy-cursor!      | xy-cursor@      | xy-home
| set-cursor | get-cursor | set-coords      | get-coords      | home-coords
| set-cursor | get-cursor | set-xy          | get-xy          | home-xy
| set-xy     | get-xy     | set-gxy         | get-gxy         | ghome
|===

So far (2016-04-23) the best are:

|===
| set txt pos| get txt pos| set graph pos   | get graph pos   | graph home

| at-xy      | xy         | at-coord        | coord           | coord-home
| at-xy      | xy         | at-coord        | coord           | home-coord
| at-xy      | xy         | at-coords       | coords          | coords-home
| at-xy      | xy         | at-coords       | coords          | home-coords
| at-xy      | xy         | at-gxy          | gxy             | ghome
| at-xy      | xy         | at-g-xy         | g-xy            | g-home
|===

.2015-09-05:

Name for graphic fill: `flood`.

// }}}
== Screen modes ==
// {{{

.2015-09-05:

There's an example how to change and restore a channel in print-42, by
Ricardo Serral Wigge. Beside, it supports many (all?) control
characters, unlike the implementation by Andy Jenkinson.

.2015-09-11:

Idea: screen modes table?

- 0: 32 cpl original (ROM routines)
- 1: 32 cpl improved (bold, italic).
- 3: 36 cpl
- 4: 42 cpl
- 5: 51 cpl
- 6: 64 cpl

It seems more versatile to create one word to select every mode and provide a
common user interface to row, column, cpl, window...

// }}}
== Keyboard ==
// {{{

.2015-06-07:

Change: move key to the blocks, as `mode-key` or similar, and use a
simpler `key` (`akey` from Afera).

.2015-06-30:

Change: modify `expect` after Spectrum Forth-83.

// }}}
== Parsing ==
// {{{

.2016-06-01:

When loading an app with `load-app`, make `(` behave like in the
Forth-2012 FILE word set.

.2015-06-17:

New:
- Case-sensitive mode.
- Create words in lowercase.
- Improve `parse-name` with case conversion.

.2015-09-23:

Fix: `where` shows the offending word uppercased. This means somewhere the
original address hold in `parsed-word` is used by `uppers`.

.2015-10-15:

Adapt from Gforth: `noname`.

// }}}
== Errors ==
// {{{

.2015-09-20:

Idea:
____

The correlation between DX-Forth exception code and DOS error code
is given below:

 Exception   DOS
     0        0     no error
   -511       1     function number invalid (not used)
   -510       2     file not found
   -509       3     path not found
   -508       4     too many open files
   -507       5     access denied
   -506       6     invalid handle
    ...     ...
   -257     255     unspecified error

Note: To convert an exception code in the range -257 to -511 to its
corresponding DOS error code, use: 255 AND
____

.2015-10-18:

`.warning`

// }}}
== Files ==
// {{{

.2016-04-11:

Make the tape words return a standard _ior_.

Rename the tape and disk words after a common convention. Maybe after
Gforth `slurp-file` and Galope `unslurpe-file`: `slurp-tape-file`,
`unslurp-tape-file`, `slurp-file`, `unslurp-file`.

.2016-03-02:

Adapt all file words to standard _ior_; remove _f n_.

2016-04-09: already done?

.2015-09-18:

New: `.files` (from Pygmy Forth).

// }}}
== Misc new words ==
// {{{

.2015-06-10:

Adapt this word from Spectrum Forth-83, which uses it in `cold` and
`query`:

----
  : TERMINAL ( --- )
    LIT PKEY (KEY) !    \ Set default handler for KEY.
    >S ;                \ And initialize screen output.
----

.2015-07-23:

New: `lower` and `lowers`.

Idea: 2 more bytes for `base`, to be used as save-restore space.

----
  : exchange  ( a1 a2 -- )  2dup @ swap @  rot ! swap !  ;
    \ Exchange the 16-bit contents of a1 and a2.

  : cexchange  ( ca1 ca2 -- )  2dup c@ swap c@  rot c! swap c!  ;
    \ Exchange the 8-bit contents of a1 and a2.

  : switch  ( a1 -- )  dup cell+ exchange  ;
    \ Exchange the 16-bit contents of a1 and the following cell.

  \ Example:

  base switch hex

  base switch
----

.2015-09-12:

____

ROTATE         n1 n2 -- n3

     Rotate  the value n1 left n2 bits if n2 is positive, right  n2
     bits  if n2 is negative.  Bits shifted out of one end  of  the
     cell are shifted back in at the opposite end.

  \ Standard: Forth-79 (Reference Word Set); Forth-83 (Appendix
  \ B.  Uncontrolled Reference Words).
____

Implement a configurable case mode for `search` and `compare`? See how
Z88 CamelForth does it. Also DX-Forth has this feature.

.2015-09-13:

`rp` should be a user variable.

.2015-09-22:

`console` to do `display` and init the keyboard and `tib` (see
Spectrum Forth-83).

// }}}
== Sample games ==
// {{{

.2016-01-01:

Compilation of the tt game crash!  the offending word is marked.
something to do with the new loops?

// }}}
== Strings ==
// {{{

.2016-05-09:

Simplify the circular string buffer:

- convert `>csb` to a variable, and remove the extra cell at the start of the
  actual buffer.
- convert `csb0` to a variable, so the buffer can be moved.

.2016-06-10:

Rename "csb" as "stringer":

|===
| Now         | "stringer"

| >csb        | >stringer
| ?csb        | ?stringer
| csb-size    | /stringer
| csb0        | stringer
| empty-csb   | empty-stringer
| unused-csb  | unused-stringer
|===

.2015-11-10:

Move the circular string buffer to the top of memory.  Use `high` or
similar, like fig-Forth, to protect the string buffer and the heap. In
fact, the string buffer should be defined in the heap, but a small
implementation of the heap is needed. The problem is words compiled
above 0xC000 could not use the circular string buffer.

// }}}
== Maths ==
// {{{

.2016-05-07:

Implement 2-cell operators from Spectrum Forth-83. Most of them are written in Z80.

.2016-05-01:

Change the order of the parameters of `%` and `u%`, after _Starting Forth_ pp 103..105.

.2016-04-27:

Adapt `d>q`, `q>d`, `s>q`, `q+`, `q-`, `udm*` from Pygmy, in module
"math.operators.4-cell.fsb".

.2016-04-22:

Document floating point.

.2016-04-22:

Idea: Use the ROM calculator memories (0..5) as floating-point non-recursive
locals. Problem: some calculator's words use them (eg. `over`).  They could be
recursive, because their address can be changed with the system variable MEM;
they could be pointed to a frame in the return stack.

Simpler idea: use the calculator memories them as is, as temporary storage.
The ROM allocates 6*5 bytes, but 32*5 can be used.

.2016-04-19:

Floating-point words `flit`, `fliteral`. From PFE:
`fround>s`, `ftrunc>s` (being `f>s` a synonym), `1/f`, `f^2`, `f^n`, `f2/`,
`f2*`.

.2016-04-18:

Modify `interpret` to be patched by a floating-point implementation in order
to recognize floating-point numbers.

Make `number?` deferred, in order to add floating-point support.

.2016-04-17:

`factorial`, from Forth-2012 documentation: examples in `recurse` and
`repeat`.

.2015-12-24:

Fractional arithmetic, FD 4-1.

.2016-03-16:

Idea for improving `number?` or writing an optional alternative:
Return the chars and positions of every point, not only the last
one. Convert `dpl` to a backwards compatible array:

----
+0 cell: position of the last point
+2 byte: last point
+3 cell: position of the last but one point
+5 byte: last but one point
etc.
----

A new variable `#dpl` would hold the number of points.

// }}}
== Time ==
// {{{

.2015-12-14

Update the date with interrupts.

// }}}
== Printing ==
// {{{

.2016-10-27:

Add `vemits`, inspired by TI BASIC's `call vchar()`.

.2016-04-17:

Improve tab control.

// }}}
== Assembler ==
// {{{

.2016-04-20:

Make `call-xt` and `execute-hl` independent from the assemblers.

Change the stack notation of Z80 registers from _r rp_ to _reg regp_,
because _r_ is the standard for floating-point numbers.

// }}}
== G+DOS ==
// {{{

.2015-08-31:

Problem: SZX snapshots don't preserve the mounted disks or G+DOS!

The Plus D own snapshots can be used, but this means programs have to
be started manually, typing `run` in BASIC to load G+DOS, and then
loading the snapshot file from BASIC or an Autoload file.

.2015-08-31:

Fix: `transfer-block` changes the current drive to 2!

.2015-07-23:

Study how to save and load the main code and the name bank apart, in
two files. This way `turnkey` could be used also to save a modified
copy of the system, not just Forth programs. Simpler solution: use the
snapshop option of the Plus D, or save a snapshot from the emulator.

.2016-03-16:

Investigate how to use the free memory of the Plus D RAM.

// }}}
== +3DOS ==
// {{{

.2016-08-14:

`set-drive`, `open-disk` and `close-file` work on drive "a".  But when drive
"b" is used, `close-file` returns ior -1006 (unrecognised disk format). This
is problem of fsb2's fb2dsk.

// }}}
== TR-DOS ==
// {{{

.2016-10-15:

The new benchmarks don't fit a TR-DOS disk. The source of the benchmarks
should be splitted into several parts, e.g. maths, system, data...

.2016-09-01:

`read-mode 0 22528 1 transfer-sectors` works after but `read-mode 80 22528 1
transfer-sectors` hangs. `0 set-drive` or `1 set-drive` makes no difference.

.2016-08-11:

Make also 40S, 40D and 80S TRD disk images?

.2016-08-11:

Investigate if TR-DOS uses the IX register. If not, remove the restorings.

// }}}
== Sound ==
// {{{

.2016-08-01:

Rename `sound:` to `sound` and make the sounds sound when executed.

.2016-10-10:

Finish the conversion of 128K sound explosions. More details in the source.
