= Solo Forth version history
:author: Marcos Cruz (programandala.net)
:revdate: 2016-03-16

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

== 0.0

Developed from 2015-06-02 to 2015-12-18.

During this long initial period of the development, Solo Forth grew
from a small seed (the code of Abersoft Forth, a fig-Forth 1.1) to a
disk-based system, with only some small traces of fig-Forth left, with
many features of modern standard Forth systems and a huge library of
optional code.

Version branch 0.0 was finished after replacing the fig-Forth `do
loop` control structures with the Forth-83 version, adding a method to
nest sources (`nest-source` and `unnest-source`) and writing
`evaluate`.

== 0.1.0

Developed from 2015-12-18 to 2016-03-14.

Many fixes, changes and improvements. See the
http://programandala.net/en.program.solo_forth.history.html[development
history].

- The Vim syntax file for Solo Forth is included.

== 0.2.0

Released on 2016-03-14.

- The old alternative ITC code is removed.

== 0.3.0

Under development since 2016-03-14.

// XXX TODO --  summarize the commit messages since 0.2.0

