= Solo Forth %VERSION% %DOS%
:author: Marcos Cruz (programandala.net)
:revdate: 2018-04-10
:toc:
:toclevels: 1
:toc-placement!:
:linkattrs:

// Last modified 201804091515

toc::[]

// =============================================================

// == Description

include::../README.adoc[tags=description]

// == History and current status

include::../README.adoc[tags=history]

// == Supported computers and disk operating systems

include::../README.adoc[tags=computers]

== Status of each DOS support

=== G+DOS

==== Summary

include::../README.adoc[tags=gplusdos_support_summary]

==== Rationale

G+DOS was the first target (in fact, the only planned target at the
beginning), and it's also the author's platform of choice to develop
projects in Solo Forth, because of its excellent features:

- Fast disk operations.
- Big disk capacity (800 KiB for Forth blocks or 780 KiB for files).
- It uses only the RAM of the Plus D interface.

=== TR-DOS

==== Summary

include::../README.adoc[tags=trdos_support_summary]

==== Rationale

TR-DOS is slower than G+DOS, it uses 368 bytes of RAM from the main
computer memory, and the maximum capacity of its disks is smaller (636
KiB of useful space, either for Forth blocks or files), but it haves
some interesting features:

- TR-DOS can handle 4 disk drives at the same time. This makes it an
  interesting choice in some cases. For example, to compile a program
  from the third drive, using the library on the second drive during
  the process, and also reading or manipulating the files on the first
  drive (for example, graphics); or just to use a total of 2544 Forth
  blocks (`636 4 *`).
- TR-DOS is the DOS used by all of the Russian ZX Spectrum powerful
  clones: The Pentagon and Scorpion series are the best known among
  them.

=== +3DOS

==== Summary

include::../README.adoc[tags=plus3dos_support_summary]

==== Rationale

+3DOS uses 16 KiB of banked memory, but their features and API are
excellent and very well documented.

=== Comparative of DOS support

The following table shows the main disk-management words implemented
on each DOS.

[cols="3,1,1,1,4",caption="Main disk-related words implemented"]
|===
| Word              | G+DOS | TR-DOS | +3DOS | Comment

| `2-block-drives`  | YES   | YES    | YES   | Use the first two drives as block drives
| `3-block-drives`  | n/a   | YES    | n/a   | Use the first three drives as block drives
| `4-block-drives`  | n/a   | YES    | n/a   | Use the first four drives as block drives
| `>file`           | YES   | YES    |       | Save memory zone to a file
| `acat`            | YES   | YES    | YES   | Abbreviated disk catalogue
| `bank-read-file`  |       |        | YES   |
| `bank-write-file` |       |        | YES   |
| `bin`             |       |        | YES   | Standard Forth
| `cat`             | YES   | YES    | YES   | Detailed disk catalogue
| `close-file`      |       |        | YES   | Standard Forth
| `create-file`     |       |        | YES   | Standard Forth
| `delete-file`     | YES   | YES    | YES   | Standard Forth
| `drive-unused`    |       |        | YES   |
| `file-dir#`       | YES   | YES    |       |
| `file-dirdesc`    | YES   | n/a    |       |
| `file-exists?`    | YES   | YES    |       |
| `file-length`     | YES   | YES    |       |
| `file-position`   |       |        | YES   | Standard Forth
| `file-sector`     |       | YES    |       |
| `file-sectors`    |       | YES    |       |
| `file-size`       |       |        | YES   | Standard Forth
| `file-start`      | YES   | YES    |       |
| `file-status`     | YES   | YES    |       | Standard Forth
| `file-track`      |       | YES    |       |
| `file-type`       | YES   | YES    |       |
| `file>`           | YES   | YES    |       | Load file contents to memory zone
| `find-file`       | YES   | YES    |       |
| `flush-drive`     |       |        | YES   |
| `flush-file`      |       |        |       | Standard Forth
| `get-drive`       | YES   | YES    | YES   |
| `include-file`    |       |        |       | Standard Forth
| `include`         |       |        |       | Standard Forth
| `included`        |       |        |       | Standard Forth
| `open-file`       |       |        | YES   | Standard Forth
| `r/o`             |       |        | YES   | Standard Forth
| `r/w`             |       |        | YES   | Standard Forth
| `read-byte`       |       |        | YES   |
| `read-file`       |       |        | YES   | Standard Forth
| `read-line`       |       |        | YES   | Standard Forth
| `rename-file`     | YES   | YES    | YES   | Standard Forth
| `reposition-file` |       |        | YES   | Standard Forth
| `require`         |       |        |       | Standard Forth
| `required`        |       |        |       | Standard Forth
| `resize-file`     |       |        |       | Standard Forth
| `set-block-drives`| YES   | YES    | YES   | Set the drives used as block drives
| `set-drive`       | YES   | YES    | YES   |
| `undelete-file`   |       | YES    |       |
| `w/o`             |       |        | YES   | Standard Forth
| `wacat`           | YES   |        | YES   | Abbreviated disk catalogue with wildcards
| `wcat`            | YES   |        | YES   | Detailed disk catalogue with wildcards
| `write-byte`      |       |        | YES   |
| `write-file`      |       |        | YES   | Standard Forth
| `write-line`      |       |        | YES   | Standard Forth

|===

=== Comparative of block access speed

////////////////////////////////////////////////////////////////

// XXX OLD

In order to compare the block access speed on every platform, the
following code was executed with disk 1 (library) in the first drive
and disk 2 (programs) in the second drive:

---
1 load need dtimer
dticks need 2-block-drives need edit-sound dtimer
---

The test was run several times on every platform, and the fastest
result was noted.

Final results as of 2018-04-09, from fastest to slowest:

// XXX REMARK -- 2018-04-10: The results are wrong, because TR-DOS is
// actually the slowest system. It seems the ticks clock is not
// properly updated by TR-DOS. The test has to be repeated with a real
// clock.

|===
| Computer        | Interface| DOS    | Ticks | Ratio

| Pentagon 128    |          | TR-DOS | 11056 |
| Pentagon 1024   |          | TR-DOS | 11480 |
| Pentagon 512    |          | TR-DOS | 11526 |
| Scorpion ZS 256 |          | TR-DOS | 12395 |
| ZX Spectrum 128 | Beta 128 | TR-DOS | 14754 |
| ZX Spectrum +2  | Beta 128 | TR-DOS | 14774 |
| ZX Spectrum +2  | Plus D   | G+DOS  | 19018 |
| ZX Spectrum 128 | Plus D   | G+DOS  | 19778 |
| ZX Spectrum +3e |          | +3DOS  | 24347 |
| ZX Spectrum +3  |          | +3DOS  | 24505 |
|===

////////////////////////////////////////////////////////////////

The following table compares the block access speed on different
platforms.

The ticks clock can not be used for the tests, because it's not
regulary updated by the DOS during disk operations. A chronometer
watch was used instead.  The following line of code was executed with
disk 1 (library) in the first drive and disk 2 (programs) in the
second drive:

----
1 load 4 border need 2-block-drives need edit-sound 2 border
----

The tests were done running Solo Forth on the
http://fuse-emulator.sourceforge.net[Fuse emulator], on a Raspberry Pi
2 with Raspbian, at c. 700% the speed of the original machines.

// 2018-04-10:

[caption="Block access speed test in seconds"]
|===
| Computer        | Interface| DOS    | Seconds

| ZX Spectrum +3  |          | +3DOS  | 100
| ZX Spectrum +3e |          | +3DOS  | 101
| ZX Spectrum +2  | Plus D   | G+DOS  | 119
| ZX Spectrum 128 | Plus D   | G+DOS  | 121
| Scorpion ZS 256 |          | TR-DOS | 506
| ZX Spectrum 128 | Beta 128 | TR-DOS | 510
| ZX Spectrum +2  | Beta 128 | TR-DOS | 515
| Pentagon 128    |          | TR-DOS | 519
| Pentagon 1024   |          | TR-DOS | 523
| Pentagon 512    |          | TR-DOS | 528
|===

== Download

Solo Forth can be downloaded from two sites:

// XXX FIXME -- Asciidoctor bug?
//
// The following text creates a link with text
// "Solo Forth repository":
//
//- http://github.com/programandala-net/solo-forth[Solo Forth repository
//  in GitHub,role="external"]

- http://programandala.net/en.program.solo_forth.html[Solo Forth home page]
- http://github.com/programandala-net/solo-forth[Solo Forth repository in GitHub,role="external"]

// == Directory tree

include::../README.adoc[tags=tree]

// == Disks

include::../README.adoc[tags=disks]

=== About the disk image formats

==== MGT

The MGT disk image file format (used for G+DOS disks) does not include
format-describing metadata: The MGT file is just a dump of the
original 800-KiB disk. Beside, G+DOS does not need its own metadata
(the directory tracks) be present in order to read or write sectors.

That's why converting Forth sources to MGT disk images is most simple,
and the full capacity of the disks can be used to store the Forth
blocks.

All this means the MGT disk images actually are identical to Forth
block files, as used by modern Forth systems.  Therefore, for example,
they can be browsed with a Forth block editor.

==== TRD

Also the TRD disk images, one of the formats used for TR-DOS disk
images, are dumps of the original disks, without any format-describing
metadata. But, contrary to G+DOS, TR-DOS needs the system track (track
0) to contain certain data in order to recognize the disk, even for
sector-level access. That's why only 636 KiB can be used for Forth
blocks, 4 KiB (one track) less than the maximum capacity.

Anyway, TRD disk images can be browsed with a Forth block editor, with
the following restriction: blocks 0..3 will be shown as garbage (they
are track 0 of the disk), while the actual first Forth block of the
disk (block 0) will be shown as block 4.

==== DSK

The DSK disk image format, used for +3DOS and other systems, is quite
a different thing: It contains a lot of metadata to describe the
format of the disk, the tracks and the sectors...

On +3DOS, sector 0 of track 0 can not be used for Forth blocks,
because it must contain the disk specification, even for sector-level
access.  Since the size of a sector is 512 B, only one Forth block is
lost because of this restriction.

// == How to run

include::../README.adoc[tags=run]

// == Library

include::../README.adoc[tags=library]

=== Library index

The `need` word and its related words search the index line (line 0)
of all blocks of the disk for the first occurence of the required
word, within a configurable range of blocks (using the variables
`first-locatable` and `last-locatable`).  Of course, nested `need` are
resolved the same way: searching the library from the beginning.  This
can be slow.  This is not a problem, because the goal of Solo Forth is
cross development, and therefore only the last step of the development
loop, i.e., the compilation of the sources from the disk images
created in the host system, compilation that includes all the slow
searching of library blocks, is done in the real (actually, emulated)
machine. But the system includes a tool to create an index of the
library, which is used to locate their contents instantaneously, what
makes things more comfortable when the Forth system is used
interactively.

How to use the library index:

1. Load the indexer with `need make-thru-index`.
2. Make the index and activate it with `make-thru-index`.
3. The default behaviour (no index) can be restored with
   `use-no-index`.  The index can be reactivated with
   `use-thru-index`.

The indexer creates an index (actually, a Forth word list whose
definitions use no code or data space) and changes the default
behaviour of `need` and related words to use it. Then `need name` will
automatically start loading the first block where the word "name" is
defined.

:indexnote: Test done on Solo Forth 0.12.0 on ZX Spectrum 128.

.Time and memory required to make the library indexfootnote:[pass:a,[{indexnote}]]
|===
| DOS     | First block | Last block | Seconds | Bytes of far memory

| G+DOS   |           5 |        799 |     154 |               13498
| TR-DOS  |           5 |        635 |     135 |               13027
|===

NOTE: The far memory is the virtual 64-KiB space formed by 4
configurable memory banks. No code or data space is used by the
indexer.

An alternative indexer is under development. It's activated with
`use-fly-index` and does not make and index in advance: Instead, it
indexes the blocks on the fly, when they are searched the first time.
This indexer was included in Solo Forth 0.12.0 but it's not finished
yet.

=== How to search the source files

Three simple one-line wrapper scripts are included to search the Forth
sources for a regular expression: <tools/search_library>,
<tools/search_kernel> and <tools/search_source> (to search all files
in the <src> directory).

The scripts use `ack`. In order to use the more common `grep`, edit
the files.  `ack` and `grep` are compatible.

Their first parameter is the regular expression. An optional second
parameter is passed to `ack`.

Usage examples:

----
tools/search_source use-thru-index
tools/search_source use-thru-index -l
tools/search_kernel color
tools/search_kernel ";\s:\s"
tools/search_library "\-bank"
tools/search_library "code\s+\S+\s+\("
----

== How to use the additional source disks

When the needed source is in a different disk than the library,
`set-block-drives` must be used first in order to configure the drives
used as block drives, and their order. For example, this is the case
when you want to try the simple sample games from
<disks/\*/disk_2_programs.\*> or the benchmarks and tests
from <disks/\*/disk_3_workbench.\*>.

The following example is for G+DOS.  First, "Insert" the file
<disks/gplusdos/disk_1_library.mgt> as disk 1.  Then, "Insert" the
file <disks/gplusdos/disk_2_programs.mgt> as disk 2. Then
enter the following commands to load the Pong game:

----
cold \ just to start from scratch, if needed
1 load \ load the `need` utility from the library
need set-block-drives
2 1 2 set-block-drives
need pong
----

Note the last parameter of `set-block-drives` is the number of the
drives used as block drives. The last but one parameter is the
identifier of the first drive used for blocks. Note also G+DOS uses
drive identifiers 1 and 2; TR-DOS uses 0, 1, 2 and 3; +3DOS uses
letters 'A' and 'B'.  See the glossary entry of `set-block-drives` for
more details.

[id=_test]
== How to test and benchmark

Besides many little specific tests and benchmarks used during the
development of Solo Forth probably not interesting for the application
programmer, disk image number 3 (called "workbench") contains also and
adapted version of the Hayes test and some known benchmarks.

First, in order to access disk image number 3, follow these steps:

. <<_run,Run Solo Forth>> or enter `cold` to start from scratch.
. "Insert" the file <disks/\*/disk_1_library.\*> (the <<_disks,actual
  subdirectory and filename>> depend on your DOS) into the first disk
  drive of your emulated machine, if it's not already "inserted".
. "Insert" the file <disks/\*/disk_3_workbench.\*> (the
  <<_disks,actual subdirectory and filename>> depend on your DOS) into
  the second disk drive of your emulated machine, if it's not already
  "inserted".
. Enter command `1 load` to load the `need` tool.
. Enter command `need 2-block-drives` to set the first two disk drives
  as block drives, in their normal order.

Now the first two disk drives are used as block drives, and `need`
will search both of them in the normal order: first the first one (the
library), then the second one (the benchmarks and tests).

Note `need 2-block-drives` not only loads the word `2-block-drives`,
but also executes it. This is equivalent to the following commands:

- On G+DOS: `need set-block-drives 2 1 2 set-block-drives`
- On TR-DOS: `need set-block-drives 1 0 2 set-block-drives`
- On +3DOS: `need set-block-drives 'B' 'A' 2 set-block-drives`

Second, depending on the code you want to run, enter the corresponding
command:

. `need hayes-test`
. `need byte-magazine-benchmark`
. `need interface-age-benchmark`
. `need vector-loop-benchmark`
. `need all-benchmarks` to run all the three benchmarks above

[id=_write]
== How to write Forth programs

In order to use Solo Forth to write programs for ZX Spectrum,
programmers already acquainted with Forth and GNU/Linux systems can
extract all the required information from the <Makefile> of Solo
Forth.

The only difference between <<__rebuild,building Solo Forth>> and
building a Forth program is the content of disk 0 (the boot disk), if
needed, and the library modules included in disk 1 (the library disk),
which usually also contains the source of the program.  If the program
does not need to use the disk at run-time, you can simply copy the
default disk 0, and boot it to load your program from block 1 of your
customized disk 1, with a simple `1 load`. When the loading finishes,
you can save a system snapshot, in SZX format, using the corresponding
option of your ZX Spectrum emulator.

Some simple little games are provided as examples, in <<_disks,disk
3>>.  Some of them are not finished yet.

In order to try, improve and fix the Forth system during its
development, two more complex game projects are being developed at the
same time:

- http://programandala.net/en.program.black_flag.html[Black Flag]
  (http://github.com/programandala-net/black-flag[Black Flag in
  GitHub]).
- http://programandala.net/en.program.nuclear_waste_invaders.html[Nuclear
  Waste Invaders]
  (http://github.com/programandala-net/nuclear-waste-invaders[Nuclear
  Waste Invaders in GitHub]).

They are not finished yet, but they can be useful as examples of
program development with Solo Forth.

// [id=_vim]
// == Vim support
//
// XXX TODO --

// In order to make Vim recognize and highlight the Solo Forth sources,
// with the ".fsb" extension, copy the contents of the <vim> directory
// to your home <~/.vim/> directory.

[id=_rebuild]
== How to rebuild

If you modify the sources, you have to build new disk images for your
DOS of choice. Also the manual depends on the documentation included
in the sources.

First, see the requirements listed in the header of the <Makefile>
file and install the required programs. Then enter the project
directory and use one of the following commands to build the disk
images or the manual for your DOS of choice:

.Commands to rebuild Solo Forth
|===
| DOS          | Disk images                 | Documentation

| G+DOS        | `make gplusdos` or `make g` | `make gplusdosdoc` or `make gdoc`
| TR-DOS (all) | `make trdos` or `make t`    | `make trdosdoc` or `make tdoc`
| TR-DOS (128k only) | `make t128`           |
| TR-DOS (Pentagon 512/1024 only) | `make pentagon` |
| TR-DOS (Scorpion ZS 256 only)   | `make scorpion` |
| +3DOS        | `make plus3dos` or `make p` | `make plus3dosdoc` or `make pdoc`
| All of them  | `make all` or `make`        | `make doc`
|===

The disk images will be created in the <disks> directory. The HTML
manual will be created in the <doc> directory.

== Notation

// =============================================================
