= Solo Forth %VERSION% %DOS%
:author: Marcos Cruz (programandala.net)
:revdate: 2018-06-16
:toc:
:toclevels: 1
:toc-placement!:
:linkattrs:

// This file is part of Solo Forth
// http://programandala.net/en.program.solo_forth.html

// Last modified 201806102152

toc::[]

// =============================================================

// Description {{{1
// == Description

include::doc.README.linked.adoc[tags=description]

// History and current status {{{1
// == History and current status

include::doc.README.linked.adoc[tags=history]

// Supported computers and disk operating systems {{{1
// == Supported computers and disk operating systems

include::doc.README.linked.adoc[tags=platforms]

// DOS support {{{1
== DOS support

// +3DOS {{{2
=== +3DOS

// Summary {{{3
==== Summary

include::doc.README.linked.adoc[tags=plus3dos_support_summary]

// Rationale {{{3
==== Rationale

+3DOS uses 16 KiB of banked memory, but their features and API are
excellent and very well documented.

// G+DOS {{{2
=== G+DOS

// Summary {{{3
==== Summary

include::doc.README.linked.adoc[tags=gplusdos_support_summary]

// Rationale {{{3
==== Rationale

G+DOS was the first target (in fact, the only planned target at the
beginning), and it's also the author's platform of choice to develop
projects in Solo Forth, because of its excellent features:

- Fast disk operations.
- Big disk capacity (800 KiB for Forth blocks or 780 KiB for files).
- It uses only the RAM of the Plus D interface.

// TR-DOS {{{2
=== TR-DOS

// Summary {{{3
==== Summary

include::doc.README.linked.adoc[tags=trdos_support_summary]

// Rationale {{{3
==== Rationale

TR-DOS is more than 5 times slower than +3DOS and G+DOS, it uses
368 bytes of RAM from the main computer memory, and the maximum
capacity of its disks is smaller (636 KiB of useful space, either for
Forth blocks or files), but it haves some interesting features:

- TR-DOS can handle 4 disk drives. This makes it an interesting choice
  in some cases. For example, to compile a program from the fourth
  drive, using the library on the second and third drives during the process,
  while reading or manipulating the files on the first drive (for
  example, graphics); or just to use a total of 2544 Forth blocks
  (``636 4 *``).
- TR-DOS is used by Pentagon and Scorpion, the powerful Russian clones
  of ZX Spectrum.

// Comparative of DOS support {{{2
=== Comparative of DOS support

The following table shows the main disk-management words implemented
on each DOS.

[%autowidth]
.Main disk-related words implemented
|===
| Word              | +3DOS | G+DOS | TR-DOS | Comment

| `2-block-drives`  | YES   | YES   | YES    | Use the first two drives as block drives
| `3-block-drives`  | n/a   | n/a   | YES    | Use the first three drives as block drives
| `4-block-drives`  | n/a   | n/a   | YES    | Use the first four drives as block drives
| `>file`           |       | YES   | YES    | Save memory zone to a file
| `acat`            | YES   | YES   | YES    | Abbreviated disk catalogue
| `bank-read-file`  | YES   |       |        |
| `bank-write-file` | YES   |       |        |
| `bin`             | YES   |       |        | Standard Forth
| `cat`             | YES   | YES   | YES    | Detailed disk catalogue
| `close-file`      | YES   |       |        | Standard Forth
| `create-file`     | YES   |       |        | Standard Forth
| `delete-file`     | YES   | YES   | YES    | Standard Forth
| `drive-unused`    | YES   |       |        |
| `file-dir#`       |       | YES   | YES    |
| `file-dirdesc`    |       | YES   | n/a    |
| `file-exists?`    |       | YES   | YES    |
| `file-length`     |       | YES   | YES    |
| `file-position`   | YES   |       |        | Standard Forth
| `file-sector`     |       |       | YES    |
| `file-sectors`    |       |       | YES    |
| `file-size`       | YES   |       |        | Standard Forth
| `file-start`      |       | YES   | YES    |
| `file-status`     |       | YES   | YES    | Standard Forth
| `file-track`      |       |       | YES    |
| `file-type`       |       | YES   | YES    |
| `file>`           |       | YES   | YES    | Load file contents to memory zone
| `find-file`       |       | YES   | YES    |
| `flush-drive`     | YES   |       |        |
| `flush-file`      |       |       |        | Standard Forth
| `get-block-drives`| YES   | YES   | YES    | Get the drives used as block drives
| `get-drive`       | YES   | YES   | YES    |
| `include-file`    |       |       |        | Standard Forth
| `include`         |       |       |        | Standard Forth
| `included`        |       |       |        | Standard Forth
| `open-file`       | YES   |       |        | Standard Forth
| `r/o`             | YES   |       |        | Standard Forth
| `r/w`             | YES   |       |        | Standard Forth
| `read-byte`       | YES   |       |        |
| `read-file`       | YES   |       |        | Standard Forth
| `read-line`       | YES   |       |        | Standard Forth
| `rename-file`     | YES   | YES   | YES    | Standard Forth
| `reposition-file` | YES   |       |        | Standard Forth
| `require`         |       |       |        | Standard Forth
| `required`        |       |       |        | Standard Forth
| `resize-file`     |       |       |        | Standard Forth
| `set-block-drives`| YES   | YES   | YES    | Set the drives used as block drives
| `set-drive`       | YES   | YES   | YES    |
| `undelete-file`   |       |       | YES    |
| `w/o`             | YES   |       |        | Standard Forth
| `wacat`           | YES   | YES   |        | Abbreviated disk catalogue with wildcards
| `wcat`            | YES   | YES   |        | Detailed disk catalogue with wildcards
| `write-byte`      | YES   |       |        |
| `write-file`      | YES   |       |        | Standard Forth
| `write-line`      | YES   |       |        | Standard Forth

|===

// Download {{{1
== Download

Solo Forth can be downloaded from two sites:

// XXX FIXME -- Asciidoctor bug?
//
// The following text creates a link with text
// "Solo Forth repository":
//
//- http://github.com/programandala-net/solo-forth[Solo Forth repository
//  in GitHub,role="external"]

- http://programandala.net/en.program.solo_forth.html[Solo Forth home page]
- http://github.com/programandala-net/solo-forth[Solo Forth repository in GitHub,role="external"]

// Directory tree {{{1
// == Directory tree

include::doc.README.linked.adoc[tags=tree]

// Disks {{{1
// == Disks

include::doc.README.linked.adoc[tags=disks]

// About the disk image formats {{{2
=== About the disk image formats

// DSK {{{3
==== DSK

The DSK disk image format, used for +3DOS and other systems, is quite
a different thing: It contains a lot of metadata to describe the
format of the disk, the tracks and the sectors...

On +3DOS, sector 0 of track 0 can not be used for Forth blocks,
because it must contain the disk specification, even for sector-level
access.  Since the size of a sector is 512 B, only one Forth block is
lost because of this restriction.

// MGT {{{3
==== MGT

The MGT disk image file format (used for G+DOS disks) does not include
format-describing metadata: The MGT file is just a dump of the
original 800-KiB disk. Beside, G+DOS does not need its own metadata
(the directory tracks) be present in order to read or write sectors.

That's why converting Forth sources to MGT disk images is most simple,
and the full capacity of the disks can be used to store the Forth
blocks.

All this means the MGT disk images actually are identical to Forth
block files, as used by modern Forth systems.  Therefore, for example,
they can be browsed with a Forth block editor.

// TRD {{{3
==== TRD

Also the TRD disk images, one of the formats used for TR-DOS disk
images, are dumps of the original disks, without any format-describing
metadata. But, contrary to G+DOS, TR-DOS needs the system track (track
0) to contain certain data in order to recognize the disk, even for
sector-level access. That's why only 636 KiB can be used for Forth
blocks, 4 KiB (one track) less than the maximum capacity.

Anyway, TRD disk images can be browsed with a Forth block editor, with
the following restriction: blocks 0..3 will be shown as garbage (they
are track 0 of the disk), while the actual first Forth block of the
disk (block 0) will be shown as block 4.

// How to run {{{1
// == How to run

include::doc.README.linked.adoc[tags=run]

// Library {{{1
// == Library

include::doc.README.linked.adoc[tags=library]

// Library index {{{2
=== Library index

The `need` word and its related words search the index line (line 0)
of all blocks of the disk for the first occurence of the required
word, within a configurable range of blocks (using the variables
`first-locatable` and `last-locatable`).  Of course, nested `need` are
resolved the same way: searching the library from the beginning.  This
can be slow.  This is not a problem, because the goal of Solo Forth is
cross development, and therefore only the last step of the development
loop, i.e., the compilation of the sources from the disk images
created in the host system, compilation that includes all the slow
searching of library blocks, is done in the real (actually, emulated)
machine. But the system includes a tool to create an index of the
library, which is used to locate their contents instantaneously, what
makes things more comfortable when the Forth system is used
interactively.

How to use the library index:

1. Load the indexer with ``need make-thru-index``.
2. Make the index and activate it with `make-thru-index`.
3. The default behaviour (no index) can be restored with
   `use-no-index`.  The index can be reactivated with
   `use-thru-index`.

The indexer creates an index (actually, a Forth word list whose
definitions use no code or data space) and changes the default
behaviour of `need` and related words to use it. Then ``need name``
will automatically start loading the first block where the word "name"
is defined.

:indexnote: Test done on Solo Forth 0.12.0 on ZX Spectrum 128.

[%autowidth]
.Time and memory required to make the library indexfootnote:[pass:a,[{indexnote}]]
|===
| DOS     | First block | Last block | Seconds | Bytes of far memory

| G+DOS   |           5 |        799 |     154 |               13498
| TR-DOS  |           5 |        635 |     135 |               13027
|===

NOTE: The far memory is the virtual 64-KiB space formed by 4
configurable memory banks. No code or data space is used by the
indexer.

An alternative indexer is under development. It's activated with
`use-fly-index` and does not make and index in advance: Instead, it
indexes the blocks on the fly, when they are searched the first time.
This indexer was included in Solo Forth 0.12.0 but it's not finished
yet.

// How to search the source files {{{2
=== How to search the source files

Three simple one-line wrapper scripts are included to search the Forth
sources for a regular expression: <tools/search_library>,
<tools/search_kernel> and <tools/search_source> (to search all files
in the <src> directory).

The scripts use ``ack``. In order to use the more common ``grep``,
edit the files.  ``ack`` and ``grep`` are compatible.

Their first parameter is the regular expression. An optional second
parameter is passed to ``ack``.

Usage examples:

----
tools/search_source use-thru-index
tools/search_source use-thru-index -l
tools/search_kernel color
tools/search_kernel ";\s:\s"
tools/search_library "\-bank"
tools/search_library "code\s+\S+\s+\("
----

// How to use more than one block disk {{{1
== How to use more than one block disk

The programs included in disk 2, and the tests and benchmarks included
in disk 3, need to load words from the library, which is in disk(s) 1.
Therefore, both disk drives must be configured first as block drives,
using `2-block-drives`.

Let's see an example, how to load the game called Tetris for
Terminals, which is in disk 2 and depends on the library, which is in
disk 1:

. <<_run,Run Solo Forth>>.
. Insert the library disk image (disk 1) into the first drive.
. Insert the programs disk image (disk 2) into the second drive.
. Execute command ``1 load`` in order to load the `need` utility from
  the library disk.
. Execute the command `need 2-block-drives`, which loads
  `2-block-drives` from the library disk and executes it, setting the
  first and the second drives as block drives.
. Execute the command ``need tt``, which locates the first block of
  the game (in disk 2) and loads it, loading its requirements from the
  library (disk 1) as needed.
. Follow the instructions.

When `2-block-drives` is executed, the blocks of the first two disk
drives are seen as one single set, i.e. ``200 list`` will list block
200 from the first disk, but ``850 list`` will list the block from the
second disk:

[%autowidth]
.Range of blocks per drive in normal order
|===
| DOS    | 1st drive | 2nd drive | 3rd drive | 4th drive

| +3DOS  | 0-718     | 719-1437  | n/a       | n/a
| G+DOS  | 0-799     | 800-1599  | n/a       | n/a
| TR-DOS | 0-635     | 636-1271  | 1272-1908 | 1909-2544
|===

Since TR-DOS can handle four disk drives, `3-block-drives` and
`4-block-drives` are included in its library.

`2-block-drives` is a layer above `set-block-drives`, which can
configure any number of block drives in any order. Examples:

----
    2 1 2 set-block-drives \ identical to ``2-block-drives`` on G+DOS
'b' 'a' 2 set-block-drives \ identical to ``2-block-drives`` on +3DOS
    1 0 2 set-block-drives \ identical to ``2-block-drives`` on TR-DOS
    1 2 2 set-block-drives \ use both drives in reverse order on G+DOS
  2 3 1 3 set-block-drives \ use three drives in special order on TR-DOS
  2 1 0 3 set-block-drives \ identical to ``3-block-drives`` on TR-DOS
3 2 1 0 4 set-block-drives \ identical to ``4-block-drives`` on TR-DOS
----

[id=_test]
// How to test and benchmark {{{1
== How to test and benchmark

Besides many little specific tests and benchmarks used during the
development of Solo Forth probably not interesting for the application
programmer, disk image number 3 (called "workbench") contains also and
adapted version of the Hayes test and some known benchmarks.

// First, set the required block disks {{{2
=== First, set the required block disks

// On G+DOS {{{3
==== On G+DOS

. <<_run,Run Solo Forth>> or enter `cold` to start from scratch.
. "Insert" the file <disks/gplusdos/disk_1_library.mgt> into disk drive 1 of
  your emulated machine.
. "Insert" the file <disks/gplusdos/disk_3_workbench.mgt> into disk drive 2 of
  your emulated machine.
. Enter command ``1 load`` to load the ``need`` tool.
. Enter command ``need 2-block-drives`` to set both disk drives as block drives
  in their normal order, making `need` search both of them: first drive 1 (the
  library), then drive 2 (the benchmarks and tests).  Note ``need
  2-block-drives`` not only loads the word `2-block-drives`, but also executes
  it. This is equivalent to the command ``need set-block-drives 2 1 2
  set-block-drives``

// On +3DOS {{{3
==== On +3DOS

. <<_run,Run Solo Forth>> or enter `cold` to start from scratch.
. "Insert" the file <disks/plus3dos/disk_1_library.dsk> into the disk drive 'A'
  of your emulated machine.
. "Insert" the file <disks/plus3dos/disk_3_workbench.dsk> into the disk drive
  'B' of your emulated machine.
. Enter command ``1 load`` to load the ``need`` tool.
. Enter command ``need 2-block-drives`` to set both disk drives as block drives
  in their normal order, making `need` search both of them: first drive 'A'
  (the library), then drive 'B' (the benchmarks and tests).  Note ``need
  2-block-drives`` not only loads the word `2-block-drives`, but also executes
  it. This is equivalent to the command ``need set-block-drives 'B' 'A' 2
  set-block-drives``

// On TR-DOS {{{3
==== On TR-DOS

. <<_run,Run Solo Forth>> or enter `cold` to start from scratch.
. "Insert" the files <disks/trdos/disk_1a_library.trd> and
  <disks/trdos/disk_1b_library.trd> into drives 'A' and 'B' respectively of
  your emulated machine.
. "Insert" the file <disks/trdos/disk_3_workbench.trd> into disk drive 'C' of
  your emulated machine.
. Enter command ``1 load`` to load the ``need`` tool.
. Enter command ``need 3-block-drives`` to set the first three disk drives as
  block drives, in their normal order, making `need` search all of them: first
  drive 'A'/0 (the first part of the library), then drive 'B'/1 (the second
  part of the library), and finally drive 'C'/2 (the benchmarks and tests) Note
  ``need 3-block-drives`` not only loads the word `3-block-drives`, but also
  executes it. This is equivalent to the command ``need set-block-drives 2 1 0
  3 set-block-drives``.

// Second, load the desired code {{{2
=== Second, load the desired code

Depending on the code you want to run, enter the corresponding command:

. ``need hayes-test``
. ``need byte-magazine-benchmark``
. ``need interface-age-benchmark``
. ``need vector-loop-benchmark``
. ``need all-benchmarks`` to run all the three benchmarks above

[id=_write]
// How to write Forth programs {{{1
== How to write Forth programs

// XXX TODO --

Briefly, the steps of cross development are the following:

. Edit the sources of the Forth program on the host operating system, using the
  simple FSB format described in the documentation of
  http://programandala.net/en.program.fsb.html[fsb] and
  http://programandala.net/en.program.fsb2.html[fsb2].
. Convert the sources into Forth block disk images using
  http://programandala.net/en.program.fsb2.html[fsb2].
. <<_run,Run Solo Forth>> on a ZX Spectrum emulator and compile the Forth
  program from the disk image. Further testing and debugging can be done in the
  Forth system.

In order to use Solo Forth to write programs for ZX Spectrum,
programmers already acquainted with Forth and GNU/Linux systems can
extract all the required information from the <Makefile> of Solo
Forth.

The only difference between <<_rebuild,building Solo Forth>> and
building a Forth program is the content of disk 0 (the boot disk), if
needed, and the library modules included in the library disk,
which usually also contains the source of the program at the end.  If the program
does not need to use the disk at run-time, you can simply copy the
default disk 0, and boot it to load your program from block 1 of your
customized disk 1, with a simple ``1 load``. When the loading
finishes, you can save a system snapshot, in SZX format, using the
corresponding option of your ZX Spectrum emulator.

Some games are provided as examples, in <<_disks,disk 2>>.  In order
to try, improve and fix the Forth system during its development, two
more complex game projects are being developed at the same time:

- http://programandala.net/en.program.black_flag.html[Black Flag]
  (http://github.com/programandala-net/black-flag[Black Flag in
  GitHub]).
- http://programandala.net/en.program.nuclear_waste_invaders.html[Nuclear
  Waste Invaders]
  (http://github.com/programandala-net/nuclear-waste-invaders[Nuclear
  Waste Invaders in GitHub]).

They are not finished yet, but they can be useful as examples of
program development with Solo Forth.

// [id=_vim]
// == Vim support
//
// XXX TODO --

// In order to make Vim recognize and highlight the Solo Forth sources,
// with the ".fsb" extension, copy the contents of the <vim> directory
// to your home <~/.vim/> directory.

[id=_rebuild]
// How to rebuild Solo Forth {{{1
== How to rebuild Solo Forth

If you modify the sources, you have to build new disk images for your
DOS of choice. Also the manual depends on the documentation included
in the sources.

First, see the requirements listed in the header of the <Makefile>
file and install the required programs. Then enter the project
directory and use one of the following commands to build the disk
images or the manual for your DOS of choice:

[%autowidth]
.Commands to rebuild Solo Forth
|===
| DOS    | Computers         | Disk images                       | Documentation

| All    | All               | ``make all`` or ``make``          | ``make doc``
| +3DOS  | All               | ``make plus3dos`` or ``make p``   | ``make plus3dosdoc`` or ``make pdoc``
| G+DOS  | All               | ``make gplusdos`` or ``make g``   | ``make gplusdosdoc`` or ``make gdoc``
| TR-DOS | 128-KiB models    | ``make trdos128`` or ``make t128` |
| TR-DOS | All               | ``make trdos`` or ``make t``      | ``make trdosdoc`` or ``make tdoc``
| TR-DOS | Pentagon 512/1024 | ``make pentagon``                 |
| TR-DOS | Scorpion ZS 256   | ``make scorpion``                 |
|===

The disk images will be created in the <disks> directory. The manual
will be created in the <doc> directory.

// Exception codes {{{1
== Exception codes

The `throw` values -255..-1 are used only as assigned by the Forth-2012
standard.  The values -4095..-256 are reserved by Solo Forth.

Programs shall not define values for use with `throw` in the range -4095..-1.

=== +3DOS

include::doc.plus3dos.exception_codes.adoc[]

=== G+DOS

include::doc.gplusdos.exception_codes.adoc[]

=== TR-DOS

include::doc.trdos.exception_codes.adoc[]

// Notation {{{1
== Notation

// =============================================================

// vim: foldmethod=marker
