= Solo Forth %VERSION% %DOS%
:author: Marcos Cruz (programandala.net)
:revdate: 2017-02-21
:toc:
:toclevels: 1
:toc-placement!:
:linkattrs:

// Last modified 201702212050

toc::[]

// =============================================================

// == Description

include::../README.adoc[tags=description]

// == History and current status

include::../README.adoc[tags=history]

// == Supported computers and disk operating systems

include::../README.adoc[tags=computers]

=== Rationale of the supported disk operating systems

==== G+DOS

This was the first target (in fact, the only planned target at the
beginning), and it's also the platform of choice for development of
projects in Solo Forth, because of its excellent features:

- Very fast disk operations.
- Big disk capacity (800 KiB for Forth blocks or 780 KiB for files).
- It uses only the RAM of the Plus D interface.

==== TR-DOS

TR-DOS is much slower than G+DOS, it uses 368 bytes RAM from the main
computer memory, and the maximum capacity of its disks is smaller (636
KiB of useful space, either for Forth blocks or files), but it haves
some interesting features:

- TR-DOS handle 4 disk drives at the same time. This makes it an
  interesting choice in some cases. For example, to compile a program
  from the third drive, using the library on the second drive during
  the process, and also reading or manipulating the files on the first
  drive; or just to use a total 2544 Forth blocks (636*4).
- TR-DOS is the DOS used by all of the Russian ZX Spectrum powerful
  clones: The Pentagon and Scorpion series are the most well known of
  them.

==== +3DOS

+3DOS is also slower than G+DOS, and somehow its by-design kind of
compatibility with CP/M is an issue. Also, it uses banked memory, what
forces Solo Forth change the way it works on G+DOS or TR-DOS.

But the features and API of +3DOS are excellent and very well
documented. And anyway it's the door to support the more advanced
IDEDOS and ResiDOS in the future.

=== Future targets

The DOS support in Solo Forth is modular, so in theory it would not be
too difficult to support also other DOS in future versions. There are
some ideas:

Porting the G+DOS version of Solo Forth to its close relatives GDOS,
Beta DOS and Uni-DOS will require only minor changes, beside adding
some library code to benefit from their specific features.

Supporting the powerful Russian ZX Spectrum compatible computers,
Pentagon and Scorpion, which also use TR-DOS, will not be difficult.
Some models provide 1024 MiB of RAM, among other interesting features.

Supporting a more powerful and modern DOS like
http://www.worldofspectrum.org/zxplus3e/technical.html[IDEDOS,role="external"],
http://www.worldofspectrum.org/residos/[ResiDOS,role="external"], and
http://esxdos.org[esxDOS,role="external"] would require more effort,
but would let Solo Forth use hard drives, flash cards, and a lot of
memory, beside many other new features.

Porting the G+DOS version of Solo Forth to http://worldofsam.org[SAM
Coupé,role="external"] (the powerful cousin of ZX Spectrum) would not
be a trivial task, but feasible...

== Download

Solo Forth can be downloaded from two sites:

- http://programandala.net/en.program.solo_forth.html[Solo Forth home
  page]
- http://github.com/programandala-net/solo-forth[Solo Forth repository
  in GitHub,role="external"]

// == Directory tree

include::../README.adoc[tags=tree]

// == Disks

include::../README.adoc[tags=disks]

=== Notes on the disk image formats

.MGT

The MGT disk image file format (used for G+DOS disks) does not include
format-describing metadata: The MGT file is just a dump of the
original 800-KiB disk. Beside, G+DOS does not need its own metadata
(the directory tracks) be present in order to read or write sectors.

That's why converting Forth sources to MGT disk images is most simple,
and the full capacity of the disks can be used to store the Forth
blocks.

All this means the MGT disk images actually are identical to Forth
blocks files, as used by modern Forth systems.  Therefore, for
example, they can be browsed with a Forth blocks editor.

.TRD

Also the TRD disk images, one of the formats used for TR-DOS disk
images, are dumps of the original disks, without any format-describing
metadata. But, contrary to G+DOS, TR-DOS needs the system track (track
0) to contain certain data in order to recognize the disk, even for
sector-level access. That's why only 636 KiB can be used for Forth
blocks, 4 KiB (one track) less than the maximum capacity.

Anyway, TRD disk images can be browsed with a Forth blocks editor,
with the following restriction: blocks 0..3 will be shown as garbage
(they are track 0 of the disk), while the actual first Forth block of
the disk (block 0) will be shown as block 4.

.DSK

The DSK disk image format, used for +3DOS and other systems, is quite
a different thing: It contains a lot of metadata to describe the
format of the disk, the tracks and the sectors...

// == How to run

include::../README.adoc[tags=run]

// == Library

include::../README.adoc[tags=library]

=== Library index

The `need` word and its related words search the index line (line 0)
of all blocks of the disk for the first occurence of the required
word, within a configurable range of blocks (using the variables
`first-locatable` and `last-locatable`).  Of course, nested `need` are
resolved the same way: searching the library from the beginning.  This
can be slow.  This is not a problem, because the goal of Solo Forth is
cross development, and therefore only the last step of the development
loop, i.e., the compilation of the sources from the disk images
created in the host system, compilation that includes all the slow
searching of library blocks, is done in the real (actually, emulated)
machine. But the system includes a tool to create an index of the
library, which is used to locate their contents instantaneously, what
makes things more comfortable when the Forth system is used
interactively.

How to use the library index:

1. Load the indexer with `need make-thru-index`.
2. Make the index and activate it with `make-thru-index`.
3. The default behaviour (no index) can be restored with
   `use-no-index`.  The index can be reactivated with
   `use-thru-index`.

The indexer creates an index (actually, a Forth word list whose
definitions use no code or data space) and changes the default
behaviour of `need` and related words to use it. Then `need name` will
automatically start loading the first block where the word "name" is
defined.

:indexnote: Test done on Solo Forth 0.12.0 on ZX Spectrum 128.

.Time and memory required to make the library indexfootnote:[pass:a,[{indexnote}]]
|===
| DOS     | First block | Last block | Seconds | Bytes of far memory

| G+DOS   |           5 |        799 |     154 |               13498
| TR-DOS  |           5 |        635 |     135 |               13027
|===

NOTE: The far memory is the virtual 64-KiB space formed by 4
configurable memory banks. No code or data space is used by the
indexer.

An alternative indexer is under development. It's activated with
`use-fly-index` and does not make and index in advance: Instead, it
indexes the blocks on the fly, when they are searched the first time.
This indexer was included in Solo Forth 0.12.0 but it's not finished
yet.

=== How to search the source files

Three simple one-line wrapper scripts are included to search the Forth
sources for a regular expression: <tools/search_library>,
<tools/search_kernel> and <tools/search_source> (to search all files
in the <src> directory).

The scripts use `ack`. In order to usu the more common `grep`, edit
the files.  `ack` and `grep` are compatible.

Their first parameter is the regular expression. An optional second
parameter is passed to `ack`.

Usage examples:

----
tools/search_source use-thru-index
tools/search_source use-thru-index -l
tools/search_kernel color
tools/search_kernel ";\s:\s"
tools/search_library "\-bank"
tools/search_library "code\s+\S+\s+\("
----

== How to use the additional source disks

Section pending.

// == How to write Forth programs

[id=_write]
== How to write Forth programs

In order to use Solo Forth to write programs for ZX Spectrum,
programmers already acquainted with Forth and GNU/Linux systems can
extract all the required information from the <Makefile> of Solo
Forth.

The only difference between <<__rebuild,building Solo Forth>> and
building a Forth program is the contents of disk 0 (the boot disk), if
needed, and the library modules included in disk 1 (the library disk),
which usually also contains the source of the program.  If the program
does not need to use the disk at run-time, you can simply copy the
default disk 0, and boot it to load your program from block 1 of your
customized disk 1, with a simple `1 load`. When the loading finishes,
you can save a system snapshot, in SZX format, using the corresponding
option of your ZX Spectrum emulator.

Some simple little games are provided as examples, in <<_disks,disk
3>>.  Some of them are not finished yet.

In order to try and fix the Forth system during its development, two
more complex game projects are being developed at the same time.  One
of them has been published:
http://programandala.net/en.program.black_flag.html[Black Flag]
(http://github.com/programandala-net/black-flag[Black Flag in
GitHub]).  It's not finished, but it can be useful as an example of
development with Solo Forth.

[id=_vim]
== Vim support

In order to make Vim recognize and highlight the Solo Forth sources,
with the ".fsb" extension, copy the contents of the <vim> directory
to your home <~/.vim/> directory.

[id=_rebuild]
== How to rebuild

If you modify the sources, you have to build new disk images for your
DOS of choice. Also the manual depends on the documentation included
in the sources.

First, see the requirements listed in the header of the <Makefile>
file and install the required programs. Then enter the project
directory and use one of the following commands to build the disk
images or the manual for your DOS of choice:

.Commands to rebuild Solo Forth
|===
| DOS          | Disk images                 | Documentation

| G+DOS        | `make gplusdos` or `make g` | `make gplusdosdoc` or `make gdoc`
| TR-DOS (all) | `make trdos` or `make t`    | `make trdosdoc` or `make tdoc`
| TR-DOS (Pentagon 512/1024 only) | `make pentagon` |
| TR-DOS (Scorpion ZS 256 only)   | `make scorpion` |
| +3DOS        | `make plus3dos` or `make p` | `make plus3dosdoc` or `make pdoc`
| All of them  | `make all` or `make`        | `make doc`
|===

The disk images will be created in the <disks> directory. The HTML
manual will be created in the <doc> directory.

// =============================================================
