#!/bin/sh

# search_library

# Search the library of Solo Forth for the regex $1.

# 2016-04-17: First version.
# 2016-04-24: Add $2 for optional parameters.
# 2017-02-27: Chang filename extension to "fs".

ack $1 $2 -r ~/forth/solo_forth/src/lib/*.fs
