#!/bin/sh

# search_sources

# This file is part of Solo Forth
# http://programandala.net/en.program.solo_forth.html

# Last modified: 202003012155

# Search the sources of Solo Forth using ack (by default) or grep
# (when ack is not installed).  All parameters and options are passed
# to the searcher.

# 2020-03-01

dirs="./src/kernel*.z80s ./src/lib/*.fs"

ack $* -r $dirs 2>/dev/null || \
grep $* -r $dirs 2>/dev/null

